force-app/main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <label>Milestone</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Milestone Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Milestone</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone__c/fields/Expected_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_End_Date__c</fullName>
    <description>Expected End Date</description>
    <label>Actual End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/Expected_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_Start_Date__c</fullName>
    <description>Expected Start Date</description>
    <label>Actual Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/Lead_Time__c.field-meta.xml
<CustomField>
    <fullName>Lead_Time__c</fullName>
    <label>Lead Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Milestone</label>
    <referenceTo>Milestone__c</referenceTo>
    <relationshipLabel>Milestone</relationshipLabel>
    <relationshipName>Milestone</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/Number_Of_Sub_MileStone_Records__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Sub_MileStone_Records__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number Of Sub-MileStone Records</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/Total_No_Of_Tasks_Under_Sub_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Total_No_Of_Tasks_Under_Sub_Milestone__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total No Of Tasks Under Sub-Milestone</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Milestone</fullName>
            </value>
            <value>
                <fullName>Sub-Milestone</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <label>Task</label>
    <nameField>
        <displayFormat>T-{0000}</displayFormat>
        <label>Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/fields/Expected_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_End_Date__c</fullName>
    <description>Expected End Date</description>
    <label>Expected End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Expected_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_Start_Date__c</fullName>
    <description>Expected Start Date</description>
    <label>Expected Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Milestone</label>
    <referenceTo>Milestone__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Task__c.field-meta.xml
<CustomField>
    <fullName>Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Task</label>
    <referenceTo>Task__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Total_No_Of_Task_Records__c.field-meta.xml
<CustomField>
    <fullName>Total_No_Of_Task_Records__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total No Of Task Records</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Task</fullName>
            </value>
            <value>
                <fullName>Sub-Task</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TasktriggerHandler_Test.cls
@isTest
public class TasktriggerHandler_Test{
    static testMethod void countMilestone_TestMethod(){
        Test.startTest();
        SC_MI_TestHandler.insertIsTriggerExecute();
        SC_MI_TestHandler.insertCustomDate();
        
        Milestone__c mile = new Milestone__c();
        mile.Title__c= 'Production';
        mile.Expected_Start_Date__c = system.Today();
        mile.Expected_End_Date__c = system.Today()+2;
        mile.Lead_Time__c = 1;
        mile.Number_Of_Sub_MileStone_Records__c = 0;
        mile.Total_No_Of_Tasks_Under_Sub_Milestone__c =0;
        insert mile;
        
        Milestone__c mile1 = new Milestone__c();
        mile1.Title__c= 'Production';
        mile1.Expected_Start_Date__c = system.Today();
        mile1.Expected_End_Date__c = system.Today()+2;
        mile1.Lead_Time__c = 1;
        mile1.Number_Of_Sub_MileStone_Records__c = 0;
        mile1.Total_No_Of_Tasks_Under_Sub_Milestone__c =0;
        insert mile1;
        
        Milestone__c subMile1 = new Milestone__c();
        subMile1.Title__c= 'Production';
        subMile1.Milestone__c = mile.id;
        subMile1.Expected_Start_Date__c = system.Today();
        subMile1.Expected_End_Date__c = system.Today()+2;
        subMile1.Lead_Time__c = 1;
        submile1.Total_No_Of_Tasks_Under_Sub_Milestone__c =0;
        submile1.Number_Of_Sub_MileStone_Records__c = 0;
        insert subMile1;
        
        Milestone__c subMile2 = new Milestone__c();
        subMile2.Title__c= 'Production';
        subMile2.Milestone__c = mile.id;
        subMile2.Expected_Start_Date__c = system.Today();
        subMile2.Expected_End_Date__c = system.Today()+2;
        subMile2.Number_Of_Sub_MileStone_Records__c=0;
        submile2.Total_No_Of_Tasks_Under_Sub_Milestone__c =0;
        submile2.Number_Of_Sub_MileStone_Records__c = 0;
        subMile2.Lead_Time__c = 1;
        insert subMile2;
        
        Milestone__c subMile3 = new Milestone__c();
        subMile3.Title__c= 'Production';
        subMile3.Milestone__c = mile.id;
        subMile3.Expected_Start_Date__c = system.Today();
        subMile3.Expected_End_Date__c = system.Today()+2;
        subMile3.Lead_Time__c = 1;
        submile3.Total_No_Of_Tasks_Under_Sub_Milestone__c =0;
        submile3.Number_Of_Sub_MileStone_Records__c = 0;
        insert subMile3;
        
        delete subMile3;
        
        Task__c task = new Task__c();
        task.Milestone__c = subMile2.id;
        task.Title__c = 'Test';
        task.Type__c='Task';
    //    task.Total_No_Of_Task_Records__c=0;
        insert task;
        
        Task__c subtask = new Task__c();
        subtask.Title__c = 'Test';
        subtask.Task__c= task.id;
        subtask.Type__c='Sub-Task';
        subtask.Total_No_Of_Task_Records__c=0;
        insert subtask ;
        
         Task__c subtask1 = new Task__c();
        subtask1.Title__c = 'Test1';
        subtask1.Task__c= task.id;
        subtask1.Type__c='Sub-Task';
        subtask1.Total_No_Of_Task_Records__c=0;
        insert subtask1;
        
     /*   submile2.Total_No_Of_Tasks_Under_Sub_Milestone__c =1;
        update submile2;*/
        
        delete subTask1;
       // delete subTask;
        delete task;
       
        Test.stopTest();

        
    }
     
}