force-app/main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <label>Milestone</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Milestone Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Milestone</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Milestone</label>
    <referenceTo>Milestone__c</referenceTo>
    <relationshipLabel>Milestone</relationshipLabel>
    <relationshipName>Milestone</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/Number_Of_Sub_MileStone_Records__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Sub_MileStone_Records__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number Of Sub-MileStone Records</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/MilestoneTriggerHandler.cls
public class MilestoneTriggerHandler{

    /****************************************************************************************************/
    // To count number of sub-milestone type records based on insert and update which is used for project planner
    
    
    public static void increaseCountInParentMileStone(list<Milestone__c> listMileStone){
        Map<Id,Integer> countSubMileStone=new Map<Id,Integer>();
        for(Milestone__c mStone:listMileStone){
            if(mStone.Milestone__c != null) {
                if(!countSubMileStone.containsKey(mStone.Milestone__c)) {
                        countSubMileStone.put(mStone.Milestone__c , 1);
                 }else {
                        countSubMileStone.put(mStone.Milestone__c , countSubMileStone.get(mStone.Milestone__c)+1);
                }
             }
        }
        system.debug('countSubMileStone='+countSubMileStone);
        List<Milestone__c> mileStonelist = new List<Milestone__c>();
        
        for(Milestone__c milStones: [SELECT Id, Number_Of_Sub_MileStone_Records__c FROM Milestone__c WHERE Id IN : countSubMileStone.keySet()] ) {
           if(milStones.Number_Of_Sub_MileStone_Records__c>=1){
                milStones.Number_Of_Sub_MileStone_Records__c += countSubMileStone.get(milStones.Id);
           }else{
                milStones.Number_Of_Sub_MileStone_Records__c = countSubMileStone.get(milStones.Id);
           }
            mileStonelist.add(milStones);
        }
        if(!mileStonelist.isEmpty())
        update mileStonelist;
    }
    
    /*********************************************************************************************************************/
    
    /**********************************************************************************************************************/
    // To count or to decrease the number of sub-task type records based on after delete event which is used for project planner
     
    public static void decreaseCountInParentMileStone(list<Milestone__c> listMileStone){
        Map<Id,Integer> countSubMileStone=new Map<Id,Integer>();
        for(Milestone__c mStone:listMileStone){
            if(mStone.Milestone__c != null) {
                if(!countSubMileStone.containsKey(mStone.Milestone__c)) {
                        countSubMileStone.put(mStone.Milestone__c , 1);
                 }else {
                        countSubMileStone.put(mStone.Milestone__c , countSubMileStone.get(mStone.Milestone__c)-1);
                }
             }
        }
        system.debug('countSubMileStone='+countSubMileStone);
        List<Milestone__c> mileStonelist = new List<Milestone__c>();
        
        for(Milestone__c milStones: [SELECT Id, Number_Of_Sub_MileStone_Records__c FROM Milestone__c WHERE Id IN : countSubMileStone.keySet()] ) {
           if(milStones.Number_Of_Sub_MileStone_Records__c>=1){
                milStones.Number_Of_Sub_MileStone_Records__c -= countSubMileStone.get(milStones.Id);
           }/*else{
                milStones.Number_Of_Sub_MileStone_Records__c -= countSubMileStone.get(milStones.Id);
           }*/
            mileStonelist.add(milStones);
        }
        if(!mileStonelist.isEmpty())
        update mileStonelist;
    }
    
    /*******************************************************************************************************************/
}