force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>URLString For the Opportunity Record</description>
    <label>URLString</label>
</CustomObject>

force-app/main/default/objects/Whatsapp_Message__c/Whatsapp_Message__c.object-meta.xml
<CustomObject>
    <label>Whatsapp Message</label>
    <nameField>
        <label>Whatsapp Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Whatsapp Message</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Whatsapp_Message__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Whatsapp Message</relationshipLabel>
    <relationshipName>Whatsapp_Message</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/WhatsappQuoteAPI_Test.cls
@isTest
public class WhatsappQuoteAPI_Test{

  @isTest 
  static void testSucess() 
  {
       Account personAcc=new Account(LastName='John',PersonEmail='Johnsdas@gmail.com',Customer_ID__c='Ben-d-2000027174');
        insert personAcc;
        
         Opportunity perOpp=new Opportunity(Name='John Arjun',AccountId=personAcc.Id,stageName='D1 initiated',
                                                closeDate=system.today(),amount=200,
                                                Opportunity_Stage__c ='Appointment Successful'
                                        );
                                                insert perOpp;
        
        test.starttest();
            String json = '{"oppId":"'+perOpp.id+'","response_msg":"Count"}';
            
                    Whatsapp_Message__c whats = new  Whatsapp_Message__c(
                                                    Name='WA - Quote',Opportunity__c=perOpp.id
                                    );       
        insert whats;    
            
            RestRequest req = new RestRequest();
            req.addHeader('Content-Type','application/json');
            req.RequestURI = '/services/apexrest/WhatsappQuoteAPI';
            req.HTTPMethod = 'POST';
            req.requestBody = Blob.valueOf(json);
            
            RestResponse res = new RestResponse();
            RestContext.Request = req;
            RestContext.Response = res;  
            WhatsappQuoteAPI.leadPush();     
        test.stoptest();
  }
  @isTest 
  static void testFail() 
  {
       Account personAcc=new Account(LastName='John',PersonEmail='Johnsdas@gmail.com',Customer_ID__c='Ben-d-2000027174');
        insert personAcc;
        
         Opportunity perOpp=new Opportunity(Name='John Arjun',AccountId=personAcc.Id,stageName='D1 initiated',
                                                closeDate=system.today(),amount=200,
                                                Opportunity_Stage__c ='Appointment Successful'
                                        );
                                                insert perOpp;
                                                
        Whatsapp_Message__c whats = new  Whatsapp_Message__c(
                                                    Name='WA - Quote',Opportunity__c=perOpp.id
                                    );       
        insert whats;                                        
        
        test.starttest();
            String json = '{"oppId":"perOpp.id","response_msg":"Count"}';
            
            RestRequest req = new RestRequest();
            req.addHeader('Content-Type','application/json');
            req.RequestURI = '/services/apexrest/WhatsappQuoteAPI';
            req.HTTPMethod = 'POST';
            req.requestBody = Blob.valueOf(json);
            
            RestResponse res = new RestResponse();
            RestContext.Request = req;
            RestContext.Response = res;  
            WhatsappQuoteAPI.leadPush();     
        test.stoptest();
  }
}