force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>URLString For the Opportunity Record</description>
    <label>URLString</label>
</CustomObject>

force-app/main/default/objects/SC_Item__c/SC_Item__c.object-meta.xml
<CustomObject>
    <label>SC Item</label>
    <nameField>
        <displayFormat>SCIN-{00000}</displayFormat>
        <label>SC Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SC Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SC_Item__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SC_User_Response__c/SC_User_Response__c.object-meta.xml
<CustomObject>
    <label>SC User Response</label>
    <nameField>
        <displayFormat>SCUR-{0000}</displayFormat>
        <label>SC User Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SC User Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SC_User_Response__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Item</label>
    <referenceTo>SC_Item__c</referenceTo>
    <relationshipLabel>SC User Responses</relationshipLabel>
    <relationshipName>SC_User_Responses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SC_User_Response__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>SC User Responses</relationshipLabel>
    <relationshipName>SC_User_Responses1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SC_User_Response__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Quote Rejected - Unable To Contact</fullName>
            </value>
            <value>
                <fullName>Initial Quote Rejected - Follow Up Later</fullName>
            </value>
            <value>
                <fullName>Initial Quote Rejected - Property on Hold</fullName>
            </value>
            <value>
                <fullName>IQ Follow Up - Unable To Contact</fullName>
            </value>
            <value>
                <fullName>IQ Follow Up - Follow Up Later</fullName>
            </value>
            <value>
                <fullName>IQ Follow Up - Property on Hold</fullName>
            </value>
            <value>
                <fullName>Customer Needs More Time</fullName>
            </value>
            <value>
                <fullName>Customer Not Free To Talk</fullName>
            </value>
            <value>
                <fullName>Initial Quote Approved</fullName>
            </value>
            <value>
                <fullName>Initial Quote Rejected</fullName>
            </value>
            <value>
                <fullName>Site Measurement Proposed</fullName>
            </value>
            <value>
                <fullName>Site Measurement Meeting Confirmed</fullName>
            </value>
            <value>
                <fullName>Site Measurement Completed</fullName>
            </value>
            <value>
                <fullName>Site Measurements Uploaded</fullName>
            </value>
            <value>
                <fullName>3D Design &amp; Quote Uploaded</fullName>
            </value>
            <value>
                <fullName>3D Design &amp; Quote Reviewed by Buddy</fullName>
            </value>
            <value>
                <fullName>Site Measurement Rescheduled</fullName>
            </value>
            <value>
                <fullName>Site Measurement Cancelled</fullName>
            </value>
            <value>
                <fullName>3D Design &amp; Quote Sent</fullName>
            </value>
            <value>
                <fullName>Design Presentation Proposed</fullName>
            </value>
            <value>
                <fullName>Design Presentation Confirmed</fullName>
            </value>
            <value>
                <fullName>Design Presentation Completed</fullName>
            </value>
            <value>
                <fullName>Final 3D Design &amp; Quote Sent</fullName>
            </value>
            <value>
                <fullName>3D Design &amp; Quote Approved</fullName>
            </value>
            <value>
                <fullName>3D Design &amp; Quote Rejected</fullName>
            </value>
            <value>
                <fullName>Production Drawings Uploaded</fullName>
            </value>
            <value>
                <fullName>Production Drawings &amp; Quote Review Complete</fullName>
            </value>
            <value>
                <fullName>Production Drawings Sent</fullName>
            </value>
            <value>
                <fullName>Project Kick-off Proposed</fullName>
            </value>
            <value>
                <fullName>Project Kick-off Meeting Confirmed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SC_User_Response__c/fields/User_Response__c.field-meta.xml
<CustomField>
    <fullName>User_Response__c</fullName>
    <label>User Response</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/ViewCheckListD2Controller.cls
public without sharing class ViewCheckListD2Controller{
    public list<SC_User_Response__c> scUserList{get;set;}
     public string emailOpp;
    public ViewCheckListD2Controller(ApexPages.StandardController Controller){
      String opportunityID = ApexPages.currentPage().getParameters().get('Id');
      if(opportunityID!=''){
          scUserList = [SELECT  Opportunity__r.Name,Opportunity__c,CreatedDate,Opportunity__r.Customer_Email__c,Stage__c,item__r.item__c,User_Response__c,Opportunity__r.Sub_Status__c from SC_User_Response__c 
                        WHERE Opportunity__c =: opportunityID AND Stage__c='Design Presentation Confirmed' limit 50000];  
       } 
       if(scUserList.size()==0 || Test.IsRunningTest()){
          ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,'Checklist for D2 Initiated is not yet generated'));   
      }
      
    }
    public PageReference sendEmail(){
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
        //PageReference pageRef = page.ViewCheckListPDF;
        PageReference pageRef= new PageReference('/ViewD2CheckListPDF?id='+scUserList[0].Opportunity__r.id);
        pageRef.setRedirect(true);
        Blob content;
        if (Test.IsRunningTest())
        {
            content=Blob.valueOf('UNIT.TEST');
        }
        else
        {
            content=pageRef.getContent();
        }
        //Blob b = pageRef.getContent();
        emailOpp= scUserList.get(0).Opportunity__r.Customer_Email__c;
        system.debug('===emailOpp==='+emailOpp);
        system.debug('==scUserList.get(0).Opportunity__r.Customer_Email__c=='+scUserList.get(0).Opportunity__r.Customer_Email__c);
        Messaging.EmailFileAttachment efa = new Messaging.EmailFileAttachment();
        efa.setFileName('attachment.pdf');
        efa.setBody(content);
        email.setSubject('Feedback');
        email.setToAddresses(new String[] { emailOpp});
        String messageBody = '<html><body>Hi ' + scUserList.get(0).Opportunity__r.Name + ',<br/><br/>The requested checklist for D2 Initated has been attached below. <br><br>Thanks&Regards<br>HomeLane Team</body></html>';
        email.setHtmlBody( messageBody );
        email.setFileAttachments(new Messaging.EmailFileAttachment[] {efa});
        email.setSaveAsActivity(true);
        Messaging.SendEmailResult [] res = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email}); 
         
        return pageRef;
    
    }
}