force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>URLString For the Opportunity Record</description>
    <label>URLString</label>
</CustomObject>

force-app/main/default/objects/SC_Item__c/SC_Item__c.object-meta.xml
<CustomObject>
    <label>SC Item</label>
    <nameField>
        <displayFormat>SCIN-{00000}</displayFormat>
        <label>SC Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SC Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SC_Item__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SC_Item__c/fields/Response_Type__c.field-meta.xml
<CustomField>
    <fullName>Response_Type__c</fullName>
    <label>Response Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PickList</fullName>
            </value>
            <value>
                <fullName>Multi PickList</fullName>
            </value>
            <value>
                <fullName>Check Box</fullName>
            </value>
            <value>
                <fullName>Open Text</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SC_Response__c/SC_Response__c.object-meta.xml
<CustomObject>
    <label>SC Response</label>
    <nameField>
        <displayFormat>SCRN-{0000}</displayFormat>
        <label>SC Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SC Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SC_Response__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <referenceTo>SC_Item__c</referenceTo>
    <relationshipLabel>SC Responses</relationshipLabel>
    <relationshipName>SC_Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SC_Response__c/fields/Required_for_Next_Stage__c.field-meta.xml
<CustomField>
    <fullName>Required_for_Next_Stage__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Required for Next Stage</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SC_Section_Item__c/SC_Section_Item__c.object-meta.xml
<CustomObject>
    <label>SC Section Item</label>
    <nameField>
        <displayFormat>SCSI-{0000}</displayFormat>
        <label>SC Section Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SC Section Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SC_Section_Item__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Item</label>
    <referenceTo>SC_Item__c</referenceTo>
    <relationshipLabel>SC Section Items</relationshipLabel>
    <relationshipName>SC_Section_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SC_User_Response__c/SC_User_Response__c.object-meta.xml
<CustomObject>
    <label>SC User Response</label>
    <nameField>
        <displayFormat>SCUR-{0000}</displayFormat>
        <label>SC User Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SC User Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SC_User_Response__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Item</label>
    <referenceTo>SC_Item__c</referenceTo>
    <relationshipLabel>SC User Responses</relationshipLabel>
    <relationshipName>SC_User_Responses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SC_User_Response__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>SC User Responses</relationshipLabel>
    <relationshipName>SC_User_Responses1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SC_User_Response__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Quote Rejected - Unable To Contact</fullName>
            </value>
            <value>
                <fullName>Initial Quote Rejected - Follow Up Later</fullName>
            </value>
            <value>
                <fullName>Initial Quote Rejected - Property on Hold</fullName>
            </value>
            <value>
                <fullName>IQ Follow Up - Unable To Contact</fullName>
            </value>
            <value>
                <fullName>IQ Follow Up - Follow Up Later</fullName>
            </value>
            <value>
                <fullName>IQ Follow Up - Property on Hold</fullName>
            </value>
            <value>
                <fullName>Customer Needs More Time</fullName>
            </value>
            <value>
                <fullName>Customer Not Free To Talk</fullName>
            </value>
            <value>
                <fullName>Initial Quote Approved</fullName>
            </value>
            <value>
                <fullName>Initial Quote Rejected</fullName>
            </value>
            <value>
                <fullName>Site Measurement Proposed</fullName>
            </value>
            <value>
                <fullName>Site Measurement Meeting Confirmed</fullName>
            </value>
            <value>
                <fullName>Site Measurement Completed</fullName>
            </value>
            <value>
                <fullName>Site Measurements Uploaded</fullName>
            </value>
            <value>
                <fullName>3D Design &amp; Quote Uploaded</fullName>
            </value>
            <value>
                <fullName>3D Design &amp; Quote Reviewed by Buddy</fullName>
            </value>
            <value>
                <fullName>Site Measurement Rescheduled</fullName>
            </value>
            <value>
                <fullName>Site Measurement Cancelled</fullName>
            </value>
            <value>
                <fullName>3D Design &amp; Quote Sent</fullName>
            </value>
            <value>
                <fullName>Design Presentation Proposed</fullName>
            </value>
            <value>
                <fullName>Design Presentation Confirmed</fullName>
            </value>
            <value>
                <fullName>Design Presentation Completed</fullName>
            </value>
            <value>
                <fullName>Final 3D Design &amp; Quote Sent</fullName>
            </value>
            <value>
                <fullName>3D Design &amp; Quote Approved</fullName>
            </value>
            <value>
                <fullName>3D Design &amp; Quote Rejected</fullName>
            </value>
            <value>
                <fullName>Production Drawings Uploaded</fullName>
            </value>
            <value>
                <fullName>Production Drawings &amp; Quote Review Complete</fullName>
            </value>
            <value>
                <fullName>Production Drawings Sent</fullName>
            </value>
            <value>
                <fullName>Project Kick-off Proposed</fullName>
            </value>
            <value>
                <fullName>Project Kick-off Meeting Confirmed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SC_User_Response__c/fields/User_Response__c.field-meta.xml
<CustomField>
    <fullName>User_Response__c</fullName>
    <label>User Response</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/SC_OpportunityStageValidation.cls
/*
 * Description : To validate and display Message to user whether Opportunity is ready to move to next Stage or not.
 * Created Date: 11/02/2016
 * Created By  : Naveen Kumar B H
*/
public class SC_OpportunityStageValidation { 
    @AuraEnabled
    public static Boolean SC_OpportunityStageValidate(Id OpportunityId, String StageName,List<SC_Section_Item__c> listSectn){
        try{
            /* 
             * Query to get SC_Item,SC_User_Response__c(child of SC_Item) and SC_Response__c(child of SC_Item).
             * From SC_Response__c object , we are querying only responses which are required to move to next stage. 
            */
            
            Set<Id> setItemId = new Set<Id>();
            for(SC_Section_Item__c secItm : listSectn){
                setItemId.add(secItm.Item__c);
            }
            for(SC_Item__c item : [SELECT Id,Item__c,Response_Type__c,
                                   (SELECT Item__c,Stage__c,User_Response__c 
                                    FROM SC_User_Responses__r 
                                    WHERE Stage__c =: StageName 
                                    AND Opportunity__c =: OpportunityId),
                                   (SELECT Answer__c,Is_Active__c,Item__c,Required_for_Next_Stage__c,Score__c 
                                    FROM  SC_Responses__r 
                                    WHERE Required_for_Next_Stage__c = TRUE)  
                                   FROM SC_Item__c 
                                   WHERE (Response_Type__c = 'Picklist' OR Response_Type__c = 'Check Box' OR Response_Type__c = 'Date') AND Id IN : setItemId]){
                                       
                                       if(!item.SC_Responses__r.isEmpty()){
                                           if(!item.SC_User_Responses__r.isEmpty()){
                                               //To check all question's response, setting flag value to false for each question.
                                               Boolean flag = false;
                                               if(item.Response_Type__c == 'Picklist'){
                                                   for(SC_Response__c response : item.SC_Responses__r){ 
                                                       if(item.SC_User_Responses__r[0].User_Response__c == response.Answer__c){
                                                           //Settting flag as TRUE if user response is in response list which is required to move to next stage.
                                                           flag = true;
                                                       }
                                                   }
                                               }else if(item.Response_Type__c == 'Check Box'){
                                                   if(item.SC_User_Responses__r[0].User_Response__c == 'true'){
                                                       flag = true;
                                                   }
                                               }
                                               else {
                                                   if(item.SC_User_Responses__r[0].User_Response__c != null && item.SC_User_Responses__r[0].User_Response__c != ''){
                                                       system.debug('***********'+item.SC_User_Responses__r[0].User_Response__c);
                                                       flag = true;
                                                   }

                                               }
                                               if(!flag){
                                                   //If any one of required questioned is not answered or other answer is given then not ready message will be displayed.
                                                   return false;
                                               }
                                           }else{
                                               return false;
                                           }
                                       }            
                                   }
        }
        catch(Exception e){
            System.debug('Exception ----->'+e);
            // if all requred answers are given, then method will return true. And Redy to move message will be displayed.
            return true;
        }
        return true;
    }
}