force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>URLString For the Opportunity Record</description>
    <label>URLString</label>
</CustomObject>

force-app/main/default/objects/Whatsapp_Message__c/Whatsapp_Message__c.object-meta.xml
<CustomObject>
    <label>Whatsapp Message</label>
    <nameField>
        <label>Whatsapp Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Whatsapp Message</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Whatsapp_Message__c/fields/Call_Back_Request__c.field-meta.xml
<CustomField>
    <fullName>Call_Back_Request__c</fullName>
    <label>Call Back Request</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inside Business Hours</fullName>
            </value>
            <value>
                <fullName>Outside Business Hours</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Whatsapp_Message__c/fields/Delivered__c.field-meta.xml
<CustomField>
    <fullName>Delivered__c</fullName>
    <label>Delivered</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Whatsapp_Message__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Whatsapp Message</relationshipLabel>
    <relationshipName>Whatsapp_Message</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Whatsapp_Message__c/fields/Quote_Link_Click__c.field-meta.xml
<CustomField>
    <fullName>Quote_Link_Click__c</fullName>
    <label>Quote Link Click #</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Whatsapp_Message__c/fields/Quote_WA_Message__c.field-meta.xml
<CustomField>
    <fullName>Quote_WA_Message__c</fullName>
    <label>Quote WA Message</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Whatsapp_Message__c/fields/Read__c.field-meta.xml
<CustomField>
    <fullName>Read__c</fullName>
    <label>Read</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Whatsapp_Message__c/fields/Responded__c.field-meta.xml
<CustomField>
    <fullName>Responded__c</fullName>
    <label>Responded?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Whatsapp_Message__c/fields/Responded_First_Time__c.field-meta.xml
<CustomField>
    <fullName>Responded_First_Time__c</fullName>
    <label>Responded First Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Whatsapp_Message__c/fields/Responded_Last_Time__c.field-meta.xml
<CustomField>
    <fullName>Responded_Last_Time__c</fullName>
    <label>Responded Last Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Whatsapp_Message__c/fields/Response_Msg__c.field-meta.xml
<CustomField>
    <fullName>Response_Msg__c</fullName>
    <label>Response Msg</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Whatsapp_Message__c/fields/Sent__c.field-meta.xml
<CustomField>
    <fullName>Sent__c</fullName>
    <label>Sent</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/WhatsappQuoteAPI.cls
@RestResource(urlMapping='/WhatsappQuoteAPI/*')
global class WhatsappQuoteAPI{
    @HTTPPost
    global static void leadPush() {
        ResponseWrapper wrapper = new ResponseWrapper();
        try {
            RestRequest req = RestContext.request;
            system.debug('******req *******  '+req);
            String input = req.requestBody.toString();
            system.debug('******input *******  '+input );
            Map<String,Object> json_input = (Map<String,Object>)JSON.deserializeUntyped(input);
            system.debug('******json_input*******  '+json_input);
           
            Id oppId = (Id)json_input.get('oppId');
            String o = 'select id, name, DescriptionCopy__c from Opportunity where id =:oppId';
            Opportunity myOpp = Database.query(o);
            system.debug('******myOpp *******  '+myOpp );
            String nowTime = System.Now().format('dd/MM/yyyy\' \'HH:mm');           
             
            String respMsg = (String)json_input.get('response_msg');
            String respName;
            if(respMsg == 'Count' )
            respName = 'WA - Quote';
            
            List<Whatsapp_Message__c> whats = new List<Whatsapp_Message__c>();
            whats = [select id, name, Quote_Link_Click__c,Call_Back_Request__c,Quote_WA_Message__c, Delivered__c, Read__c, Responded__c, Responded_First_Time__c, Responded_Last_Time__c, Response_Msg__c, Sent__c from Whatsapp_Message__c where Opportunity__c =: oppId and name = :respName  order by createdDate desc limit 1];
            system.debug('******whats*******  '+whats);   
            
           /*if(respMsg == 'quote'){                    
                if(whats[0] != null) {
                    if((String)json_input.get('within_business_hours') == 'false')
                    whats[0].Call_Back_Request__c = 'Outside Business Hours';
                    else if((String)json_input.get('within_business_hours') == 'true')
                    whats[0].Call_Back_Request__c = 'Inside Business Hours';      
                    whats[0].Responded__c = 'Yes';
                    whats[0].Response_Msg__c = respMsg;
                    if(whats[0].Responded_First_Time__c == null)
                    whats[0].Responded_First_Time__c = System.now();
                    whats[0].Responded_Last_Time__c = System.now();    
                    update whats[0];         
                }
            }*/

            if(respMsg == 'Count'){  
                if(whats[0] != null) {
                    if(whats[0].Quote_Link_Click__c == null){ 
                        whats[0].Quote_Link_Click__c = 1;
                    }    
                    else{
                        whats[0].Quote_Link_Click__c++;   
                    }
                    if(whats[0].Quote_WA_Message__c == null) {
                        whats[0].Quote_WA_Message__c = nowTime;
                    }
                    else{
                        whats[0].Quote_WA_Message__c = nowTime+'\n'+whats[0].Quote_WA_Message__c; 
                    }                  
                    update whats[0];
                }
            }
            
            wrapper.status_code = '201';
            wrapper.message = 'Success';
        }
         catch(Exception e) {
            
            wrapper.status_code = '501';
            wrapper.message = 'Failure';
        }
        
        String json = json.serialize(wrapper);
        RestContext.response.addHeader('Content-Type','application/json');
        RestContext.response.responseBody = Blob.valueOf(json);
    }
    
     global class ResponseWrapper {
        String status_code;
        String message;
    }
}