force-app/main/default/objects/Interior_Designer__c/Interior_Designer__c.object-meta.xml
<CustomObject>
    <label>Interior Designer</label>
    <nameField>
        <label>Design Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interior Designers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Interior_Designer__c/fields/Available_at_Showroom__c.field-meta.xml
<CustomField>
    <fullName>Available_at_Showroom__c</fullName>
    <label>Available at Showroom</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Kanakapura Showroom</fullName>
            </value>
            <value>
                <fullName>Gopalan Showroom</fullName>
            </value>
            <value>
                <fullName>Pushparang Showroom</fullName>
            </value>
            <value>
                <fullName>Durga Petals Showroom</fullName>
            </value>
            <value>
                <fullName>Test Showroom 2</fullName>
            </value>
            <value>
                <fullName>Sanghvi Valley</fullName>
            </value>
            <value>
                <fullName>Noida Showroom</fullName>
            </value>
            <value>
                <fullName>Gurgaon Showroom</fullName>
            </value>
            <value>
                <fullName>Kodambakkam Showroom</fullName>
            </value>
            <value>
                <fullName>Gachibowli Showroom</fullName>
            </value>
            <value>
                <fullName>Kandivali Showroom</fullName>
            </value>
            <value>
                <fullName>Yelahanka Showroom</fullName>
            </value>
            <value>
                <fullName>HSR Showroom</fullName>
            </value>
            <value>
                <fullName>Thane Showroom</fullName>
            </value>
            <value>
                <fullName>Test Showroom</fullName>
            </value>
            <value>
                <fullName>Gulbarga</fullName>
            </value>
            <value>
                <fullName>Hebbal Showroom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interior_Designer__c/fields/N_10_to_N_4_Total_Opportunities__c.field-meta.xml
<CustomField>
    <fullName>N_10_to_N_4_Total_Opportunities__c</fullName>
    <label>N-10 to N-4 Total Opportunities</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Interior_Designer__c/fields/N_10_to_N_4_Total_Won_Opportunities__c.field-meta.xml
<CustomField>
    <fullName>N_10_to_N_4_Total_Won_Opportunities__c</fullName>
    <label>N-10 to N-4 Total Won Opportunities</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Interior_Designer__c/fields/N_9_to_N_3_Total_Opportunities__c.field-meta.xml
<CustomField>
    <fullName>N_9_to_N_3_Total_Opportunities__c</fullName>
    <label>N-9 to N-3 Total Opportunities</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Master__c/Master__c.object-meta.xml
<CustomObject>
    <description>This is master object.</description>
    <label>Master</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master__c/fields/Avg_Conversion__c.field-meta.xml
<CustomField>
    <fullName>Avg_Conversion__c</fullName>
    <label>Avg Conversion %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Master__c/fields/Avg_Opportunites_Month__c.field-meta.xml
<CustomField>
    <fullName>Avg_Opportunites_Month__c</fullName>
    <label>Avg Opportunites / Month</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Master__c/fields/N_8_to_N_2_Total_Opportunities__c.field-meta.xml
<CustomField>
    <fullName>N_8_to_N_2_Total_Opportunities__c</fullName>
    <label>N-8 to N-2 Total Opportunities</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Master__c/fields/N_8_to_N_2_Total_Won_Opportunities__c.field-meta.xml
<CustomField>
    <fullName>N_8_to_N_2_Total_Won_Opportunities__c</fullName>
    <label>N-8 to N-2 Total Won Opportunities</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Master__c/fields/N_9_to_N_3_Total_Opportunities__c.field-meta.xml
<CustomField>
    <fullName>N_9_to_N_3_Total_Opportunities__c</fullName>
    <label>N-9 to N-3 Total Opportunitie</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Master__c/fields/N_9_to_N_3_Total_Won_Opportunities__c.field-meta.xml
<CustomField>
    <fullName>N_9_to_N_3_Total_Won_Opportunities__c</fullName>
    <label>N-9 to N-3 Total Won Opportunities</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Master__c/fields/Total_Opportunities__c.field-meta.xml
<CustomField>
    <fullName>Total_Opportunities__c</fullName>
    <label>Total Opportunities</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Master__c/fields/Total_Won_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Total_Won_Opportunity__c</fullName>
    <label>Total Won Opportunity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Master__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Property</fullName>
                <default>true</default>
                <label>Property</label>
            </value>
            <value>
                <fullName>Showroom</fullName>
            </value>
            <value>
                <fullName>Builder</fullName>
            </value>
            <value>
                <fullName>Walk-in Source</fullName>
            </value>
            <value>
                <fullName>Dealer Showroom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DPTypeConversionCalc_Test.cls
@isTest
public class DPTypeConversionCalc_Test {
    public testmethod static void setup() {
        List<Interior_Designer__c> intDesigner = new List<Interior_Designer__c>();
        List<Opportunity> oppList = new List<Opportunity>();
        
        Interior_Designer__c inte = new Interior_Designer__c();
        inte.name = 'test';
        inte.Email__c = 'test@23.com';
        inte.Active__c   = true;
        inte.Available_at_Showroom__c = null;
        insert inte;               
        
        Master__c m = new Master__c();
        m.Name = 'Test howwroomm';
        m.Type__c = 'Showroom';
        m.Avg_Conversion__c = 10;
        m.Total_Opportunities__c = 10;
        m.Total_Won_Opportunity__c = 6;
        m.Avg_Opportunites_Month__c = 20;
        m.N_8_to_N_2_Total_Opportunities__c = 1;
        m.N_8_to_N_2_Total_Won_Opportunities__c = 2;
        m.N_9_to_N_3_Total_Opportunities__c = 3;
        m.N_9_to_N_3_Total_Won_Opportunities__c = 4;
        m.N_10_to_N_4_Total_Opportunities__c = 5;
        m.N_10_to_N_4_Total_Won_Opportunities__c = 6;
        insert m;      
        
        Master__c m1 = new Master__c();
        m1.Name = 'Test wwroomm';
        m1.Type__c = 'Showroom';
        m1.Avg_Conversion__c = 10;
        m1.Total_Opportunities__c = 10;
        m1.Total_Won_Opportunity__c = 6;
        m1.Avg_Opportunites_Month__c = 20;
        m1.N_8_to_N_2_Total_Opportunities__c = 10;
        m1.N_8_to_N_2_Total_Won_Opportunities__c = 20;
        m1.N_9_to_N_3_Total_Opportunities__c = 30;
        m1.N_9_to_N_3_Total_Won_Opportunities__c = 40;
        m1.N_10_to_N_4_Total_Opportunities__c = 50;
        m1.N_10_to_N_4_Total_Won_Opportunities__c = 60;
        insert m1;
        
        Opportunity opp1 = new Opportunity();
        opp1.name = 'first';
        opp1.StageName='Won';
        opp1.Opportunity_Stage__c = 'Won';
        opp1.CloseDate = Date.Today();
        opp1.Interior_Design_Partner__c = inte.id;
        opp1.Amount = 1000;
        opp1.Appointment_Venue_Square__c = m.Id;
        opp1.Time_of_Actual_Appointment_Start__c = date.today().addMonths(-5);
        insert opp1;
     
        Interior_Designer__c inte2 = new Interior_Designer__c();
        inte2.name = 'test1235353';
        inte2.Email__c = 'test@231afa34.com';
        inte2.Active__c   = true;
        insert inte2;      
        
        for(Integer i=0; i<=15;i++) {
            Opportunity opp3 = new Opportunity();
            opp3.name = 'first3[i]';
            opp3.StageName='Won';
            opp3.Opportunity_Stage__c = 'Won';
            opp3.CloseDate = Date.Today();
            opp3.Interior_Design_Partner__c = inte2.id;
            opp3.Amount = 500000;
            opp3.Time_of_Actual_Appointment_Start__c = date.today().addMonths(-5);
            opp3.Appointment_Venue_Square__c = m1.Id;
            oppList.add(opp3);
        }     
        insert oppList;
        
        Test.startTest();
        DPTypeConversionCalc.DPTypeConversion();
        Test.stopTest();
    }
}