force-app/main/default/objects/Interior_Designer__c/Interior_Designer__c.object-meta.xml
<CustomObject>
    <label>Interior Designer</label>
    <nameField>
        <label>Design Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interior Designers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Interior_Designer__c/fields/Available_at_Showroom__c.field-meta.xml
<CustomField>
    <fullName>Available_at_Showroom__c</fullName>
    <label>Available at Showroom</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Kanakapura Showroom</fullName>
            </value>
            <value>
                <fullName>Gopalan Showroom</fullName>
            </value>
            <value>
                <fullName>Pushparang Showroom</fullName>
            </value>
            <value>
                <fullName>Durga Petals Showroom</fullName>
            </value>
            <value>
                <fullName>Test Showroom 2</fullName>
            </value>
            <value>
                <fullName>Sanghvi Valley</fullName>
            </value>
            <value>
                <fullName>Noida Showroom</fullName>
            </value>
            <value>
                <fullName>Gurgaon Showroom</fullName>
            </value>
            <value>
                <fullName>Kodambakkam Showroom</fullName>
            </value>
            <value>
                <fullName>Gachibowli Showroom</fullName>
            </value>
            <value>
                <fullName>Kandivali Showroom</fullName>
            </value>
            <value>
                <fullName>Yelahanka Showroom</fullName>
            </value>
            <value>
                <fullName>HSR Showroom</fullName>
            </value>
            <value>
                <fullName>Thane Showroom</fullName>
            </value>
            <value>
                <fullName>Test Showroom</fullName>
            </value>
            <value>
                <fullName>Gulbarga</fullName>
            </value>
            <value>
                <fullName>Hebbal Showroom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interior_Designer__c/fields/New_joinee__c.field-meta.xml
<CustomField>
    <fullName>New_joinee__c</fullName>
    <defaultValue>false</defaultValue>
    <label>New joinee</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Interior_Designer__c/fields/Property_Exp_Data__c.field-meta.xml
<CustomField>
    <fullName>Property_Exp_Data__c</fullName>
    <label>Property Exp Data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Interior_Designer__c/fields/Total_Wins__c.field-meta.xml
<CustomField>
    <fullName>Total_Wins__c</fullName>
    <label>Total Wins</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Interior_Designer__c/fields/Workload_10_40__c.field-meta.xml
<CustomField>
    <fullName>Workload_10_40__c</fullName>
    <label>10-40 Workload</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DesignPartnerSelectionCntlr_Test.cls
@IsTest(SeeAllData=true)
private class DesignPartnerSelectionCntlr_Test{
    @isTest static void DesignPartnerSelectionCntlrTest() {
        Interior_Designer__c objIDP = new Interior_Designer__c();
        objIDP.Name = 'testData';
        objIDP.Email__c = 'Test1DesighP@hfltest.com';
        objIDP.Available_at_Showroom__c  = 'Test Showroom 2; Kodambakkam Showroom; Gachibowli Showroom; Kandivali Showroom; HSR Showroom; Test Showroom';
        objIDP.Total_Wins__c = 5;
        objIDP.Workload_10_40__c = 22;
        objIDP.Avg_Opportunites_Month__c = 20.02;
        objIDP.Total_Opportunities__c = 50;
        objIDP.New_joinee__c = true;
        objIDP.Property_Exp_Data__c = 'a090I00000odaKL,<@>Test ,Property 3<@>2';
        insert objIDP;
        lead leadRec1=leadUtil_Test.insertLead('tesqWL@hamelane.com','8919449949');
         leadRec1.PostalCode='561284';
         leadRec1.status='Fresh Lead';
         leadRec1.City='Bengaluru';
        leadRec1.LeadSource = 'Website';
         insert leadRec1; 
        ApexPages.currentPage().getParameters().put('id','a092800000TGD0w');
        ApexPages.currentPage().getParameters().put('recordId',leadRec1.Id);
        ApexPages.currentPage().getParameters().put('objectName','Lead');
        ApexPages.currentPage().getParameters().put('name','Test Lead');
        ApexPages.currentPage().getParameters().put('property','a090I00000odaKL');
        Test.StartTest();
        DesignPartnerSelectionCntlr obj = new DesignPartnerSelectionCntlr();
        obj.getDesginPartnerData();
        obj.strSearchDP = 'A';
        //obj.GetSearchData();
        obj.strRecordId =leadRec1.Id;
        obj.strDPId = objIDP.Id;
        obj.updateDesignPartner();
        Test.StopTest();
       
            
         
   }

}