force-app/main/default/objects/Lead_Round_Robin_Assignment__c/Lead_Round_Robin_Assignment__c.object-meta.xml
<CustomObject>
    <label>Iron Man Assignment</label>
    <nameField>
        <label>Lead Round Robin Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Iron Man Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead_Round_Robin_Assignment__c/fields/Assignment_Days__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Days__c</fullName>
    <label>Assignment Days</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
            <value>
                <fullName>Sunday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead_Round_Robin_Assignment__c/fields/Daily_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Daily_Assignment__c</fullName>
    <label>Daily Assignment</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead_Round_Robin_Assignment__c/fields/Daily_Limit__c.field-meta.xml
<CustomField>
    <fullName>Daily_Limit__c</fullName>
    <label>Daily Limit</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead_Round_Robin_Assignment__c/fields/Distance_from_ShowRoom__c.field-meta.xml
<CustomField>
    <fullName>Distance_from_ShowRoom__c</fullName>
    <label>Distance from ShowRoom</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead_Round_Robin_Assignment__c/fields/Monthly_Assignments__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Assignments__c</fullName>
    <label>Monthly Assignments</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead_Round_Robin_Assignment__c/fields/Monthly_Limit__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Limit__c</fullName>
    <label>Monthly Limit</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead_Round_Robin_Assignment__c/fields/Showroom_Name__c.field-meta.xml
<CustomField>
    <fullName>Showroom_Name__c</fullName>
    <label>Showroom Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ScheResetResVisitDaily_Test.cls
@isTest
public class ScheResetResVisitDaily_Test {
    @isTest static void test() {
        Lead_Round_Robin_Assignment__c ObjRoundRobin = new Lead_Round_Robin_Assignment__c();
        ObjRoundRobin.Assignment_Days__c = 'Monday';
        ObjRoundRobin.Daily_Assignment__c= 1;
        ObjRoundRobin.Daily_Limit__c= 10;
        ObjRoundRobin.Monthly_Assignments__c= 100;
        ObjRoundRobin.Monthly_Limit__c= 10;
        ObjRoundRobin.Showroom_Name__c= 'HSR';
        ObjRoundRobin.Distance_from_ShowRoom__c= 10;

        insert ObjRoundRobin;  
        ScheResetResVisitDaily s = new ScheResetResVisitDaily();
        s.execute(null);
    }
}