force-app/main/default/objects/Lead_Round_Robin_Assignment__c/Lead_Round_Robin_Assignment__c.object-meta.xml
<CustomObject>
    <label>Iron Man Assignment</label>
    <nameField>
        <label>Lead Round Robin Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Iron Man Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead_Round_Robin_Assignment__c/fields/Monthly_Assignments__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Assignments__c</fullName>
    <label>Monthly Assignments</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ScheResetResVisitMonthly.cls
global class ScheResetResVisitMonthly implements Schedulable {
    global void execute(SchedulableContext SC) {
         List<Lead_Round_Robin_Assignment__c> lstLeadRound= [select id,Monthly_Assignments__c from Lead_Round_Robin_Assignment__c for Update];
         for(Lead_Round_Robin_Assignment__c objleadRound : lstLeadRound){
             objleadRound.Monthly_Assignments__c= 0;
         }
         if(!lstLeadRound.IsEmpty()){
             update lstLeadRound;  
         }         
    }
}