force-app/main/default/objects/Integration_Setting__c/Integration_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains the End Point and Content-Type</description>
    <label>Integration Setting</label>
</CustomObject>

force-app/main/default/objects/Master__c/Master__c.object-meta.xml
<CustomObject>
    <description>This is master object.</description>
    <label>Master</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If the Showroom is active the isActive then check it else Uncheck</description>
    <label>IsActive ShowRoom</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/Showroom_User__c.object-meta.xml
<CustomObject>
    <label>Showroom User</label>
    <nameField>
        <label>ShowRoom User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Showroom User</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Showroom_User__c/fields/Backlogs__c.field-meta.xml
<CustomField>
    <fullName>Backlogs__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Backlogs</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/Daily_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Daily_Assignment__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Daily Assignment</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/Daily_Assignment_Limit__c.field-meta.xml
<CustomField>
    <fullName>Daily_Assignment_Limit__c</fullName>
    <defaultValue>7</defaultValue>
    <label>Daily Assignment Limit</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/IM_Class__c.field-meta.xml
<CustomField>
    <fullName>IM_Class__c</fullName>
    <defaultValue>&apos;Bronze&apos;</defaultValue>
    <label>IM Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/Monthly_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Assignment__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Monthly Assignment</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/Monthly_Assignment_Limit__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Assignment_Limit__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Monthly Assignment Limit</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/Outskirts_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Outskirts_Assignment__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Outskirts Daily Assignment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/Outskirts_Assignment_Limit__c.field-meta.xml
<CustomField>
    <fullName>Outskirts_Assignment_Limit__c</fullName>
    <label>Outskirts Daily Assignment Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Showroom Manager</fullName>
            </value>
            <value>
                <fullName>Sales Manager</fullName>
            </value>
            <value>
                <fullName>Iron Man</fullName>
            </value>
            <value>
                <fullName>Delivery Manager</fullName>
            </value>
            <value>
                <fullName>Design Manager</fullName>
            </value>
            <value>
                <fullName>Business Development Manager</fullName>
            </value>
            <value>
                <fullName>Pre-Sales Freelancer</fullName>
            </value>
            <value>
                <fullName>Tele Caller Agent</fullName>
            </value>
            <value>
                <fullName>Product Consultant</fullName>
            </value>
            <value>
                <fullName>Doowup Presales</fullName>
            </value>
            <value>
                <fullName>Central Team Agent</fullName>
            </value>
            <value>
                <fullName>Inside Sales Agent</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
            <value>
                <fullName>Desgin Manager</fullName>
                <isActive>false</isActive>
                <label>Desgin Manager</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/Threashold__c.field-meta.xml
<CustomField>
    <fullName>Threashold__c</fullName>
    <defaultValue>18</defaultValue>
    <label>Threashold</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CalloutToExotelQueue_test.cls
@istest
global class CalloutToExotelQueue_test  {
    
     public static  Integration_Setting__c  intSetting ;
    Public static Lead ld;
    public static master__c prop;
    @TestSetup static void data() { 
        intSetting = new Integration_Setting__c();
        intSetting.Name = 'Exotel API';
        intSetting.End_Point__c ='https://88f2905a42807de7499a2e23bae7c99e5745d496f3e76427:72f89a2e7c8d2e1302769ceafb1fb035eed1e6b6ba006592@api.exotel.com/v1/Accounts/homelane4/Calls/connect?' ;   
        insert intsetting ;

        Showroom_User__c objShowroom1= TestData_Factory.createShowroomUser(false);
        objShowroom1.Email__c ='showroomuser@gmail.com';
        objShowroom1.Phone__c = '9911882266';
        objShowroom1.Threashold__c = 10;
        objShowroom1.Backlogs__c = 2;
        objShowroom1.Daily_Assignment__c = 1;
        objShowroom1.Daily_Assignment_Limit__c = 10;
        objShowroom1.IsActive__c = true; 
        objShowroom1.Monthly_Assignment__c = 0;
        objShowroom1.Monthly_Assignment_Limit__c = 100;
        objShowroom1.Role__c ='Iron Man';
        objShowroom1.Outskirts_Assignment__c=1;
        objShowroom1.Outskirts_Assignment_Limit__c=3;
        objShowroom1.IM_Class__c= 'Bronze';
        insert ObjShowroom1;
              
        account acc= new account();
        acc.name='Tetsacc';
        insert acc;
         //Create User record
        
       
        ld = TestData_Factory.CreateFreshLead(false);
        ld.Account__c =acc.id;
        ld.city='Bengaluru';
        ld.Phone='9988772244';
        insert ld;
        
    }
    
    
    
    public testMethod static void testscenario1(){
        
        
        
        test.startTest();
        try
        {
            intsetting = [select id from Integration_Setting__c limit 1 ];
            
            ld=[select id,phone from lead limit 1];                        
            
            List<Id> LeadIds = new List<Id>();
            LeadIds.add(ld.id);
            
            CalloutToExotelQueue.CallExotelAPI(LeadIds);
        }
        catch(exception e)
        {
            system.debug('exception');
        }
        
        test.stoptest();
        
    }
    
}