force-app/main/default/objects/Master__c/Master__c.object-meta.xml
<CustomObject>
    <description>This is master object.</description>
    <label>Master</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HomeLane</fullName>
            </value>
            <value>
                <fullName>Doowup</fullName>
            </value>
            <value>
                <fullName>Wrapzap</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If the Showroom is active the isActive then check it else Uncheck</description>
    <label>IsActive ShowRoom</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Master__c/fields/Luxe_service__c.field-meta.xml
<CustomField>
    <fullName>Luxe_service__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Luxe service</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Master__c/fields/Property_City__c.field-meta.xml
<CustomField>
    <fullName>Property_City__c</fullName>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/Showroom_User__c.object-meta.xml
<CustomObject>
    <label>Showroom User</label>
    <nameField>
        <label>ShowRoom User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Showroom User</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Showroom_User__c/fields/Backlogs__c.field-meta.xml
<CustomField>
    <fullName>Backlogs__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Backlogs</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/Daily_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Daily_Assignment__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Daily Assignment</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/Daily_Assignment_Limit__c.field-meta.xml
<CustomField>
    <fullName>Daily_Assignment_Limit__c</fullName>
    <defaultValue>7</defaultValue>
    <label>Daily Assignment Limit</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/IM_Class__c.field-meta.xml
<CustomField>
    <fullName>IM_Class__c</fullName>
    <defaultValue>&apos;Bronze&apos;</defaultValue>
    <label>IM Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/IronMan__c.field-meta.xml
<CustomField>
    <fullName>IronMan__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IronMan</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/Monthly_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Assignment__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Monthly Assignment</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/Monthly_Assignment_Limit__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Assignment_Limit__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Monthly Assignment Limit</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/Outskirts_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Outskirts_Assignment__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Outskirts Daily Assignment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/Outskirts_Assignment_Limit__c.field-meta.xml
<CustomField>
    <fullName>Outskirts_Assignment_Limit__c</fullName>
    <label>Outskirts Daily Assignment Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Showroom Manager</fullName>
            </value>
            <value>
                <fullName>Sales Manager</fullName>
            </value>
            <value>
                <fullName>Iron Man</fullName>
            </value>
            <value>
                <fullName>Delivery Manager</fullName>
            </value>
            <value>
                <fullName>Design Manager</fullName>
            </value>
            <value>
                <fullName>Business Development Manager</fullName>
            </value>
            <value>
                <fullName>Pre-Sales Freelancer</fullName>
            </value>
            <value>
                <fullName>Tele Caller Agent</fullName>
            </value>
            <value>
                <fullName>Product Consultant</fullName>
            </value>
            <value>
                <fullName>Doowup Presales</fullName>
            </value>
            <value>
                <fullName>Central Team Agent</fullName>
            </value>
            <value>
                <fullName>Inside Sales Agent</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
            <value>
                <fullName>Desgin Manager</fullName>
                <isActive>false</isActive>
                <label>Desgin Manager</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/Showroom_Name__c.field-meta.xml
<CustomField>
    <fullName>Showroom_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Showroom Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Master__c.Type__c</field>
            <operation>equals</operation>
            <value>Showroom</value>
        </filterItems>
        <filterItems>
            <field>Master__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Master__c</referenceTo>
    <relationshipLabel>Showroom User</relationshipLabel>
    <relationshipName>Showroom_User</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/Threashold__c.field-meta.xml
<CustomField>
    <fullName>Threashold__c</fullName>
    <defaultValue>18</defaultValue>
    <label>Threashold</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territory__c/Territory__c.object-meta.xml
<CustomObject>
    <label>Territory</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory__c/fields/Assignment__c.field-meta.xml
<CustomField>
    <fullName>Assignment__c</fullName>
    <formula>IF( ISPICKVAL(City__c, &apos;Outskirts&apos;), Ironman__r.Outskirts_Assignment__c , Ironman__r.Daily_Assignment__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Assignment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territory__c/fields/Cluster__c.field-meta.xml
<CustomField>
    <fullName>Cluster__c</fullName>
    <label>Cluster</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BLR_GOP_1</fullName>
            </value>
            <value>
                <fullName>Test1</fullName>
            </value>
            <value>
                <fullName>Test2</fullName>
            </value>
            <value>
                <fullName>BLR_KAN_6</fullName>
            </value>
            <value>
                <fullName>BLR_HEB_5</fullName>
            </value>
            <value>
                <fullName>BLR_MUS_4</fullName>
            </value>
            <value>
                <fullName>BLR_WHI_3</fullName>
            </value>
            <value>
                <fullName>BLR_HSR_2</fullName>
            </value>
            <value>
                <fullName>CBE_ PLZ_1</fullName>
            </value>
            <value>
                <fullName>HYD_SHG_1</fullName>
            </value>
            <value>
                <fullName>MUM_THN_2</fullName>
            </value>
            <value>
                <fullName>HYD_BAN_2</fullName>
            </value>
            <value>
                <fullName>KOL_MAN_1</fullName>
            </value>
            <value>
                <fullName>CHE_CTY_2</fullName>
            </value>
            <value>
                <fullName>CHE_ OMR_1</fullName>
            </value>
            <value>
                <fullName>NCR_NOI_3</fullName>
            </value>
            <value>
                <fullName>NCR_GUR_1</fullName>
            </value>
            <value>
                <fullName>NCR_KRN_2</fullName>
            </value>
            <value>
                <fullName>PUN_BAN_1</fullName>
            </value>
            <value>
                <fullName>MUM_GOR_1</fullName>
            </value>
            <value>
                <fullName>BLR_BSR_7</fullName>
            </value>
            <value>
                <fullName>VIZ_SQRLT_1</fullName>
            </value>
            <value>
                <fullName>MYS_SQRLT_1</fullName>
            </value>
            <value>
                <fullName>KOL_CHI_2</fullName>
            </value>
            <value>
                <fullName>LKO_SQRLT_1</fullName>
            </value>
            <value>
                <fullName>PUN_VIM_2</fullName>
            </value>
            <value>
                <fullName>BAN_JPN_6</fullName>
            </value>
            <value>
                <fullName>SRT_SQRLT_1</fullName>
            </value>
            <value>
                <fullName>CHE_SQRLT_1</fullName>
            </value>
            <value>
                <fullName>CHE_ GST_3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Territory__c/fields/Cluster_Brand__c.field-meta.xml
<CustomField>
    <fullName>Cluster_Brand__c</fullName>
    <label>Cluster Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Homelane</fullName>
                <default>true</default>
                <label>Homelane</label>
            </value>
            <value>
                <fullName>Doow up</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Territory__c/fields/Ironman__c.field-meta.xml
<CustomField>
    <fullName>Ironman__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Ironman</label>
    <referenceTo>Showroom_User__c</referenceTo>
    <relationshipLabel>Territories</relationshipLabel>
    <relationshipName>Territories</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Territory__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <description>IF(OR(Ironman__r.Backlogs_Inactivity__c =True, Ironman__r.IsActive__c =False,Ironman__r.Reached_Daily_Limit__c = True,Ironman__r.Reached_Monthly_Limit__c = True),false,true)</description>
    <formula>IF ( ISPICKVAL(City__c, &apos;Outskirts&apos;),
IF(OR(Ironman__r.IsActive__c =False, Ironman__r.Reached_Outskirts_Monthly_Limit__c=true, Ironman__r.Reached_Outskirts_Limit__c =True ),false,true),

IF(OR(Ironman__r.Backlogs_Inactivity__c =True, Ironman__r.IsActive__c =False,Ironman__r.Reached_Daily_Limit__c = True,Ironman__r.Reached_Monthly_Limit__c = True),false,true))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Territory__c/fields/Monthly_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Assignment__c</fullName>
    <formula>If( ISPICKVAL( City__c , &apos;Outskirts&apos;), Ironman__r.Outskirts_Monthly_Assignment__c , Ironman__r.Monthly_Assignment__c  )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Monthly Assignment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territory__c/fields/Sales_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Sales_Campaign__c</fullName>
    <label>Sales Campaign</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Green Channel</fullName>
            </value>
            <value>
                <fullName>Inside Sales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LuxeLeadAssignmentHandler_Test.cls
@isTest
public class LuxeLeadAssignmentHandler_Test {
 
     public static lead objLead ;
    public static Showroom_User__c objShowroom;
    public static Territory__c objTerr;
    public static master__c showroom;
  public static testMethod void DirectAssignment(){
        test.startTest();
        Showroom_User__c objShowroom1= TestData_Factory.createShowroomUser(false);
        objShowroom1.Threashold__c = 10;
        objShowroom1.Backlogs__c = 2;
        objShowroom1.Daily_Assignment__c = 1;
        objShowroom1.Daily_Assignment_Limit__c = 10;
        objShowroom1.IsActive__c = true; 
        objShowroom1.Monthly_Assignment__c = 0;
        objShowroom1.Monthly_Assignment_Limit__c = 100;
        objShowroom1.Role__c ='Iron Man';
        objShowroom1.Outskirts_Assignment__c=1;
        //
        objShowroom1.Outskirts_Assignment_Limit__c=3;
        objShowroom1.IM_Class__c= 'Silver';
        
        insert ObjShowroom1;
        
        Showroom_User__c objShowroom2= TestData_Factory.createShowroomUser(false);
        objShowroom2.Email__c = 'TestSHowRoomasdUSer@test.com';
        objShowroom2.Threashold__c = 10;
        objShowroom2.Backlogs__c = 2;
        objShowroom2.Daily_Assignment__c = 4;
        objShowroom2.Daily_Assignment_Limit__c = 10;
        objShowroom2.IsActive__c = true;
        objShowroom2.Monthly_Assignment__c = 0;
        objShowroom2.Monthly_Assignment_Limit__c = 100;
        objShowroom2.Outskirts_Assignment__c=1;
        
        objShowroom2.Outskirts_Assignment_Limit__c=3;
        ObjShowroom2.IM_Class__c='Gold';
        
        insert objShowroom2;
        
        
        
        
        Territory__c objTerr = TestData_Factory.createTerritory('Area a',ObjShowroom1.id,'Bengaluru','Cluster A','123456',False);
        objTerr.Lat_Long__Latitude__s = 20.0936477440000;
        objTerr.Lat_Long__Longitude__s =  89.7849897840000;
        objTerr.Cluster_Brand__c ='Homelane';
        
        Insert objTerr ;
        
        Territory__c objTerr1 = TestData_Factory.createTerritory('Area b',ObjShowroom2.id,'Bengaluru','Cluster A','123457',False);
        objTerr1.Lat_Long__Latitude__s = 25.0936477440000;
        objTerr1.Lat_Long__Longitude__s =  88.7849897840000;
        objTerr1.Cluster_Brand__c ='Homelane';
        //objTerr1.Sales_Campaign__c ='Green Channel';
        Insert objTerr1;            
        
        Account ac = new account();
        ac.Name='testacc';
        insert ac;
        lead objLead = new Lead();
        objlead = TestData_Factory.CreateFreshLead(false);
        objlead.Postalcode = '123457';
        objLead.Brand__c ='Homelane';
        objLead.City='Bengaluru';
        objLead.IM_Assignment_Stage__c ='Lead Creation';
        objLead.Account__c= ac.id;
        objLead.Sign_Up_Source__c ='HomeLaneLuxeLeadForm';
        Insert objlead;
        list<Lead> lstLead = [Select Id,email,LastName,LeadSource,Postalcode,city,Assigned_To_Resi_ASM__c,Should_run_Ironman_assignment__c,phone,Squad_IQ_Status__c,Status,Sub_Status__c,Bulk_Upload__C,Brand__c From Lead];
        Set<String>  setString= new set<String>();
        setString.add(lstLead[0].Postalcode);
        
        LuxeLeadAssignmentHandler.getLuxeShowroomUserDetails(lstLead,setString);
        list<Territory__c > lst = [Select id,Name,Cluster__C,Assignment__c,Lat_Long__Latitude__s,Lat_Long__Longitude__s,IronMan__c,Is_Active__c,Cluster_Brand__c 
                                   from Territory__c];
        System.debug('+++++++lst ++++'+lst );
      test.stopTest();
        
    }
    public static testMethod void DirectAssignment2(){
        
        
         test.startTest();
        Showroom_User__c objShowroom1= TestData_Factory.createShowroomUser(false);
        objShowroom1.Threashold__c = 10;
        objShowroom1.Backlogs__c = 2;
        objShowroom1.Daily_Assignment__c = 10;
        objShowroom1.Daily_Assignment_Limit__c = 10;
        objShowroom1.IsActive__c = true; 
        objShowroom1.Monthly_Assignment__c = 0;
        objShowroom1.Monthly_Assignment_Limit__c = 100;
        objShowroom1.Role__c ='Iron Man';
        objShowroom1.Outskirts_Assignment__c=1;
        //
        objShowroom1.Outskirts_Assignment_Limit__c=3;
        objShowroom1.IM_Class__c= 'Silver';
        
        insert ObjShowroom1;
        
         Showroom =TestData_Factory.CreateShowRoom(false);
        Showroom.Luxe_service__c =True;
        showroom.Property_City__c ='Bengaluru';
        insert showroom;
        
        Showroom_User__c objShowroom2= TestData_Factory.createShowroomUser(false);
        objShowroom2.Email__c = 'TestSHowRoomasdUSer@test.com';
        objShowroom2.Threashold__c = 10;
        objShowroom2.Backlogs__c = 2;
        objShowroom2.Daily_Assignment__c = 4;
        objShowroom2.Daily_Assignment_Limit__c = 10;
        objShowroom2.IsActive__c = true;
        objShowroom2.Monthly_Assignment__c = 0;
        objShowroom2.Monthly_Assignment_Limit__c = 100;
        objShowroom2.Outskirts_Assignment__c=1;
        objShowroom2.Role__c='Iron Man';
        objShowroom2.Outskirts_Assignment_Limit__c=3;
        ObjShowroom2.IM_Class__c='Gold';
        ObjShowroom2.Showroom_Name__c =showroom.id;
        
        insert objShowroom2;
        
       
        Territory__c objTerr = TestData_Factory.createTerritory('Area a',ObjShowroom1.id,'Bengaluru','Cluster A','123456',False);
        objTerr.Lat_Long__Latitude__s = 20.0936477440000;
        objTerr.Lat_Long__Longitude__s =  89.7849897840000;
        objTerr.Cluster_Brand__c ='Homelane';
        
        Insert objTerr ;
        Account acc= new account();
        acc.name='luxe acc';
        insert acc;
        Lead ld= new Lead();
        ld.leadSource ='HomeLaneLuxeLeadForm';
        ld.postalcode='123456';
        ld.LastName='luxe';
        ld.City='Bengaluru';
        ld.Phone ='9790789089';
        ld.Email ='luse@gmail.com';
        ld.Account__c =acc.id;
        insert ld;
         test.stopTest();
    }
}