force-app/main/default/objects/Master__c/Master__c.object-meta.xml
<CustomObject>
    <description>This is master object.</description>
    <label>Master</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master__c/fields/Builder_Name__c.field-meta.xml
<CustomField>
    <fullName>Builder_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Self Lookup On Master</description>
    <label>Builder Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Master__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Builder</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Master__c</referenceTo>
    <relationshipLabel>Master</relationshipLabel>
    <relationshipName>Master</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master__c/fields/Property_City__c.field-meta.xml
<CustomField>
    <fullName>Property_City__c</fullName>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Property</fullName>
                <default>true</default>
                <label>Property</label>
            </value>
            <value>
                <fullName>Showroom</fullName>
            </value>
            <value>
                <fullName>Builder</fullName>
            </value>
            <value>
                <fullName>Walk-in Source</fullName>
            </value>
            <value>
                <fullName>Dealer Showroom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master__c/recordTypes/Builder.recordType-meta.xml
<RecordType>
    <fullName>Builder</fullName>
    <active>true</active>
    <label>Builder</label>
</RecordType>

force-app/main/default/objects/Master__c/recordTypes/Property.recordType-meta.xml
<RecordType>
    <fullName>Property</fullName>
    <active>true</active>
    <label>Property</label>
</RecordType>

force-app/main/default/classes/Getbuilderdata.cls
/**
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* Author: Aditya Saini
* Created Date : 8th May 2017
* Description : This class will generate json file that will contain builder name and ID 
*               Through API - /services/apexrest/Getbuilderdata.
* ─────────────────────────────────────────────────────────────────────────────────────────────────
**/

@RestResource(urlMapping='/Getbuilderdata/*')
global with sharing class Getbuilderdata{
@HttpGet
  global static list<FinalWrapper>  getbuilderrec() {
        List<FinalWrapper> finalList = new List<FinalWrapper>();
        //String Oppemail = RestContext.request.params.get('Oppemail');
        //system.debug('testrun');
        //system.debug('------------------>Oppemail'+Oppemail); 
        String type = 'Property'; 
        List<Master__c > buildrlist = new List<Master__c >();        
        String query = 'select id,Name,Type__c,Property_City__c,Builder_Name__c,Builder_Name__r.name from Master__c where Type__c = \''+type+'\'';        
        buildrlist = Database.query(query);
        system.debug('buildrlist ---------------------->'+buildrlist );
        system.debug('buildrlist.size()---------------------->'+buildrlist.size());
        List<Master__c> listbuild = (List<Master__c>)(buildrlist);
        for(Master__c ld : listbuild ){FinalWrapper fin = new FinalWrapper();fin.ProjectID= ld.Id;fin.Projectcity = ld.Property_City__c;fin.BuilderID = ld.Builder_Name__c;fin.BuilderName = ld.Builder_Name__r.name;fin.ProjectName= ld.Name;finalList.add(fin);}
        return finalList;
     }
     global class FinalWrapper{ 
         public String ProjectID{get;set;}public String ProjectName{get;set;}public String Projectcity{get;set;}public String BuilderID{get;set;}public String BuilderName{get;set;}
     }
}