force-app/main/default/objects/Master__c/Master__c.object-meta.xml
<CustomObject>
    <description>This is master object.</description>
    <label>Master</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master__c/fields/Unique_Name__c.field-meta.xml
<CustomField>
    <fullName>Unique_Name__c</fullName>
    <description>Name After removing the special Character</description>
    <label>Unique Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PropertyMatchString__c/PropertyMatchString__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Strings to remove from Property Tiger</description>
    <label>PropertyMatchString</label>
</CustomObject>

force-app/main/default/objects/RedundantPropertyString__mdt/RedundantPropertyString__mdt.object-meta.xml
<CustomObject>
    <label>RedundantPropertyString</label>
    <pluralLabel>RedundantPropertyString</pluralLabel>
</CustomObject>

force-app/main/default/objects/RedundantPropertyString__mdt/fields/IsPreposition__c.field-meta.xml
<CustomField>
    <fullName>IsPreposition__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsPreposition</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RedundantPropertyString__mdt/fields/RedundantString__c.field-meta.xml
<CustomField>
    <fullName>RedundantString__c</fullName>
    <label>RedundantString</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/updateMasterBatch.cls
global class updateMasterBatch implements Database.Batchable<sObject> {
    
    Set<Id> setMasterId = new Set<Id>();
    public updateMasterBatch(Set<Id> setID){
        this.setMasterId = setID; 
    }
    
    global database.QueryLocator start(Database.BatchableContext bc)
    {
        String sQuery = 'Select name,Unique_Name__c from master__C where id IN : setMasterId' ;
                        system.debug('sQuery'+sQuery);
        return database.getQueryLocator(sQuery);
    }
     
    global void execute(Database.BatchableContext bc,List<master__C> scope)
    {
        try{
            String newString;
            String Name;
            list<Master__c> lstmaster = new List<Master__c>();



            list<RedundantPropertyString__mdt>  lstRedundantString = [Select Label,Priority__c,RedundantString__c,IsPreposition__c from RedundantPropertyString__mdt
                                                                        order by Priority__c ASC];
                                                                        
                                                                        
            for(Master__c m:scope){
               
                Name = m.name;
                //Add Space at begining and Ending of the word
                Name = ' '+Name.toLowerCase()+' ';
                System.debug('+++Name lower++'+Name);
                //replace Double space with single space  
                Name = Name.replace('  ',' ');

                //Remove the Number 
                Name = Name.replaceAll('[0-9]', '');

                // Remove Special Character  
                Name = Name.replaceAll('[^a-zA-Z\\s+]', '');

                System.debug('+++PropertyMatchString__c ++'+lstRedundantString);
                for(RedundantPropertyString__mdt strRemove:lstRedundantString){
                   
                        newString =' '+strRemove.RedundantString__c.toLowerCase()+' ';
                        Name = Name.replace(newString,' '); 
                  
                }

                //Replace Double space with single space  
                Name = Name.replace('  ',' ');


                //Remove white Space from begining and End
                Name = Name.trim();

                m.Unique_Name__c = Name.replaceAll( '\\s+', '');
                lstmaster.add(m);

            }
                    if(lstmaster!=NULL && !lstmaster.isempty())
                    {
                        update lstmaster;
                    }
                    
            }
        catch(Exception e){
             Logger.log('Exception','updateMasterBatch ','execute',e.getMessage(),e.getStackTraceString(),NULL);
        }    
    }
    
    global void finish(Database.BatchableContext bc)
    {
    }


}