force-app/main/default/objects/Master__c/Master__c.object-meta.xml
<CustomObject>
    <description>This is master object.</description>
    <label>Master</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Property</fullName>
                <default>true</default>
                <label>Property</label>
            </value>
            <value>
                <fullName>Showroom</fullName>
            </value>
            <value>
                <fullName>Builder</fullName>
            </value>
            <value>
                <fullName>Walk-in Source</fullName>
            </value>
            <value>
                <fullName>Dealer Showroom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CallSMSAPIController_test.cls
@isTest
global class CallSMSAPIController_test implements HttpCalloutMock{

    global HTTPResponse respond(HTTPRequest request) {
        // Create a fake response
        HttpResponse response = new HttpResponse();
        response.setHeader('Content-Type', 'application/json');
        response.setBody('{"response":"success","tiny_url":"tinyurl.com/y45cog","status":1}');
        response.setStatusCode(200);
        return response; 
    }
    @isTest static void CallSMS() {
        Master__c m = new Master__c();
        m.Type__c = 'Showroom';
        m.Name = 'Testing the Shwoeroom';
        insert m;
        
         Lead l = new Lead(
           FirstName='Vaniya',
            LastName='Sowmyala',
            Email='testWLffdfd@hamelane.com',
            Phone='6530007890',
            City='Noida',
            Status='Fresh Lead',
             Sub_Status__c ='Follow Up Later',
             Appointment_Venue_Square__c = m.Id,
             LeadSource='Website'
             ); 

        insert l; 
        System.debug('Lead is : '+l);  
     //  CallSMSAPIController.dummyTestCover();
        Test.setMock(HttpCalloutMock.class, new CallSMSAPIController_test ()); 
      //  HttpResponse response = response;
      //  String contentType = response.getHeader('Content-Type');
      //  String actualValue = response.getBody();
      //  return response; 
              
    } 
}