force-app/main/default/objects/Lead_and_IM_class_Mapping__mdt/Lead_and_IM_class_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Lead and IM class Mapping</label>
    <pluralLabel>Lead and IM class Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Lead_and_IM_class_Mapping__mdt/fields/IM_Class__c.field-meta.xml
<CustomField>
    <fullName>IM_Class__c</fullName>
    <label>IM Class</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_and_IM_class_Mapping__mdt/fields/Lead_Green_class__c.field-meta.xml
<CustomField>
    <fullName>Lead_Green_class__c</fullName>
    <label>Lead Green class</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Class_Scoring__c/Lead_Class_Scoring__c.object-meta.xml
<CustomObject>
    <label>Lead and IM Class mapping</label>
    <nameField>
        <displayFormat>LM - {0000000}</displayFormat>
        <label>Lead  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead and IM Class mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead_Class_Scoring__c/fields/Lead_Source_List__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source_List__c</fullName>
    <label>Lead Source List</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Walk-In</fullName>
            </value>
            <value>
                <fullName>bing</fullName>
            </value>
            <value>
                <fullName>sfleadgen</fullName>
            </value>
            <value>
                <fullName>Toll-free</fullName>
            </value>
            <value>
                <fullName>local</fullName>
            </value>
            <value>
                <fullName>Facebook Ad</fullName>
            </value>
            <value>
                <fullName>google seo</fullName>
            </value>
            <value>
                <fullName>Paid Search</fullName>
            </value>
            <value>
                <fullName>instagram</fullName>
            </value>
            <value>
                <fullName>HomeBliss</fullName>
            </value>
            <value>
                <fullName>yahoo seo</fullName>
            </value>
            <value>
                <fullName>SEO</fullName>
            </value>
            <value>
                <fullName>bing seo</fullName>
            </value>
            <value>
                <fullName>an</fullName>
            </value>
            <value>
                <fullName>ig</fullName>
            </value>
            <value>
                <fullName>Customer experience</fullName>
            </value>
            <value>
                <fullName>taboola</fullName>
            </value>
            <value>
                <fullName>HomeBliss_FB</fullName>
            </value>
            <value>
                <fullName>Quikr</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>FB Lead Form</fullName>
            </value>
            <value>
                <fullName>LinkedIn Lead Form</fullName>
            </value>
            <value>
                <fullName>LinkedIn</fullName>
            </value>
            <value>
                <fullName>Offline Ads</fullName>
            </value>
            <value>
                <fullName>Showroom Order</fullName>
            </value>
            <value>
                <fullName>Affiliates</fullName>
            </value>
            <value>
                <fullName>Blog</fullName>
            </value>
            <value>
                <fullName>Facebook Post</fullName>
            </value>
            <value>
                <fullName>HomeBliss_PaidSearch</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Showroom_User__c/Showroom_User__c.object-meta.xml
<CustomObject>
    <label>Showroom User</label>
    <nameField>
        <label>ShowRoom User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Showroom User</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Showroom_User__c/fields/Daily_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Daily_Assignment__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Daily Assignment</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/Daily_Assignment_Limit__c.field-meta.xml
<CustomField>
    <fullName>Daily_Assignment_Limit__c</fullName>
    <defaultValue>7</defaultValue>
    <label>Daily Assignment Limit</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/IM_Class__c.field-meta.xml
<CustomField>
    <fullName>IM_Class__c</fullName>
    <defaultValue>&apos;Bronze&apos;</defaultValue>
    <label>IM Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/Monthly_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Assignment__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Monthly Assignment</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/Monthly_Assignment_Limit__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Assignment_Limit__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Monthly Assignment Limit</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/Outskirts_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Outskirts_Assignment__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Outskirts Daily Assignment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/Outskirts_Assignment_Limit__c.field-meta.xml
<CustomField>
    <fullName>Outskirts_Assignment_Limit__c</fullName>
    <label>Outskirts Daily Assignment Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Showroom Manager</fullName>
            </value>
            <value>
                <fullName>Sales Manager</fullName>
            </value>
            <value>
                <fullName>Iron Man</fullName>
            </value>
            <value>
                <fullName>Delivery Manager</fullName>
            </value>
            <value>
                <fullName>Design Manager</fullName>
            </value>
            <value>
                <fullName>Business Development Manager</fullName>
            </value>
            <value>
                <fullName>Pre-Sales Freelancer</fullName>
            </value>
            <value>
                <fullName>Tele Caller Agent</fullName>
            </value>
            <value>
                <fullName>Product Consultant</fullName>
            </value>
            <value>
                <fullName>Doowup Presales</fullName>
            </value>
            <value>
                <fullName>Central Team Agent</fullName>
            </value>
            <value>
                <fullName>Inside Sales Agent</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
            <value>
                <fullName>Desgin Manager</fullName>
                <isActive>false</isActive>
                <label>Desgin Manager</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Territory__c/Territory__c.object-meta.xml
<CustomObject>
    <label>Territory</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory__c/fields/Cluster_Brand__c.field-meta.xml
<CustomField>
    <fullName>Cluster_Brand__c</fullName>
    <label>Cluster Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Homelane</fullName>
                <default>true</default>
                <label>Homelane</label>
            </value>
            <value>
                <fullName>Doow up</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Territory__c/fields/Monthly_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Assignment__c</fullName>
    <formula>If( ISPICKVAL( City__c , &apos;Outskirts&apos;), Ironman__r.Outskirts_Monthly_Assignment__c , Ironman__r.Monthly_Assignment__c  )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Monthly Assignment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territory__c/fields/Sales_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Sales_Campaign__c</fullName>
    <label>Sales Campaign</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Green Channel</fullName>
            </value>
            <value>
                <fullName>Inside Sales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/IronmanDigitTalLeadAssignment_Test.cls
@isTest
public class IronmanDigitTalLeadAssignment_Test {
    
    public static lead objLead ;
    public static Showroom_User__c objShowroom;
    public static Territory__c objTerr;
    public static Lead_and_IM_class_Mapping__mdt leadIMMap;
  @isTest
  static void testGetIMShowroomUser() {
    // Create a test lead and set its Green_Lead_Class__c to 'Green Lead Gold'
    Showroom_User__c objShowroom1= TestData_Factory.createShowroomUser(false);
      
        objShowroom1.Daily_Assignment__c = 1;
        objShowroom1.Daily_Assignment_Limit__c = 10;
        objShowroom1.IsActive__c = true; 
        objShowroom1.Monthly_Assignment__c = 0;
        objShowroom1.Monthly_Assignment_Limit__c = 100;
        objShowroom1.Role__c ='Iron Man';
        objShowroom1.Outskirts_Assignment__c=1;
        objShowroom1.Outskirts_Assignment_Limit__c=3;
        objShowroom1.IM_Class__c= 'Gold';
        
        insert ObjShowroom1;
     
         objTerr = TestData_Factory.createTerritory('Area a',ObjShowroom1.id,'Bengaluru','Cluster A','123456',False);
        objTerr.Lat_Long__Latitude__s = 20.0936477440000;
        objTerr.Lat_Long__Longitude__s =  89.7849897840000;
        objTerr.Cluster_Brand__c ='Homelane';
        objTerr.Sales_Campaign__c ='Green Channel';
        
        
        Insert objTerr ;  
      
      
      Account ac = new account();
        ac.Name='testacc';
      insert ac;
      objLead = new Lead();
      objlead = TestData_Factory.CreateFreshLead(false);
      objlead.Postalcode = '123457';
      objLead.Brand__c ='Homelane';
      objLead.City='Bengaluru';
      objLead.IM_Assignment_Stage__c ='Lead Creation';
      objLead.Account__c= ac.id;
      objLead.leadSource ='Walk-In';
      
      Insert objlead;

  } // Create a test Showroom_User__c record
    
      public static testMethod void greenLeadAssign1(){
          Test.startTest();
          
           Showroom_User__c objShowroom1= TestData_Factory.createShowroomUser(false);
      
        objShowroom1.Daily_Assignment__c = 1;
        objShowroom1.Daily_Assignment_Limit__c = 10;
        objShowroom1.IsActive__c = true; 
        objShowroom1.Monthly_Assignment__c = 0;
        objShowroom1.Monthly_Assignment_Limit__c = 100;
        objShowroom1.Role__c ='Iron Man';
        objShowroom1.Outskirts_Assignment__c=1;
        objShowroom1.Outskirts_Assignment_Limit__c=3;
        objShowroom1.IM_Class__c= 'Gold';
        
        insert ObjShowroom1;
          
          objTerr = TestData_Factory.createTerritory('Area a',ObjShowroom1.id,'Bengaluru','Cluster A','123456',False);
          objTerr.Lat_Long__Latitude__s = 20.0936477440000;
          objTerr.Lat_Long__Longitude__s =  89.7849897840000;
          objTerr.Cluster_Brand__c ='Homelane';
          objTerr.Sales_Campaign__c ='Green Channel';
          
          
          Insert objTerr ;  
          Id leadSourceScoreRTID = Schema.SObjectType.Lead_Class_Scoring__c.getRecordTypeInfosByName().get('Gold Plus Score Leads').getRecordTypeId();
          Id leadSignUpSourceScoreRTID = Schema.SObjectType.Lead_Class_Scoring__c.getRecordTypeInfosByName().get('Gold Score Leads').getRecordTypeId();
          Id leadPostalCodeScoreRTID = Schema.SObjectType.Lead_Class_Scoring__c.getRecordTypeInfosByName().get('Silver Score Leads').getRecordTypeId();
          Lead_Class_Scoring__c lcs1 = new Lead_Class_Scoring__c();
        lcs1.Lead_Source_List__c ='Walk-In';
        lcs1.RecordTypeId=leadSourceScoreRTID;
        insert lcs1;
          objTerr  = [select id from Territory__c limit 1];
          objShowroom =[select id from Showroom_User__c limit 1];
          
          leadIMMap = new Lead_and_IM_class_Mapping__mdt();
          leadIMMap.IM_Class__c ='Gold';
          LeadImMap.Lead_Green_class__c ='Gold+';
          //insert leadImMap;
          // List<Lead_and_IM_class_Mapping__mdt> mappingList = [SELECT IM_Class__c, Lead_Green_class__c FROM Lead_and_IM_class_Mapping__mdt];
          
          
          Account ac = new account();
          ac.Name='testacc';
          insert ac;
          objLead = new Lead();
          objlead = TestData_Factory.CreateFreshLead(false);
          objlead.Postalcode = '123457';
          objLead.Brand__c ='Homelane';
          objLead.City='Bengaluru';
          objLead.IM_Assignment_Stage__c ='Lead Creation';
          objLead.Account__c= ac.id;
          objLead.leadSource ='Walk-In';
          
      Insert objlead;
          test.stopTest();
          
      }
    public static testMethod void getIMShowroomUsertest(){
        
          Test.startTest();
          
           Showroom_User__c objShowroom1= TestData_Factory.createShowroomUser(false);
      
        objShowroom1.Daily_Assignment__c = 1;
        objShowroom1.Daily_Assignment_Limit__c = 10;
        objShowroom1.IsActive__c = true; 
        objShowroom1.Monthly_Assignment__c = 0;
        objShowroom1.Monthly_Assignment_Limit__c = 100;
        objShowroom1.Role__c ='Iron Man';
        objShowroom1.Outskirts_Assignment__c=1;
        objShowroom1.Outskirts_Assignment_Limit__c=3;
        objShowroom1.IM_Class__c= 'Gold';
        
        insert ObjShowroom1;
         objTerr = TestData_Factory.createTerritory('Area a',ObjShowroom1.id,'Bengaluru','Cluster A','123456',False);
          objTerr.Lat_Long__Latitude__s = 20.0936477440000;
          objTerr.Lat_Long__Longitude__s =  89.7849897840000;
          objTerr.Cluster_Brand__c ='Homelane';
          objTerr.Sales_Campaign__c ='Green Channel';
        
          
        
        Insert objTerr ;  
        Account ac = new account();
        ac.Name='testacc';
        insert ac;
        objLead = new Lead();
        objlead = TestData_Factory.CreateFreshLead(false);
        objlead.Postalcode = '123457';
        objLead.Brand__c ='Homelane';
        objLead.City='Bengaluru';
        objLead.IM_Assignment_Stage__c ='Lead Creation';
        objLead.Account__c= ac.id;
        objLead.leadSource ='Walk-In';
        
        Insert objlead;
        objLead.Lead_Score_for_Assignment__c =8;
        update objlead;
        
        IronmanDigitalLeadAssignment.getIMShowroomUser('Cluster A',objLead,true);
        test.stopTest();
    }
  public testMethod static void dummyTestCover() {
        
        Test.StartTest();
     IronmanDigitalLeadAssignment.dummyTestCover();
        
        Test.StopTest();
    }
}