force-app/main/default/objects/Showroom_User__c/Showroom_User__c.object-meta.xml
<CustomObject>
    <label>Showroom User</label>
    <nameField>
        <label>ShowRoom User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Showroom User</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Showroom_User__c/fields/Backlogs__c.field-meta.xml
<CustomField>
    <fullName>Backlogs__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Backlogs</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/Daily_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Daily_Assignment__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Daily Assignment</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/IronMan__c.field-meta.xml
<CustomField>
    <fullName>IronMan__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IronMan</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/Threashold__c.field-meta.xml
<CustomField>
    <fullName>Threashold__c</fullName>
    <defaultValue>18</defaultValue>
    <label>Threashold</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/IronmenBacklogsUpdateBatchHandler_Test.cls
@isTest
public class IronmenBacklogsUpdateBatchHandler_Test {
    Public static Lead ld;
    Public static Showroom_User__c showroomUser;
    @TestSetup static void data() { 
        //Create showroom User
        //
        showroomUser = TestData_Factory.createShowroomUser(false);
        showroomUser.Backlogs__c = 0;
        showroomUser.Daily_Assignment__c = 2;
        showroomUser.IsActive__c = True;
        showroomUser.IronMan__c = True;
        showroomUser.Threashold__c = 5;
        insert showroomUser;
        
        
        ld = TestData_Factory.CreateFreshLead(false);
        ld.Status = 'Fresh Lead';
        ld.Sub_Status__c = 'New';
        ld.Sales_Manager__c = showroomUser.Id;
        ld.Assigned_to_Resi_ASM__c = True;
        insert ld;
        
    }
    public testMethod static void IronmenBacklogsUpdateBatchTest1(){
        Test.startTest();
        showroomUser = [Select id from Showroom_User__c limit 1];
        Set<Id> setOfIronmenId = new Set<Id>();
        setOfIronmenId.add(showroomUser.id);
        Showroom_User__c dummyShowroomUser = TestData_Factory.createShowroomUser(True);
        setOfIronmenId.add(dummyShowroomUser.id);
        Map<Id,AggregateResult> mapOfIronmanWithAggregateResult = new Map<Id,AggregateResult>();
        mapOfIronmanWithAggregateResult = new Map<Id,AggregateResult>([SELECT Sales_Manager__r.Id Id,Count(Id) 
                                                                       FROM Lead 
                                                                       WHERE Sales_Manager__r.Id =:setOfIronmenId and Assigned_To_Resi_ASM__c =True 
                                                                       and Status='Fresh Lead' and (Sub_Status__c='New' or Sub_Status__c='Unverified') 
                                                                       GROUP BY Sales_Manager__r.Id]);
        IronmenBacklogsUpdateBatchHandler.updateBackLogsCount(setOfIronmenId, mapOfIronmanWithAggregateResult);
        IronmenBacklogsUpdateBatchHandler.updateBackLogsCount(null, null);
        test.stopTest();
    }
}