force-app/main/default/objects/Showroom_User__c/Showroom_User__c.object-meta.xml
<CustomObject>
    <label>Showroom User</label>
    <nameField>
        <label>ShowRoom User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Showroom User</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Showroom_User__c/fields/Backlogs__c.field-meta.xml
<CustomField>
    <fullName>Backlogs__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Backlogs</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/Daily_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Daily_Assignment__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Daily Assignment</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/Daily_Assignment_Limit__c.field-meta.xml
<CustomField>
    <fullName>Daily_Assignment_Limit__c</fullName>
    <defaultValue>7</defaultValue>
    <label>Daily Assignment Limit</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/Monthly_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Assignment__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Monthly Assignment</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/Monthly_Assignment_Limit__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Assignment_Limit__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Monthly Assignment Limit</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/Specialisation__c.field-meta.xml
<CustomField>
    <fullName>Specialisation__c</fullName>
    <label>Specialisation</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Renovation</fullName>
            </value>
            <value>
                <fullName>Paint</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/Threashold__c.field-meta.xml
<CustomField>
    <fullName>Threashold__c</fullName>
    <defaultValue>18</defaultValue>
    <label>Threashold</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/WT_Leads_Daily_Assignment__c.field-meta.xml
<CustomField>
    <fullName>WT_Leads_Daily_Assignment__c</fullName>
    <defaultValue>0</defaultValue>
    <label>WT Leads Daily Assignment</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/WT_Leads_Daily_Assignment_Limit__c.field-meta.xml
<CustomField>
    <fullName>WT_Leads_Daily_Assignment_Limit__c</fullName>
    <defaultValue>0</defaultValue>
    <label>WT Leads Daily Assignment Limit</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/IronManPaintSpecialistEmail_Test.cls
@isTest 
public class IronManPaintSpecialistEmail_Test {
     public static testMethod void execute() {
        Test.startTest();
        IronManPaintSpecialistScheduleEmail ss = new IronManPaintSpecialistScheduleEmail ();
        String sch = '0 0 23 * * ?';
        system.schedule('Test check', sch, ss);
        Test.stopTest();
    }
public static testMethod Void execute1(){
       Showroom_User__c objShowroom1= TestData_Factory.createShowroomUser(false);
        objShowroom1.Threashold__c = 10;
        objShowroom1.Backlogs__c = 2;
        objShowroom1.Daily_Assignment__c = 8;
        objShowroom1.Daily_Assignment_Limit__c = 10;
        objShowroom1.IsActive__c = true; 
        objShowroom1.Monthly_Assignment__c = 8;
        objShowroom1.Monthly_Assignment_Limit__c = 10;
        objShowroom1.WT_Leads_Daily_Assignment__c = 0;
        objShowroom1.WT_Leads_Daily_Assignment_Limit__c = 100;
        objShowroom1.Specialisation__c='Paint';
        insert ObjShowroom1;
        Showroom_User__c objShowroom2= TestData_Factory.createShowroomUser(false);
        objShowroom2.Threashold__c = 10;
        objShowroom2.Backlogs__c = 2;
        objShowroom2.Daily_Assignment__c = 9;
        objShowroom2.Daily_Assignment_Limit__c = 10;
        objShowroom2.IsActive__c = true; 
        objShowroom2.Monthly_Assignment__c = 8;
        objShowroom2.Monthly_Assignment_Limit__c = 10;
        objShowroom2.WT_Leads_Daily_Assignment__c = 0;
        objShowroom2.WT_Leads_Daily_Assignment_Limit__c = 100;
         objShowroom2.Specialisation__c='Paint';
        insert ObjShowroom2;
       List<Showroom_User__c> showroomUserList = new  List<Showroom_User__c>();
       Decimal cumulativeValue =10;
       showroomUserList.add(ObjShowroom1);
       showroomUserList.add(ObjShowroom2);
     
       list<Messaging.SingleEmailMessage> mailList = new List<Messaging.SingleEmailMessage>();
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        
     String  htmlBody = '<table border="1" style="border-collapse: collapse"><caption>Request Summary Data</caption><tr><th>Name</th><th>Daily Assignment</th><th>Daily Assignment limit</th><th>Monthly Assignment</th><th>Daily Assignment limit</th></tr>';
        List<String> toAddresses = new List<String>(); 
         toAddresses.add('testemail@test.com');
        mail.setToAddresses(toAddresses);
        mail.setSubject('Daily limit exceeds');
       mail.setHtmlBody(HTMLBody);
       String subject = 'Daily/Monthly limit for Pronto Paint has reached '+ cumulativeValue +'% utilization';
                String messageBody = '<html><body> Team,<br>The daily/monthly cumulative assignment for the Pronto Paint specialist has reached '+ cumulativeValue +'%. Please check if the limit needs to be changed.<br>Thanks </body></html>';
                
                mail.setSubject(subject);
                mail.setHtmlBody(messageBody+htmlBody);
                mailList.add(mail); 
        Test.startTest();
        
      IronManPaintSpecialistScheduleEmail ss = new IronManPaintSpecialistScheduleEmail ();
        String sch = '0 0 23 * * ?';
        system.schedule('Test check', sch, ss);
        Test.stopTest();
    }
    public static testMethod Void execute2(){
       Showroom_User__c objShowroom1= TestData_Factory.createShowroomUser(false);
        objShowroom1.Threashold__c = 10;
        objShowroom1.Backlogs__c = 2;
        objShowroom1.Daily_Assignment__c = 8;
        objShowroom1.Daily_Assignment_Limit__c = 10;
        objShowroom1.IsActive__c = false; 
        objShowroom1.Monthly_Assignment__c = 8;
        objShowroom1.Monthly_Assignment_Limit__c = 10;
        objShowroom1.WT_Leads_Daily_Assignment__c = 0;
        objShowroom1.WT_Leads_Daily_Assignment_Limit__c = 100;
        objShowroom1.Specialisation__c='Paint';
        insert ObjShowroom1;
        Showroom_User__c objShowroom2= TestData_Factory.createShowroomUser(false);
        objShowroom2.Threashold__c = 10;
        objShowroom2.Backlogs__c = 2;
        objShowroom2.Daily_Assignment__c = 8;
        objShowroom2.Daily_Assignment_Limit__c = 10;
        objShowroom2.IsActive__c = false; 
        objShowroom2.Monthly_Assignment__c = 8;
        objShowroom2.Monthly_Assignment_Limit__c = 10;
        objShowroom2.WT_Leads_Daily_Assignment__c = 0;
        objShowroom2.WT_Leads_Daily_Assignment_Limit__c = 100;
         objShowroom2.Specialisation__c='Paint';
        insert ObjShowroom2;
       List<Showroom_User__c> showroomUserList = new  List<Showroom_User__c>();
       
       list<Messaging.SingleEmailMessage> mailList = new List<Messaging.SingleEmailMessage>();
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        
        List<String> toAddresses = new List<String>(); 
         toAddresses.add('testemail@test.com');
        mail.setToAddresses(toAddresses);
        mail.setSubject('No Im is active');
        Test.startTest();
        
      IronManPaintSpecialistScheduleEmail ss = new IronManPaintSpecialistScheduleEmail ();
        String sch = '0 0 23 * * ?';
        system.schedule('Test check', sch, ss);
        Test.stopTest();
}
}