force-app/main/default/objects/Showroom_User__c/Showroom_User__c.object-meta.xml
<CustomObject>
    <label>Showroom User</label>
    <nameField>
        <label>ShowRoom User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Showroom User</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Showroom_User__c/fields/Backlogs__c.field-meta.xml
<CustomField>
    <fullName>Backlogs__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Backlogs</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/IronmenBacklogsUpdateBatchHandler.cls
/**
* @File Name          : IronmenBacklogsUpdateBatchHandler.cls
* @Description        : Batch class.
* @Author             : Bharatesh Shetty
* @Group              : 
* @Last Modified By   : Bharatesh Shetty
* @Last Modified On   : 11/21/2019, 12:21:43 PM
* @Modification Log   : 
*==============================================================================
* Ver         Date                     Author      		      Modification
*==============================================================================
* 1.0    11/21/2019, 12:20:14 PM   Bharatesh Shetty     Initial Version
**/
public class IronmenBacklogsUpdateBatchHandler {
    public static void updateBackLogsCount(Set<Id> setOfIronmenId,Map<Id,AggregateResult> mapOfIronmanWithAggregateResult){
        try{
            if(!setOfIronmenId.isEmpty() && !mapOfIronmanWithAggregateResult.isEmpty()){
                Map<Id,Showroom_User__c> mapOfIronMenToUpdateBacklogs = new Map<Id,Showroom_User__c>();
                for(Id ironmanId :setOfIronmenId){
                    Showroom_User__c ironman = new Showroom_User__c();
                    ironman.Id = ironmanId;
                    if(mapOfIronmanWithAggregateResult.containskey(ironmanId)){
                        ironman.Backlogs__c = (Decimal)mapOfIronmanWithAggregateResult.get(ironmanId).get('expr0');
                    }
                    else{
                        ironman.Backlogs__c = 0;
                    }
                    mapOfIronMenToUpdateBacklogs.put(ironmanId,ironman);
                    System.debug('ironman record Update: '+ironman);
                }
                if(!mapOfIronMenToUpdateBacklogs.isEmpty()){
                    update mapOfIronMenToUpdateBacklogs.values();
                }
            }
            
        }
        catch(Exception e){
            system.debug('Exception : '+e.getStackTraceString());
            system.debug('Exception message: '+e.getMessage());
            Logger.log('Exception','IronmenBacklogsUpdateBatchHandler class','updateBackLogsCount method',e.getMessage(),e.getStackTraceString(),null);
        } 
    }
    
}