force-app/main/default/objects/Showroom_User__c/Showroom_User__c.object-meta.xml
<CustomObject>
    <label>Showroom User</label>
    <nameField>
        <label>ShowRoom User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Showroom User</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Showroom_User__c/fields/Daily_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Daily_Assignment__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Daily Assignment</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/Monthly_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Assignment__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Monthly Assignment</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/Offline_Daily_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Offline_Daily_Assignment__c</fullName>
    <label>Offline Daily Assignment</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/Offline_Monthly_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Offline_Monthly_Assignment__c</fullName>
    <label>Offline Monthly Assignment</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/Outskirts_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Outskirts_Assignment__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Outskirts Daily Assignment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/Outskirts_Monthly_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Outskirts_Monthly_Assignment__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Outskirts Monthly Assignment</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/WT_Leads_Daily_Assignment__c.field-meta.xml
<CustomField>
    <fullName>WT_Leads_Daily_Assignment__c</fullName>
    <defaultValue>0</defaultValue>
    <label>WT Leads Daily Assignment</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/WT_Leads_Monthly_Assignment__c.field-meta.xml
<CustomField>
    <fullName>WT_Leads_Monthly_Assignment__c</fullName>
    <defaultValue>0</defaultValue>
    <label>WT Leads Monthly Assignment</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/IronmenDailyAssignmentResetBatch.cls
/**
* @File Name          : IronmenDailyAssignmentResetBatch.cls
* @Description        : Batch class.
* @Author             : Bharatesh Shetty
* @Group              : 
* @Last Modified By   : Bharatesh Shetty
* @Last Modified On   : 11/21/2019, 12:21:43 PM
* @Modification Log   : 
*==============================================================================
* Ver         Date                     Author                 Modification
*==============================================================================
* 1.0    11/21/2019, 12:20:14 PM   Bharatesh Shetty     Initial Version
**/
global class IronmenDailyAssignmentResetBatch implements Database.Batchable<sObject>,Schedulable{
    Public Set<Id> setOfIds = new Set<Id>();
    // Constructor to excecute only set of records in the Batch.
    global IronmenDailyAssignmentResetBatch(Set<Id> setOfIds){
        this.setOfIds = setOfIds;
    }
    global IronmenDailyAssignmentResetBatch(){
    }
    global void execute(SchedulableContext SC) {
        database.executebatch(new IronmenDailyAssignmentResetBatch(),100);
    }
    global Database.QueryLocator start(Database.BatchableContext bc) {
        String queryString = UtilityClass.getQueryString('Showroom_User__c');
        //System.debug('setOfIds '+setOfIds);
        queryString += ' From Showroom_User__c where Id !=null';
        if(!setOfIds.isEmpty()){
            queryString += ' and id=:setOfIds';
        }
        return Database.getQueryLocator(queryString);
    }
    
    global void execute(Database.BatchableContext bc, List<Showroom_User__c> listOfSalesManager) { 
        try{
            Date lastDayOfMonth = Date.newInstance(System.today().year(), System.today().month(),Date.daysInMonth(System.today().year(), System.today().month()));
            System.debug('lastDayOfMonth: '+lastDayOfMonth);
            if(!listOfSalesManager.isEmpty()){
                for(Showroom_User__c ironman :listOfSalesManager){
                    ironman.Daily_Assignment__c = 0;
                    ironman.WT_Leads_Daily_Assignment__c = 0;
                    ironman.Outskirts_Assignment__c=0;
                    ironman.Offline_Daily_Assignment__c=0;
                    if(System.today()==lastDayOfMonth || Test.isRunningTest()){
                        //System.debug('Today is last day of the month.');
                        ironman.Monthly_Assignment__c = 0;
                        ironman.Outskirts_Monthly_Assignment__c=0;
                        ironman.WT_Leads_Monthly_Assignment__c=0;
                        ironman.Offline_Monthly_Assignment__c	=0;
                    }
                }
                update listOfSalesManager;
            }
        }
        catch(Exception e){
            system.debug('Exception : '+e.getStackTraceString());
        }
    }   
    
    global void finish(Database.BatchableContext bc){ 
        System.debug('finish method');   
    }
}