force-app/main/default/objects/Showroom_User__c/Showroom_User__c.object-meta.xml
<CustomObject>
    <label>Showroom User</label>
    <nameField>
        <label>ShowRoom User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Showroom User</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Showroom_User__c/fields/Daily_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Daily_Assignment__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Daily Assignment</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/IM_Class__c.field-meta.xml
<CustomField>
    <fullName>IM_Class__c</fullName>
    <defaultValue>&apos;Bronze&apos;</defaultValue>
    <label>IM Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/IronMan__c.field-meta.xml
<CustomField>
    <fullName>IronMan__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IronMan</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/Monthly_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Assignment__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Monthly Assignment</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/Outskirts_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Outskirts_Assignment__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Outskirts Daily Assignment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/Outskirts_Monthly_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Outskirts_Monthly_Assignment__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Outskirts Monthly Assignment</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/Reached_Daily_Limit__c.field-meta.xml
<CustomField>
    <fullName>Reached_Daily_Limit__c</fullName>
    <formula>IF((Daily_Assignment__c &gt;= Daily_Assignment_Limit__c),true,false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Reached Daily Limit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/Reached_Monthly_Limit__c.field-meta.xml
<CustomField>
    <fullName>Reached_Monthly_Limit__c</fullName>
    <formula>IF((Monthly_Assignment__c+Monthly_Exception_Leads_Assigned__c &gt;= Monthly_Assignment_Limit__c),true,false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Reached Monthly Limit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Showroom Manager</fullName>
            </value>
            <value>
                <fullName>Sales Manager</fullName>
            </value>
            <value>
                <fullName>Iron Man</fullName>
            </value>
            <value>
                <fullName>Delivery Manager</fullName>
            </value>
            <value>
                <fullName>Design Manager</fullName>
            </value>
            <value>
                <fullName>Business Development Manager</fullName>
            </value>
            <value>
                <fullName>Pre-Sales Freelancer</fullName>
            </value>
            <value>
                <fullName>Tele Caller Agent</fullName>
            </value>
            <value>
                <fullName>Product Consultant</fullName>
            </value>
            <value>
                <fullName>Doowup Presales</fullName>
            </value>
            <value>
                <fullName>Central Team Agent</fullName>
            </value>
            <value>
                <fullName>Inside Sales Agent</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
            <value>
                <fullName>Desgin Manager</fullName>
                <isActive>false</isActive>
                <label>Desgin Manager</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/Weekly_Off_Days__c.field-meta.xml
<CustomField>
    <fullName>Weekly_Off_Days__c</fullName>
    <label>Weekly Off Days</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sunday</fullName>
            </value>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Territory__c/Territory__c.object-meta.xml
<CustomObject>
    <label>Territory</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory__c/fields/Assignment__c.field-meta.xml
<CustomField>
    <fullName>Assignment__c</fullName>
    <formula>IF( ISPICKVAL(City__c, &apos;Outskirts&apos;), Ironman__r.Outskirts_Assignment__c , Ironman__r.Daily_Assignment__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Assignment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territory__c/fields/Cluster__c.field-meta.xml
<CustomField>
    <fullName>Cluster__c</fullName>
    <label>Cluster</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BLR_GOP_1</fullName>
            </value>
            <value>
                <fullName>Test1</fullName>
            </value>
            <value>
                <fullName>Test2</fullName>
            </value>
            <value>
                <fullName>BLR_KAN_6</fullName>
            </value>
            <value>
                <fullName>BLR_HEB_5</fullName>
            </value>
            <value>
                <fullName>BLR_MUS_4</fullName>
            </value>
            <value>
                <fullName>BLR_WHI_3</fullName>
            </value>
            <value>
                <fullName>BLR_HSR_2</fullName>
            </value>
            <value>
                <fullName>CBE_ PLZ_1</fullName>
            </value>
            <value>
                <fullName>HYD_SHG_1</fullName>
            </value>
            <value>
                <fullName>MUM_THN_2</fullName>
            </value>
            <value>
                <fullName>HYD_BAN_2</fullName>
            </value>
            <value>
                <fullName>KOL_MAN_1</fullName>
            </value>
            <value>
                <fullName>CHE_CTY_2</fullName>
            </value>
            <value>
                <fullName>CHE_ OMR_1</fullName>
            </value>
            <value>
                <fullName>NCR_NOI_3</fullName>
            </value>
            <value>
                <fullName>NCR_GUR_1</fullName>
            </value>
            <value>
                <fullName>NCR_KRN_2</fullName>
            </value>
            <value>
                <fullName>PUN_BAN_1</fullName>
            </value>
            <value>
                <fullName>MUM_GOR_1</fullName>
            </value>
            <value>
                <fullName>BLR_BSR_7</fullName>
            </value>
            <value>
                <fullName>VIZ_SQRLT_1</fullName>
            </value>
            <value>
                <fullName>MYS_SQRLT_1</fullName>
            </value>
            <value>
                <fullName>KOL_CHI_2</fullName>
            </value>
            <value>
                <fullName>LKO_SQRLT_1</fullName>
            </value>
            <value>
                <fullName>PUN_VIM_2</fullName>
            </value>
            <value>
                <fullName>BAN_JPN_6</fullName>
            </value>
            <value>
                <fullName>SRT_SQRLT_1</fullName>
            </value>
            <value>
                <fullName>CHE_SQRLT_1</fullName>
            </value>
            <value>
                <fullName>CHE_ GST_3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Territory__c/fields/Ironman__c.field-meta.xml
<CustomField>
    <fullName>Ironman__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Ironman</label>
    <referenceTo>Showroom_User__c</referenceTo>
    <relationshipLabel>Territories</relationshipLabel>
    <relationshipName>Territories</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Territory__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <description>IF(OR(Ironman__r.Backlogs_Inactivity__c =True, Ironman__r.IsActive__c =False,Ironman__r.Reached_Daily_Limit__c = True,Ironman__r.Reached_Monthly_Limit__c = True),false,true)</description>
    <formula>IF ( ISPICKVAL(City__c, &apos;Outskirts&apos;),
IF(OR(Ironman__r.IsActive__c =False, Ironman__r.Reached_Outskirts_Monthly_Limit__c=true, Ironman__r.Reached_Outskirts_Limit__c =True ),false,true),

IF(OR(Ironman__r.Backlogs_Inactivity__c =True, Ironman__r.IsActive__c =False,Ironman__r.Reached_Daily_Limit__c = True,Ironman__r.Reached_Monthly_Limit__c = True),false,true))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Territory__c/fields/Monthly_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Assignment__c</fullName>
    <formula>If( ISPICKVAL( City__c , &apos;Outskirts&apos;), Ironman__r.Outskirts_Monthly_Assignment__c , Ironman__r.Monthly_Assignment__c  )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Monthly Assignment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/IronmanDigitalLeadAssignment.cls
public class IronmanDigitalLeadAssignment {
    
    public static List<Showroom_user__c> getIMShowroomUser(String clusterName , Lead inputLead ,Boolean GreenFlag){
        List<Showroom_user__c>  ShowroomUserList = new List<Showroom_user__c>();
        dateTime todayDate = Date.Today();
        System.debug('DayOfTheWeek: '+todayDate.format('EEEE'));
        
        String todayDayInString = todayDate.format('EEEE');
        String showroomUserPCRole = GenericConstants.PRODUCT_CONSULTANT_ROLE;
        String showroomUserCentralRole = GenericConstants.Central_Team_Agent;
        
        
        Map<string,list<Showroom_User__c>>  showroomUserclassMap = new  Map<string,List<Showroom_User__c>>();
        list<Showroom_User__c> lstShowroomUser = [Select Name,Daily_Assignment__c,Monthly_Assignment__c,Weekly_Off_Days__c,IsActive__c,Outskirts_Assignment__c,Outskirts_Monthly_Assignment__c,IM_Class__c,Role__c,
                                                  (Select id,Name,Cluster__C,Assignment__c,Lat_Long__Latitude__s,Lat_Long__Longitude__s,IronMan__c,Monthly_Assignment__c
                                                   from Territories__r) 
                                                  From Showroom_User__c 
                                                  where ID IN (Select IronMan__c 
                                                               from Territory__c 
                                                               where Cluster__C =:clusterName and Is_Active__c = True) 
                                                  and Daily_Assignment__c != NULL and Weekly_Off_Days__c Excludes(:todayDayInString) and Role__c != :showroomUserPCRole];
        System.debug('---lstShowroomUser----'+lstShowroomUser);
        
        
        
        if(GreenFlag ){
            
           
              
            List<Showroom_User__c> centralTeamList = [select id,Daily_Assignment__c,Weekly_Off_Days__c,IsActive__c,Monthly_Assignment__c,Role__c,Outskirts_Assignment__c,Outskirts_Monthly_Assignment__c
                                                      from Showroom_User__c 
                                                      where Role__c =:showroomUserCentralRole 
                                                      and Weekly_Off_Days__c Excludes(:todayDayInString) and IsActive__c= true 
                                                      and Reached_Daily_Limit__c=false and Reached_Monthly_Limit__c=false ];
            system.debug(' centralTeamList '+  centralTeamList);
            
            
            if(inputLead!= null){
                if(inputLead.Green_Lead_Class__c == GenericConstants.Green_Lead_Gold_Plus){
                    if(!lstShowroomUser.isEmpty()) {
                        ShowroomUserList=IronmanDigitalLeadAssignment.getIMclassbasedUser(GenericConstants.IM_Class_Gold,lstShowroomUser);
                        
                        if(ShowroomUserList.isEmpty() && !centralTeamList.isEmpty()){
                            ShowroomUserList =  centralTeamList;
                        }
                        
                    }
                }
                else if(inputLead.Green_Lead_Class__c == GenericConstants.Green_Lead_Gold){
                    if(!lstShowroomUser.isEmpty()) {
                        ShowroomUserList = IronmanDigitalLeadAssignment.getIMclassbasedUser(GenericConstants.IM_Class_Gold,lstShowroomUser);
                        
                        if(ShowroomUserList.isEmpty()){
                            ShowroomUserList = IronmanDigitalLeadAssignment.getIMclassbasedUser(GenericConstants.IM_Class_Silver,lstShowroomUser);
                        }
                        if(ShowroomUserList.isEmpty() && !centralTeamList.isEmpty()){
                            ShowroomUserList = centralTeamList;
                        }
                        
                    }
                }
                else if(inputLead.Green_Lead_Class__c == GenericConstants.Green_Lead_Silver || inputLead.Green_Lead_Class__c == GenericConstants.Green_Lead_Silver_Minus){
                    if(!lstShowroomUser.isEmpty()) {
                        ShowroomUserList = IronmanDigitalLeadAssignment.getIMclassbasedUser(GenericConstants.IM_Class_Gold,lstShowroomUser);
                        ShowroomUserList.addAll(IronmanDigitalLeadAssignment.getIMclassbasedUser(GenericConstants.IM_Class_Silver,lstShowroomUser));
                    }
                    if(ShowroomUserList.isEmpty() && !centralTeamList.isEmpty()){
                            ShowroomUserList =  centralTeamList;
                        }
                }
                
                else if(inputLead.Green_Lead_Class__c == GenericConstants.Green_Lead_Bronze_Plus){
                    if(!lstShowroomUser.isEmpty()) {
                        ShowroomUserList = IronmanDigitalLeadAssignment.getIMclassbasedUser(GenericConstants.IM_Class_Silver,lstShowroomUser);
                        ShowroomUserList.addAll(IronmanDigitalLeadAssignment.getIMclassbasedUser(GenericConstants.IM_Class_Bronze,lstShowroomUser));
                    }
                    if(ShowroomUserList.isEmpty() && !centralTeamList.isEmpty()){
                            ShowroomUserList =  centralTeamList;
                        }
                    
                }else{
                    if(!lstShowroomUser.isEmpty()) {
                        
                        ShowroomUserList = IronmanDigitalLeadAssignment.getIMclassbasedUser(GenericConstants.IM_Class_Bronze,lstShowroomUser);
                    }
                }
            
               /** if(mapofIMAndLeadClass.containsKey(inputLead.Green_Lead_Class__c)){
                    String IMClass = mapofIMAndLeadClass.get(inputLead.Green_Lead_Class__c);
                    if(!lstShowroomUser.isEmpty() && String.isNotBlank(IMClass) && IMClass != null){
                        
                        for(Showroom_User__c user : lstShowroomUser){
                            if(user.IM_Class__C == IMClass ){
                                ShowroomUserList.add(user);
                            }
                            
                        }
                        if(ShowroomUserList.isEmpty()){
                            if(inputLead.Green_Lead_Class__c!=genericConstants.Green_Lead_Bronze){
                                if(!centralTeamList.isEmpty()){
                                  ShowroomUserList =  centralTeamList;   
                                }else{
                                   //ShowroomUserList will remain empty 
                                }
                                 
                            }else{
                                //ShowroomUserList will remain empty
                            }   
                        }
                        
                    }
                    else{
                        if(inputLead.Green_Lead_Class__c!=genericConstants.Green_Lead_Bronze){
                            if(!centralTeamList.isEmpty()){
                                  ShowroomUserList =  centralTeamList;   
                                }else{
                                   //ShowroomUserList will remain empty 
                                }  
                        }else{
                            //ShowroomUserList will remain empty
                        } 
                    }
                    
                }
                else{
                  ShowroomUserList  = lstShowroomUser;  
                }
                */
            }
               
        }
        
        
        else{
            ShowroomUserList  = lstShowroomUser;
        }
        
        return ShowroomUserList;
        
    }
    
   
    
     
    
    public static  Showroom_User__c getChampionBasedOnleastAssignment(list<Showroom_User__c> lstShowroomUser){
        Showroom_User__c  userWithLeastAssignment =null;
        if(!lstShowroomUser.isEmpty()){
            
            Decimal minAssignmentNumber = 99999;
            for(Showroom_User__c IMUser :lstShowroomUser){
                //Showroom_User__c  assignUser = new Showroom_User__c();
                if (ImUser.Daily_Assignment__c < minAssignmentNumber) {
                    minAssignmentNumber = ImUser.Daily_Assignment__c;
                    userWithLeastAssignment = imUser;
                }
            }
            
        }
        system.debug('userWithLeastAssignment '+ userWithLeastAssignment);
        return userWithLeastAssignment;
        
        
    }
    
    public static List<Showroom_User__c> getIMclassbasedUser(String className,List<Showroom_user__c>  lstShowroomUser){
        List<Showroom_User__c> ShowroomUserList = new List<Showroom_User__c>();
        
        for(Showroom_User__c user : lstShowroomUser){
            if(user.IM_Class__C == className ){
                ShowroomUserList.add(user);
            }
            
        }
        
        return ShowroomUserList;
    }
    
    
    
    public static void dummyTestCover(){
        Integer i =0;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++; i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
     i++;}
}