force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Created to map the next step with respect to lead status</description>
    <label>Next Step For Lead Status Mapping</label>
</CustomObject>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>URLString For the Opportunity Record</description>
    <label>URLString</label>
</CustomObject>

force-app/main/default/objects/Setup_Configuration__c/Setup_Configuration__c.object-meta.xml
<CustomObject>
    <label>Setup Configuration</label>
    <nameField>
        <displayFormat>SC -{0000000000}</displayFormat>
        <label>Setup Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setup Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Setup_Configuration__c/fields/Initiator_Email__c.field-meta.xml
<CustomField>
    <fullName>Initiator_Email__c</fullName>
    <label>Initiator Email</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Setup_Configuration__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Setup Configurations</relationshipLabel>
    <relationshipName>Setup_Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Setup_Configuration__c/fields/Operation_Status__c.field-meta.xml
<CustomField>
    <fullName>Operation_Status__c</fullName>
    <label>Operation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Setup_Configuration__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Setup Configurations</relationshipLabel>
    <relationshipName>Setup_Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Setup_Configuration__c/fields/Sales_Manager_Email__c.field-meta.xml
<CustomField>
    <fullName>Sales_Manager_Email__c</fullName>
    <label>Sales Manager Email</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Setup_Configuration__c/fields/Showroom_User__c.field-meta.xml
<CustomField>
    <fullName>Showroom_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Showroom User</label>
    <referenceTo>Showroom_User__c</referenceTo>
    <relationshipLabel>Setup Configurations</relationshipLabel>
    <relationshipName>Setup_Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Setup_Configuration__c/fields/Type_Of_Transfer__c.field-meta.xml
<CustomField>
    <fullName>Type_Of_Transfer__c</fullName>
    <label>Type Of Transfer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IM Transfer</fullName>
            </value>
            <value>
                <fullName>Freelancer Transfer</fullName>
            </value>
            <value>
                <fullName>Telecaller Transfer</fullName>
            </value>
            <value>
                <fullName>Nimbus Transfer</fullName>
            </value>
            <value>
                <fullName>Doowup Transfer</fullName>
            </value>
            <value>
                <fullName>Doowup Presales Transfer</fullName>
            </value>
            <value>
                <fullName>Nimbus DL Offline Transfer</fullName>
            </value>
            <value>
                <fullName>Nimbus DL Digital Transfer</fullName>
            </value>
            <value>
                <fullName>Offline Relanded Transfer</fullName>
            </value>
            <value>
                <fullName>IM Classification</fullName>
            </value>
            <value>
                <fullName>Inside Sales Transfer</fullName>
            </value>
            <value>
                <fullName>Nimbus Relanded Transfer</fullName>
            </value>
            <value>
                <fullName>Nimbus Hindi Transfer</fullName>
            </value>
            <value>
                <fullName>Nimbus Telugu Transfer</fullName>
            </value>
            <value>
                <fullName>Cubico Transfer</fullName>
            </value>
            <value>
                <fullName>Nimbus Doowup Offline Transfer</fullName>
            </value>
            <value>
                <fullName>Nimbus HL Missed Call Transfer</fullName>
            </value>
            <value>
                <fullName>Nimbus Doowup Opp Transfer</fullName>
            </value>
            <value>
                <fullName>Globiva Offline RL Transfer</fullName>
            </value>
            <value>
                <fullName>Globiva Offline PB Transfer</fullName>
            </value>
            <value>
                <fullName>Globiva Relanded Transfer</fullName>
            </value>
            <value>
                <fullName>Globiva Feedback Digital Transfer</fullName>
            </value>
            <value>
                <fullName>Globiva Digital North Transfer</fullName>
            </value>
            <value>
                <fullName>Globiva Digital South Transfer</fullName>
            </value>
            <value>
                <fullName>Globiva Digital East Transfer</fullName>
            </value>
            <value>
                <fullName>Globiva Digital West Transfer</fullName>
            </value>
            <value>
                <fullName>Globiva Digital Centre Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Setup_Configuration__c/recordTypes/Lead_Opportunity_Transfer.recordType-meta.xml
<RecordType>
    <fullName>Lead_Opportunity_Transfer</fullName>
    <active>true</active>
    <label>Lead Opportunity Transfer</label>
</RecordType>

force-app/main/default/objects/Showroom_User__c/Showroom_User__c.object-meta.xml
<CustomObject>
    <label>Showroom User</label>
    <nameField>
        <label>ShowRoom User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Showroom User</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Showroom_User__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Showroom Manager</fullName>
            </value>
            <value>
                <fullName>Sales Manager</fullName>
            </value>
            <value>
                <fullName>Iron Man</fullName>
            </value>
            <value>
                <fullName>Delivery Manager</fullName>
            </value>
            <value>
                <fullName>Design Manager</fullName>
            </value>
            <value>
                <fullName>Business Development Manager</fullName>
            </value>
            <value>
                <fullName>Pre-Sales Freelancer</fullName>
            </value>
            <value>
                <fullName>Tele Caller Agent</fullName>
            </value>
            <value>
                <fullName>Product Consultant</fullName>
            </value>
            <value>
                <fullName>Doowup Presales</fullName>
            </value>
            <value>
                <fullName>Central Team Agent</fullName>
            </value>
            <value>
                <fullName>Inside Sales Agent</fullName>
            </value>
            <value>
                <fullName>Dealer</fullName>
            </value>
            <value>
                <fullName>Desgin Manager</fullName>
                <isActive>false</isActive>
                <label>Desgin Manager</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LeadAndOpportunityTransferBatch_Test.cls
@isTest
public class LeadAndOpportunityTransferBatch_Test {
    Public static Lead ld, Dlead;
    Public static Account accountRec,accountRecDlead;
    Public static Opportunity opportunityRec;
    Public static Showroom_User__C IMRec;
    public static Setup_Configuration__c setUp;
    public static ID recTypeId;
    public static user WTAUser;
    
    @TestSetup static void data() {
        //Create Lead Record
        accountRec = TestData_factory.createAccount(true);
        accountRecDlead = TestData_factory.createAccount(true);
        ld = TestData_Factory.CreateFreshLead(false);
        Dlead = TestData_Factory.CreateFreshDoowupLead(false);
        ld.Account__c = accountRec.id;
        insert ld;
        Dlead.Account__c = accountRecDlead.id;
        insert Dlead;
        opportunityRec = TestData_factory.createOpportunity(accountRec.Id, true);
        IMRec = TestData_factory.createShowroomUser(true);
         WTAUser = TestData_factory.inserWTAUser('usr22@gmail.com','us2',true);       
        Setup_Configuration__c setUpUpdate = new  Setup_Configuration__c();
        recTypeId = Schema.SObjectType.Setup_Configuration__c.getRecordTypeInfosByDeveloperName().get(GenericConstants.LEAD_OPPORTUNITY_TRANSFER).getRecordTypeId();
        
        insert setUpUpdate;
        
    }
    
    public static testMethod void leadOrOpportunityUpdateTest1(){
        Test.startTest();
        ld =[select Id from Lead where Phone = '9000000000' Limit 1];
        IMRec = [Select id,Email__c from Showroom_User__C limit 1];
        recTypeId = Schema.SObjectType.Setup_Configuration__c.getRecordTypeInfosByDeveloperName().get(GenericConstants.LEAD_OPPORTUNITY_TRANSFER).getRecordTypeId();
        setUp =[select id,Name from Setup_Configuration__c limit 1];
        setUp.Initiator_Email__c ='abc@abc.com';
        setUp.Lead__c =ld.id;
        setUp.Type_Of_Transfer__c ='IM Transfer';
        setUp.RecordTypeId = recTypeId;
        setUp.Sales_Manager_Email__c =IMRec.Email__c;
        setUp.Operation_Status__c='Open';
        
        update setUp;
        LeadAndOpportunityTransferBatch ldTransfer = new LeadAndOpportunityTransferBatch();
        database.executeBatch(ldTransfer);
        Test.stopTest();
        
        
    }
    public static testMethod void leadOrOpportunityUpdateTest2(){
        Test.startTest();
        ld =[select Id from Lead where Phone = '9000000000' Limit 1];
        IMRec = [Select id,Email__c from Showroom_User__C limit 1];
        opportunityRec = [select id from Opportunity limit 1];
        recTypeId = Schema.SObjectType.Setup_Configuration__c.getRecordTypeInfosByDeveloperName().get(GenericConstants.LEAD_OPPORTUNITY_TRANSFER).getRecordTypeId();
        setUp =[select id,Name from Setup_Configuration__c limit 1];
        setUp.Initiator_Email__c ='abc@abc.com';
        setUp.Opportunity__c =opportunityRec.id;
        setUp.Type_Of_Transfer__c ='IM Transfer';
        setUp.RecordTypeId =recTypeId;
        setUp.Sales_Manager_Email__c =IMRec.Email__c;
        setUp.Operation_Status__c='Open';
        
        update setUp;
        LeadAndOpportunityTransferBatch ldTransfer = new LeadAndOpportunityTransferBatch();
        database.executeBatch(ldTransfer);
        Test.stopTest();
        
        
    }
    public static testMethod void leadOrOpportunityUpdateTest3(){
        Test.startTest();
        ld =[select Id from Lead where Phone = '9000000011' Limit 1];
        IMRec = [Select id,Email__c from Showroom_User__C limit 1];
        opportunityRec = [select id from Opportunity limit 1];
        recTypeId = Schema.SObjectType.Setup_Configuration__c.getRecordTypeInfosByDeveloperName().get(GenericConstants.LEAD_OPPORTUNITY_TRANSFER).getRecordTypeId();
        setUp =[select id,Name from Setup_Configuration__c limit 1];
        setUp.Initiator_Email__c ='abc@abc.com';
        setUp.Lead__c = ld.id;
        setUp.Type_Of_Transfer__c ='FreeLancer Transfer';
        setUp.RecordTypeId =recTypeId;
        setUp.Sales_Manager_Email__c =IMRec.Email__c;
        setUp.Operation_Status__c='Open';
        
    //    update setUp;
        LeadAndOpportunityTransferBatch ldTransfer = new LeadAndOpportunityTransferBatch();
        database.executeBatch(ldTransfer);
        Test.stopTest();
        
        
    }
     public static testMethod void leadOrOpportunityUpdateTest4(){
        Test.startTest();
        ld =[select Id from Lead where Phone = '9000000011' Limit 1];
        IMRec = [Select id,Email__c, Role__c from Showroom_User__C limit 1];
         Imrec.Role__c = 'Tele Caller Agent';
         update IMRec ;
        recTypeId = Schema.SObjectType.Setup_Configuration__c.getRecordTypeInfosByDeveloperName().get(GenericConstants.LEAD_OPPORTUNITY_TRANSFER).getRecordTypeId();
        setUp =[select id,Name from Setup_Configuration__c limit 1];
        setUp.Initiator_Email__c ='abc@abc.com';
        setUp.Lead__c =ld.id;
        setUp.Type_Of_Transfer__c ='Telecaller Transfer';
        setUp.RecordTypeId = recTypeId;
        setUp.Sales_Manager_Email__c =IMRec.Email__c;
        setUp.Operation_Status__c='Open';
        
         update setUp;
        LeadAndOpportunityTransferBatch ldTransfer = new LeadAndOpportunityTransferBatch();
        database.executeBatch(ldTransfer);
        Test.stopTest();
        
        
    }
     public static testMethod void leadOrOpportunityUpdateTest5(){
        Test.startTest();
        ld =[select Id from Lead where Phone = '9000000000' Limit 1];
        IMRec = [Select id,Email__c from Showroom_User__C limit 1];
        recTypeId = Schema.SObjectType.Setup_Configuration__c.getRecordTypeInfosByDeveloperName().get(GenericConstants.LEAD_OPPORTUNITY_TRANSFER).getRecordTypeId();
        setUp =[select id,Name from Setup_Configuration__c limit 1];
        setUp.Initiator_Email__c ='abc@abc.com';
        setUp.Lead__c =ld.id;
        setUp.Type_Of_Transfer__c ='Nimbus Transfer';
        setUp.RecordTypeId = recTypeId;
        setUp.Sales_Manager_Email__c =IMRec.Email__c;
        setUp.Operation_Status__c='Open';
        
        update setUp;
        LeadAndOpportunityTransferBatch ldTransfer = new LeadAndOpportunityTransferBatch();
        database.executeBatch(ldTransfer);
        Test.stopTest();
        
        
    }
    public static testMethod void leadOrOpportunityUpdateTest6(){
        Test.startTest();
        ld =[select Id from Lead where Phone = '9000000011' Limit 1];
        ld.Budget_Range__c='Upto 1.5L';
        update ld;
        
        IMRec = [Select id,Email__c,Role__c from Showroom_User__C limit 1];
        IMrec.Role__c ='Doowup Presales';
        update IMrec;
        recTypeId = Schema.SObjectType.Setup_Configuration__c.getRecordTypeInfosByDeveloperName().get(GenericConstants.LEAD_OPPORTUNITY_TRANSFER).getRecordTypeId();
        setUp =[select id,Name from Setup_Configuration__c limit 1];
        setUp.Initiator_Email__c ='abc@abc.com';
        setUp.Lead__c =ld.id;
        setUp.Type_Of_Transfer__c ='Doowup Transfer';
        setUp.RecordTypeId = recTypeId;
        setUp.Sales_Manager_Email__c =IMRec.Email__c;
        setUp.Operation_Status__c='Open';
        setUp.Lead_Source__c ='HomeLane';
        
        update setUp;
        LeadAndOpportunityTransferBatch ldTransfer = new LeadAndOpportunityTransferBatch();
        database.executeBatch(ldTransfer);
        Test.stopTest();
        
        
    }
    
    public static testMethod void leadOrOpportunityUpdateTestNewDoowup(){
        Test.startTest();
        ld =[select Id from Lead where Phone = '9000000011' Limit 1];
        ld.Budget_Range__c='1.5L - 4L';
        update ld;
        
        IMRec = [Select id,Email__c,Role__c from Showroom_User__C limit 1];
        IMrec.Role__c ='Doowup Presales';
        update IMrec;
        recTypeId = Schema.SObjectType.Setup_Configuration__c.getRecordTypeInfosByDeveloperName().get(GenericConstants.LEAD_OPPORTUNITY_TRANSFER).getRecordTypeId();
        setUp =[select id,Name from Setup_Configuration__c limit 1];
        setUp.Initiator_Email__c ='abc@abc.com';
        setUp.Lead__c =ld.id;
        setUp.Type_Of_Transfer__c ='Doowup Transfer';
        setUp.RecordTypeId = recTypeId;
        setUp.Sales_Manager_Email__c ='nimbus@homelane.com';
        setUp.Operation_Status__c='Open';
        setUp.Lead_Source__c ='HomeLane';
        
        update setUp;
        LeadAndOpportunityTransferBatch ldTransfer = new LeadAndOpportunityTransferBatch();
        database.executeBatch(ldTransfer);
        Test.stopTest();
        
        
    }
    
    public static testMethod void leadOrOpportunityUpdateTest7(){
        Test.startTest();
        ld =[select Id,Brand__c from Lead where Phone = '9000000011' Limit 1];
        ld.Brand__c='Doowup';
        update ld;
        IMRec = [Select id,Email__c,Role__c from Showroom_User__C limit 1];
        IMrec.Role__c ='Doowup Presales';
        update IMrec;
        
        recTypeId = Schema.SObjectType.Setup_Configuration__c.getRecordTypeInfosByDeveloperName().get(GenericConstants.LEAD_OPPORTUNITY_TRANSFER).getRecordTypeId();
        setUp =[select id,Name from Setup_Configuration__c limit 1];
        setUp.Initiator_Email__c ='abc@abc.com';
        setUp.Lead__c =ld.id;
        setUp.Type_Of_Transfer__c ='Doowup Presales Transfer';
        setUp.RecordTypeId = recTypeId;
        setUp.Sales_Manager_Email__c =IMRec.Email__c;
        setUp.Operation_Status__c='Open';
        
        update setUp;
        LeadAndOpportunityTransferBatch ldTransfer = new LeadAndOpportunityTransferBatch();
        database.executeBatch(ldTransfer);
        Test.stopTest();
        
        
    }
    public static testMethod void leadOrOpportunityUpdateTest8(){
        Test.startTest();
        ld =[select Id,Brand__c from Lead where Phone = '9000000011' Limit 1];
        IMRec = [Select id,Email__c,Role__c from Showroom_User__C limit 1];
        IMRec.Role__c='Inside Sales Agent';
        update IMRec;
        //WTAUser = [select Id,Email from User Limit 1];
        recTypeId = Schema.SObjectType.Setup_Configuration__c.getRecordTypeInfosByDeveloperName().get(GenericConstants.LEAD_OPPORTUNITY_TRANSFER).getRecordTypeId();
        setUp =[select id,Name from Setup_Configuration__c limit 1];
        setUp.Initiator_Email__c ='abc@abc.com';
        setUp.Lead__c =ld.id;
        setUp.Type_Of_Transfer__c ='Inside Sales Transfer';
        setUp.RecordTypeId = recTypeId;
        setUp.Sales_Manager_Email__c = IMRec.Email__c;
        setUp.Operation_Status__c='Open';
        setUp.Lead_Source__c ='HomeLane';
        
        update setUp;
        LeadAndOpportunityTransferBatch ldTransfer = new LeadAndOpportunityTransferBatch();
        database.executeBatch(ldTransfer);
        Test.stopTest();
        
        
    }
    public static testMethod void leadOrOpportunityUpdateTest9(){
        Test.startTest();
        ld =[select Id,Brand__c from Lead where Phone = '9000000000' Limit 1];
        ld.Nimbus_Status__c='Sent to Nimbus';
        update ld;
        IMRec = [Select id,Email__c,Role__c from Showroom_User__C limit 1];
        
        recTypeId = Schema.SObjectType.Setup_Configuration__c.getRecordTypeInfosByDeveloperName().get(GenericConstants.LEAD_OPPORTUNITY_TRANSFER).getRecordTypeId();
        setUp =[select id,Name from Setup_Configuration__c limit 1];
        setUp.Initiator_Email__c ='abc@abc.com';
        setUp.Lead__c =ld.id;
        setUp.Type_Of_Transfer__c ='Nimbus Transfer';
        setUp.RecordTypeId = recTypeId;
        setUp.Sales_Manager_Email__c =IMRec.Email__c;
        setUp.Operation_Status__c='Open';
        
        update setUp;
        LeadAndOpportunityTransferBatch ldTransfer = new LeadAndOpportunityTransferBatch();
        database.executeBatch(ldTransfer);
        Test.stopTest();
        
        
    }
    public static testMethod void leadOrOpportunityUpdateTest10(){
        Test.startTest();
        ld =[select Id,Brand__c from Lead where Phone = '9000000000' Limit 1];
        ld.Brand__c='Doowup';
        update ld;
        IMRec = [Select id,Email__c,Role__c from Showroom_User__C limit 1];
        IMRec.Role__c='Doowup Presales';
        update IMRec;
        
        recTypeId = Schema.SObjectType.Setup_Configuration__c.getRecordTypeInfosByDeveloperName().get(GenericConstants.LEAD_OPPORTUNITY_TRANSFER).getRecordTypeId();
        setUp =[select id,Name from Setup_Configuration__c limit 1];
        setUp.Initiator_Email__c ='abc@abc.com';
        setUp.Lead__c =ld.id;
        setUp.Type_Of_Transfer__c ='Doowup Presales Transfer';
        setUp.RecordTypeId = recTypeId;
        setUp.Sales_Manager_Email__c =IMRec.Email__c;
        setUp.Operation_Status__c='Open';
        
        update setUp;
        LeadAndOpportunityTransferBatch ldTransfer = new LeadAndOpportunityTransferBatch();
        database.executeBatch(ldTransfer);
        Test.stopTest();
        
        
    }
    
     public static testMethod void leadOrOpportunityUpdateTestpresales(){
        Test.startTest();
        ld =[select Id,Brand__c from Lead where Phone = '9000000000' Limit 1];
        ld.Brand__c='Doowup';
        update ld;
        IMRec = [Select id,Email__c,Role__c from Showroom_User__C limit 1];
        IMRec.Role__c='Pre-Sales Freelancer';
        update IMRec;
        
        recTypeId = Schema.SObjectType.Setup_Configuration__c.getRecordTypeInfosByDeveloperName().get(GenericConstants.LEAD_OPPORTUNITY_TRANSFER).getRecordTypeId();
        setUp =[select id,Name from Setup_Configuration__c limit 1];
        setUp.Initiator_Email__c ='abc@abc.com';
        setUp.Lead__c =ld.id;
        setUp.Type_Of_Transfer__c ='Freelancer Transfer';
        setUp.RecordTypeId = recTypeId;
        setUp.Sales_Manager_Email__c =IMRec.Email__c;
        setUp.Operation_Status__c='Open';
        
        update setUp;
        LeadAndOpportunityTransferBatch ldTransfer = new LeadAndOpportunityTransferBatch();
        database.executeBatch(ldTransfer);
        Test.stopTest();
        
        
    }
    
    
    
      public static testMethod void leadOrOpportunityUpdateTestCubico(){
        Test.startTest();
        ld =[select Id from Lead where Phone = '9000000011' Limit 1];
        IMRec = [Select id,Email__c,Role__c from Showroom_User__C limit 1];
        IMrec.Role__c ='Doowup Presales';
        update IMrec;
        recTypeId = Schema.SObjectType.Setup_Configuration__c.getRecordTypeInfosByDeveloperName().get(GenericConstants.LEAD_OPPORTUNITY_TRANSFER).getRecordTypeId();
        setUp =[select id,Name from Setup_Configuration__c limit 1];
        setUp.Initiator_Email__c ='abc@abc.com';
        setUp.Lead__c =ld.id;
        setUp.Type_Of_Transfer__c ='Cubico Transfer';
        setUp.RecordTypeId = recTypeId;
        setUp.Sales_Manager_Email__c =IMRec.Email__c;
        setUp.Operation_Status__c='Open';
        setUp.Lead_Source__c ='HomeLane';
        
        update setUp;
        LeadAndOpportunityTransferBatch ldTransfer = new LeadAndOpportunityTransferBatch();
        database.executeBatch(ldTransfer);
        Test.stopTest();
        
        
    }
    
    
      public static testMethod void leadOrOpportunityUpdateTestNew(){
        Test.startTest();
        ld =[select Id from Lead where Phone = '9000000011' Limit 1];
        IMRec = [Select id,Email__c,Role__c from Showroom_User__C limit 1];
        IMrec.Role__c ='Doowup Presales';
        update IMrec;
        recTypeId = Schema.SObjectType.Setup_Configuration__c.getRecordTypeInfosByDeveloperName().get(GenericConstants.LEAD_OPPORTUNITY_TRANSFER).getRecordTypeId();
        setUp =[select id,Name from Setup_Configuration__c limit 1];
        setUp.Initiator_Email__c ='abcd@abc.com';
        setUp.Lead__c =ld.id;
        setUp.Type_Of_Transfer__c ='Offline Relanded Transfer';
        setUp.RecordTypeId = recTypeId;
        setUp.Sales_Manager_Email__c =IMRec.Email__c;
        setUp.Operation_Status__c='Open';
        setUp.Lead_Source__c ='HomeLane';
        
        update setUp;
        LeadAndOpportunityTransferBatch ldTransfer = new LeadAndOpportunityTransferBatch();
        database.executeBatch(ldTransfer);
        Test.stopTest();
        
        
    }
}