force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Created to map the next step with respect to lead status</description>
    <label>Next Step For Lead Status Mapping</label>
</CustomObject>

force-app/main/default/objects/Whatsapp_Message__c/Whatsapp_Message__c.object-meta.xml
<CustomObject>
    <label>Whatsapp Message</label>
    <nameField>
        <label>Whatsapp Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Whatsapp Message</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Whatsapp_Message__c/fields/Call_Back_Request__c.field-meta.xml
<CustomField>
    <fullName>Call_Back_Request__c</fullName>
    <label>Call Back Request</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inside Business Hours</fullName>
            </value>
            <value>
                <fullName>Outside Business Hours</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Whatsapp_Message__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Whatsapp Message</relationshipLabel>
    <relationshipName>Whatsapp_Message</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Whatsapp_Message__c/fields/Responded__c.field-meta.xml
<CustomField>
    <fullName>Responded__c</fullName>
    <label>Responded?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Whatsapp_Message__c/fields/Responded_Last_Time__c.field-meta.xml
<CustomField>
    <fullName>Responded_Last_Time__c</fullName>
    <label>Responded Last Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Whatsapp_Message__c/fields/Response_Msg__c.field-meta.xml
<CustomField>
    <fullName>Response_Msg__c</fullName>
    <label>Response Msg</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WhatsappCxAnsAPI_Test.cls
@isTest
public class WhatsappCxAnsAPI_Test {
    @isTest static void test() {
        Lead l = new Lead();
        l.FirstName = 'Hamsa';
        l.LastName = 'Raj';
        l.Email = 'HamsaRaj@gmail.com';
        l.Phone = '9000000009';
        l.City = 'Bengaluru';
        l.LeadSource = 'Google Ad';
        l.Status = 'Fresh Lead';
        l.Sub_Status__c = 'New';
        insert l;
        
        Whatsapp_Message__c w = new Whatsapp_Message__c(Name = 'WA - Unable to Contact', Lead__c = l.Id, Responded_Last_Time__c = System.now(), Response_Msg__c = 'Call', Responded__c = 'Yes', Call_Back_Request__c = 'Inside Business Hours');
        insert w;
        Test.startTest();
        String json = '{"mobile_no":"9000000009","response_msg":"call","within_business_hours":"false","leadId":"'+l.Id+'","cx_response":"call"}';
        RestRequest req = new RestRequest();
        req.addHeader('Content-Type','application/json');
        req.requestURI = '/services/apexrest/WhatsappCxAnsAPI';
        req.HTTPMethod = 'POST';
        req.requestBody = Blob.valueOf(json);
        
        RestResponse res = new RestResponse();
        RestContext.Request = req;
        RestContext.Response = res;
        WhatsappCxAnsAPI.leadPush();
        Test.stopTest();
    }
    
     @isTest static void test2() {
        Lead l = new Lead();
        l.FirstName = 'Hamsa';
        l.LastName = 'Raj';
        l.Email = 'HamsaRaj@gmail.com';
        l.Phone = '9000000009';
        l.City = 'Bengaluru';
        l.LeadSource = 'Google Ad';
        l.Status = 'Fresh Lead';
        l.Sub_Status__c = 'New';
        l.Description__c = 'ABC';
        insert l;
        
        Whatsapp_Message__c w = new Whatsapp_Message__c(Name = 'WA - Unable to Contact', Lead__c = l.Id, Responded_Last_Time__c = System.now(), Response_Msg__c = 'Call', Responded__c = 'Yes', Call_Back_Request__c = 'Inside Business Hours');
        insert w;
        
        String json = '{"mobile_no":"9000000009","response_msg":"call","within_business_hours":"true","leadId":"'+l.Id+'","cx_response":"call"}';
        
        Test.startTest();
        RestRequest req = new RestRequest();
        req.addHeader('Content-Type','application/json');
        req.RequestURI = '/services/apexrest/WhatsappCxAnsAPI';
        req.HTTPMethod = 'POST';
        req.requestBody = Blob.valueOf(json);
        
        RestResponse res = new RestResponse();
        RestContext.Request = req;
        RestContext.Response = res;
        WhatsappCxAnsAPI.leadPush();
        Test.stopTest();
    }
    
    @isTest static void test3() {
        Lead l = new Lead();
        l.FirstName = 'Hamsa';
        l.LastName = 'Raj';
        l.Email = 'HamsaRaj@gmail.com';
        l.Phone = '9000000009';
        l.City = 'Bengaluru';
        l.LeadSource = 'Google Ad';
        l.Status = 'Fresh Lead';
        l.Sub_Status__c = 'New';
        insert l;
        
        String json = '{"mobile_no":"9000000008","response_msg":"call","within_business_hours":"true","leadId":"'+l.Id+'","cx_response":"call"}';
        
        Test.startTest();
        RestRequest req = new RestRequest();
        req.addHeader('Content-Type','application/json');
        req.requestURI = '/services/apexrest/WhatsappCxAnsAPI';
        req.HTTPMethod = 'POST';
        req.requestBody = Blob.valueOf(json);
        
        RestResponse res = new RestResponse();
        RestContext.Request = req;
        RestContext.Response = res;
        WhatsappCxAnsAPI.leadPush();
        Test.stopTest();
        }
}