force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Created to map the next step with respect to lead status</description>
    <label>Next Step For Lead Status Mapping</label>
</CustomObject>

force-app/main/default/objects/Setup_Configuration__c/Setup_Configuration__c.object-meta.xml
<CustomObject>
    <label>Setup Configuration</label>
    <nameField>
        <displayFormat>SC -{0000000000}</displayFormat>
        <label>Setup Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setup Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Setup_Configuration__c/fields/Initiator_Email__c.field-meta.xml
<CustomField>
    <fullName>Initiator_Email__c</fullName>
    <label>Initiator Email</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Setup_Configuration__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Setup Configurations</relationshipLabel>
    <relationshipName>Setup_Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Setup_Configuration__c/fields/Operation_Status__c.field-meta.xml
<CustomField>
    <fullName>Operation_Status__c</fullName>
    <label>Operation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Setup_Configuration__c/fields/Showroom_User__c.field-meta.xml
<CustomField>
    <fullName>Showroom_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Showroom User</label>
    <referenceTo>Showroom_User__c</referenceTo>
    <relationshipLabel>Setup Configurations</relationshipLabel>
    <relationshipName>Setup_Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Setup_Configuration__c/fields/Type_Of_Transfer__c.field-meta.xml
<CustomField>
    <fullName>Type_Of_Transfer__c</fullName>
    <label>Type Of Transfer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IM Transfer</fullName>
            </value>
            <value>
                <fullName>Freelancer Transfer</fullName>
            </value>
            <value>
                <fullName>Telecaller Transfer</fullName>
            </value>
            <value>
                <fullName>Nimbus Transfer</fullName>
            </value>
            <value>
                <fullName>Doowup Transfer</fullName>
            </value>
            <value>
                <fullName>Doowup Presales Transfer</fullName>
            </value>
            <value>
                <fullName>Nimbus DL Offline Transfer</fullName>
            </value>
            <value>
                <fullName>Nimbus DL Digital Transfer</fullName>
            </value>
            <value>
                <fullName>Offline Relanded Transfer</fullName>
            </value>
            <value>
                <fullName>IM Classification</fullName>
            </value>
            <value>
                <fullName>Inside Sales Transfer</fullName>
            </value>
            <value>
                <fullName>Nimbus Relanded Transfer</fullName>
            </value>
            <value>
                <fullName>Nimbus Hindi Transfer</fullName>
            </value>
            <value>
                <fullName>Nimbus Telugu Transfer</fullName>
            </value>
            <value>
                <fullName>Cubico Transfer</fullName>
            </value>
            <value>
                <fullName>Nimbus Doowup Offline Transfer</fullName>
            </value>
            <value>
                <fullName>Nimbus HL Missed Call Transfer</fullName>
            </value>
            <value>
                <fullName>Nimbus Doowup Opp Transfer</fullName>
            </value>
            <value>
                <fullName>Globiva Offline RL Transfer</fullName>
            </value>
            <value>
                <fullName>Globiva Offline PB Transfer</fullName>
            </value>
            <value>
                <fullName>Globiva Relanded Transfer</fullName>
            </value>
            <value>
                <fullName>Globiva Feedback Digital Transfer</fullName>
            </value>
            <value>
                <fullName>Globiva Digital North Transfer</fullName>
            </value>
            <value>
                <fullName>Globiva Digital South Transfer</fullName>
            </value>
            <value>
                <fullName>Globiva Digital East Transfer</fullName>
            </value>
            <value>
                <fullName>Globiva Digital West Transfer</fullName>
            </value>
            <value>
                <fullName>Globiva Digital Centre Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Showroom_User__c/Showroom_User__c.object-meta.xml
<CustomObject>
    <label>Showroom User</label>
    <nameField>
        <label>ShowRoom User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Showroom User</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SetUpConfigDeleteBatch_Test.cls
@IsTest
public class SetUpConfigDeleteBatch_Test {
public static Setup_Configuration__c setUp;
    Public static Lead ld;
   
    Public static Showroom_User__C IMRec;
    @TestSetup static void data() {
        //Create Lead Record
        ld = TestData_Factory.CreateFreshLead(true);
        
        IMRec = TestData_factory.createShowroomUser(true);
     Setup_Configuration__c setUp = new  Setup_Configuration__c();
        
        
        
        
        insert setUp;
    }
     public testMethod static void SetUpConfigDeleteBatchTest3(){
         Test.startTest();
       SetUpConfigDeleteBatch  sh1 = new SetUpConfigDeleteBatch();
        
        String sch = '0 0 23 * * ?'; 
        system.schedule('Test Check', sch, sh1); 
        
        Database.executeBatch(new SetUpConfigDeleteBatch());
        test.stopTest();
    }
    public static testMethod void leadOrOpportunityUpdateTest1(){
        Test.startTest();
        ld =[select Id from Lead Limit 1];
        IMRec = [Select id,Email__c from Showroom_User__C limit 1];
        setUp =[select id,Name from Setup_Configuration__c limit 1];
        setUp.Operation_Status__c ='Closed';
        setUp.Lead__c = ld.id;
        setUp.Initiator_Email__c= 'abc@abc.com';
        setUp.Type_Of_Transfer__c ='IM Transfer';
        
        update setUp;
     SetUpConfigDeleteBatch ldTransfer = new SetUpConfigDeleteBatch();
        database.executeBatch(ldTransfer);
        Test.stopTest();
        
        
    }
   
}