force-app/main/default/objects/Lead_Class_Scoring__c/Lead_Class_Scoring__c.object-meta.xml
<CustomObject>
    <label>Lead and IM Class mapping</label>
    <nameField>
        <displayFormat>LM - {0000000}</displayFormat>
        <label>Lead  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead and IM Class mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead_Class_Scoring__c/fields/Budget_Counter__c.field-meta.xml
<CustomField>
    <fullName>Budget_Counter__c</fullName>
    <label>Budget Counter</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead_Class_Scoring__c/fields/Budget_Counter_Limit__c.field-meta.xml
<CustomField>
    <fullName>Budget_Counter_Limit__c</fullName>
    <label>Budget Counter Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead_Class_Scoring__c/fields/Counter_Limit__c.field-meta.xml
<CustomField>
    <fullName>Counter_Limit__c</fullName>
    <label>Counter Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead_Class_Scoring__c/fields/Property_Counter__c.field-meta.xml
<CustomField>
    <fullName>Property_Counter__c</fullName>
    <label>Property Counter</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead_Class_Scoring__c/fields/Property_Counter_Limit__c.field-meta.xml
<CustomField>
    <fullName>Property_Counter_Limit__c</fullName>
    <label>Property Counter Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead_Class_Scoring__c/fields/Purpose_Counter__c.field-meta.xml
<CustomField>
    <fullName>Purpose_Counter__c</fullName>
    <label>Purpose Counter</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead_Class_Scoring__c/fields/Purpose_Counter_Limit__c.field-meta.xml
<CustomField>
    <fullName>Purpose_Counter_Limit__c</fullName>
    <label>Purpose Counter Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead_Class_Scoring__c/fields/Red_Pincode_Counter__c.field-meta.xml
<CustomField>
    <fullName>Red_Pincode_Counter__c</fullName>
    <label>Red Pincode Counter</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead_Class_Scoring__c/fields/Red_Pincode_Counter_Limit__c.field-meta.xml
<CustomField>
    <fullName>Red_Pincode_Counter_Limit__c</fullName>
    <label>Red Pincode Counter Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead_Class_Scoring__c/fields/Total_Limit__c.field-meta.xml
<CustomField>
    <fullName>Total_Limit__c</fullName>
    <label>Total Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/RoutingHLCountResetBatch.cls
global class RoutingHLCountResetBatch  implements Database.Batchable<sObject>,Schedulable
{
    Public Set<Id> setOfIds = new Set<Id>();
    Id recTypeId = Schema.SObjectType.Lead_Class_Scoring__c.getRecordTypeInfosByName().get('Routing HL Leads').getRecordTypeId();
    // Constructor to excecute only set of records in the Batch.
    
    global RoutingHLCountResetBatch(){}
    
    global void execute(SchedulableContext SC) 
    {
        database.executebatch(new RoutingHLCountResetBatch(),1);
    }
    
    global Database.QueryLocator start(Database.BatchableContext bc) 
    {
        String queryString = 'Select id,Budget_Counter__c,Budget_Counter_Limit__c, Purpose_Counter__c, Purpose_Counter_Limit__c,Property_Counter__c,Property_Counter_Limit__c,Red_Pincode_Counter__c,Red_Pincode_Counter_Limit__c,Counter_Limit__c,Total_Limit__c from Lead_Class_Scoring__c where RecordTypeId =:recTypeId ';
          
        return Database.getQueryLocator(queryString);
    }
    
    global void execute(Database.BatchableContext bc, List<Lead_Class_Scoring__c> listOfLeadClass) 
    { 
        List<Lead_Class_Scoring__c > updateCounter = new List<Lead_Class_Scoring__c >();
        try
        {
            if(!listOfLeadClass.isEmpty())
            {                
                for(Lead_Class_Scoring__c ldClass : listOfLeadClass)
                {                    
                    ldClass.Budget_Counter__c = 0;
                    ldClass.Purpose_Counter__c =0;                    
                    ldClass.Property_Counter__c=0;
                    ldClass.Red_Pincode_Counter__c=0;
                    
                    updateCounter.add(ldClass);                    
                }
                
                if(!updateCounter.isEmpty())
                {
                    update updateCounter;
                }
            }
        }
        catch(Exception e)
        {
            system.debug('Exception : '+e.getStackTraceString());
            system.debug('Exception message: '+e.getMessage());
            Logger.log('Exception','RoutingHLCountResetBatch Class','execute method',e.getMessage(),e.getStackTraceString(),null);
        }
    }   
    
    global void finish(Database.BatchableContext bc)
    { 
        System.debug('finish method');   
    }

}