force-app/main/default/objects/Lead_Class_Scoring__c/Lead_Class_Scoring__c.object-meta.xml
<CustomObject>
    <label>Lead and IM Class mapping</label>
    <nameField>
        <displayFormat>LM - {0000000}</displayFormat>
        <label>Lead  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead and IM Class mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead_Class_Scoring__c/fields/Budget_Counter__c.field-meta.xml
<CustomField>
    <fullName>Budget_Counter__c</fullName>
    <label>Budget Counter</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead_Class_Scoring__c/fields/Budget_Counter_Limit__c.field-meta.xml
<CustomField>
    <fullName>Budget_Counter_Limit__c</fullName>
    <label>Budget Counter Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead_Class_Scoring__c/fields/Counter_Limit__c.field-meta.xml
<CustomField>
    <fullName>Counter_Limit__c</fullName>
    <label>Counter Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead_Class_Scoring__c/fields/Property_Counter__c.field-meta.xml
<CustomField>
    <fullName>Property_Counter__c</fullName>
    <label>Property Counter</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead_Class_Scoring__c/fields/Property_Counter_Limit__c.field-meta.xml
<CustomField>
    <fullName>Property_Counter_Limit__c</fullName>
    <label>Property Counter Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead_Class_Scoring__c/fields/Purpose_Counter__c.field-meta.xml
<CustomField>
    <fullName>Purpose_Counter__c</fullName>
    <label>Purpose Counter</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead_Class_Scoring__c/fields/Purpose_Counter_Limit__c.field-meta.xml
<CustomField>
    <fullName>Purpose_Counter_Limit__c</fullName>
    <label>Purpose Counter Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead_Class_Scoring__c/fields/Total_Limit__c.field-meta.xml
<CustomField>
    <fullName>Total_Limit__c</fullName>
    <label>Total Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/Showroom_User__c.object-meta.xml
<CustomObject>
    <label>Showroom User</label>
    <nameField>
        <label>ShowRoom User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Showroom User</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Showroom_User__c/fields/Backlogs__c.field-meta.xml
<CustomField>
    <fullName>Backlogs__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Backlogs</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/Daily_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Daily_Assignment__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Daily Assignment</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/Daily_Assignment_Limit__c.field-meta.xml
<CustomField>
    <fullName>Daily_Assignment_Limit__c</fullName>
    <defaultValue>7</defaultValue>
    <label>Daily Assignment Limit</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/IronMan__c.field-meta.xml
<CustomField>
    <fullName>IronMan__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IronMan</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/Monthly_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Assignment__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Monthly Assignment</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/Monthly_Assignment_Limit__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Assignment_Limit__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Monthly Assignment Limit</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/Threashold__c.field-meta.xml
<CustomField>
    <fullName>Threashold__c</fullName>
    <defaultValue>18</defaultValue>
    <label>Threashold</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territory__c/Territory__c.object-meta.xml
<CustomObject>
    <label>Territory</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory__c/fields/Assignment__c.field-meta.xml
<CustomField>
    <fullName>Assignment__c</fullName>
    <formula>IF( ISPICKVAL(City__c, &apos;Outskirts&apos;), Ironman__r.Outskirts_Assignment__c , Ironman__r.Daily_Assignment__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Assignment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territory__c/fields/Cluster__c.field-meta.xml
<CustomField>
    <fullName>Cluster__c</fullName>
    <label>Cluster</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BLR_GOP_1</fullName>
            </value>
            <value>
                <fullName>Test1</fullName>
            </value>
            <value>
                <fullName>Test2</fullName>
            </value>
            <value>
                <fullName>BLR_KAN_6</fullName>
            </value>
            <value>
                <fullName>BLR_HEB_5</fullName>
            </value>
            <value>
                <fullName>BLR_MUS_4</fullName>
            </value>
            <value>
                <fullName>BLR_WHI_3</fullName>
            </value>
            <value>
                <fullName>BLR_HSR_2</fullName>
            </value>
            <value>
                <fullName>CBE_ PLZ_1</fullName>
            </value>
            <value>
                <fullName>HYD_SHG_1</fullName>
            </value>
            <value>
                <fullName>MUM_THN_2</fullName>
            </value>
            <value>
                <fullName>HYD_BAN_2</fullName>
            </value>
            <value>
                <fullName>KOL_MAN_1</fullName>
            </value>
            <value>
                <fullName>CHE_CTY_2</fullName>
            </value>
            <value>
                <fullName>CHE_ OMR_1</fullName>
            </value>
            <value>
                <fullName>NCR_NOI_3</fullName>
            </value>
            <value>
                <fullName>NCR_GUR_1</fullName>
            </value>
            <value>
                <fullName>NCR_KRN_2</fullName>
            </value>
            <value>
                <fullName>PUN_BAN_1</fullName>
            </value>
            <value>
                <fullName>MUM_GOR_1</fullName>
            </value>
            <value>
                <fullName>BLR_BSR_7</fullName>
            </value>
            <value>
                <fullName>VIZ_SQRLT_1</fullName>
            </value>
            <value>
                <fullName>MYS_SQRLT_1</fullName>
            </value>
            <value>
                <fullName>KOL_CHI_2</fullName>
            </value>
            <value>
                <fullName>LKO_SQRLT_1</fullName>
            </value>
            <value>
                <fullName>PUN_VIM_2</fullName>
            </value>
            <value>
                <fullName>BAN_JPN_6</fullName>
            </value>
            <value>
                <fullName>SRT_SQRLT_1</fullName>
            </value>
            <value>
                <fullName>CHE_SQRLT_1</fullName>
            </value>
            <value>
                <fullName>CHE_ GST_3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Territory__c/fields/Cluster_Brand__c.field-meta.xml
<CustomField>
    <fullName>Cluster_Brand__c</fullName>
    <label>Cluster Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Homelane</fullName>
                <default>true</default>
                <label>Homelane</label>
            </value>
            <value>
                <fullName>Doow up</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Territory__c/fields/Ironman__c.field-meta.xml
<CustomField>
    <fullName>Ironman__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Ironman</label>
    <referenceTo>Showroom_User__c</referenceTo>
    <relationshipLabel>Territories</relationshipLabel>
    <relationshipName>Territories</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Territory__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <description>IF(OR(Ironman__r.Backlogs_Inactivity__c =True, Ironman__r.IsActive__c =False,Ironman__r.Reached_Daily_Limit__c = True,Ironman__r.Reached_Monthly_Limit__c = True),false,true)</description>
    <formula>IF ( ISPICKVAL(City__c, &apos;Outskirts&apos;),
IF(OR(Ironman__r.IsActive__c =False, Ironman__r.Reached_Outskirts_Monthly_Limit__c=true, Ironman__r.Reached_Outskirts_Limit__c =True ),false,true),

IF(OR(Ironman__r.Backlogs_Inactivity__c =True, Ironman__r.IsActive__c =False,Ironman__r.Reached_Daily_Limit__c = True,Ironman__r.Reached_Monthly_Limit__c = True),false,true))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Territory__c/fields/Monthly_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Assignment__c</fullName>
    <formula>If( ISPICKVAL( City__c , &apos;Outskirts&apos;), Ironman__r.Outskirts_Monthly_Assignment__c , Ironman__r.Monthly_Assignment__c  )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Monthly Assignment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LeadTriggerDoowupHandler_Test.cls
@IsTest
public class LeadTriggerDoowupHandler_Test {
    Public static Lead ld;
    public static Lead_Class_Scoring__c  lcs;
    
    @TestSetup static void data() { 
        Showroom_User__c objShowroom2= TestData_Factory.createShowroomUser(false);
        objShowroom2.Email__c = 'TestSHowRoomasdUSer@test.com';
        objShowroom2.Threashold__c = 10;
        objShowroom2.Backlogs__c = 2;
        objShowroom2.Daily_Assignment__c = 4;
        objShowroom2.Daily_Assignment_Limit__c = 10;
        objShowroom2.IsActive__c = true;
        objShowroom2.Monthly_Assignment__c = 0;
        objShowroom2.Monthly_Assignment_Limit__c = 100;
        insert objShowroom2;
        
         Showroom_User__c objShowroom3= TestData_Factory.createShowroomUser(false);
        objShowroom3.Email__c = 'doowuptransfer@homelane.com';
        
        insert objShowroom3;
        
        Territory__c objTerr1 = TestData_Factory.createTerritory('Area b',ObjShowroom2.id,'Bengaluru','Cluster A','560103',False);
        objTerr1.Lat_Long__Latitude__s = 25.0936477440000;
        objTerr1.Lat_Long__Longitude__s =  88.7849897840000;
        objTerr1.Cluster_Brand__c ='Doow up';
        //objTerr1.Ironman__c
        Insert objTerr1;  
        
        lcs = new Lead_Class_Scoring__c();
        lcs.Budget_Counter__c = 0;
        lcs.Budget_Counter_Limit__c=25;
        lcs.Counter_Limit__c=0;
        lcs.Property_Counter__c=0;
        lcs.Property_Counter_Limit__c=25;
        lcs.Purpose_Counter__c=0;
        lcs.Purpose_Counter_Limit__c=25;
        lcs.Total_Limit__c=100;
        RecordType recType1= [SELECT Id FROM RecordType WHERE Name='Routing HL Leads' limit 1];
        lcs.RecordTypeId =recType1.id;
        insert lcs;
        
        
    }
    
    public testMethod static void LeadTriggerDoowupTest1() {
        Test.StartTest();
        id recTypeId  =Schema.SObjectType.Lead_Class_Scoring__c.getRecordTypeInfosByName().get('Routing HL Leads').getRecordTypeId();
        ld = TestData_Factory.CreateFreshLead(false);
        ld.Property_Config__c ='1 BHK';
        ld.leadSource ='Website';
        ld.PostalCode ='560103';
        ld.Brand__c ='HomeLane';
        ld.Sub_Status__c='Unverified';
        insert ld;
       Showroom_User__c sh = [select id,Email__c from Showroom_User__c where Email__c ='doowuptransfer@homelane.com' limit 1];
       
        list<Territory__c > lst = [Select id,Name,Cluster__C,Assignment__c,Lat_Long__Latitude__s,Lat_Long__Longitude__s,IronMan__c,Is_Active__c,Cluster_Brand__c from Territory__c];
        lcs =[Select id,Budget_Counter__c,Budget_Counter_Limit__c,Purpose_Counter__c,Purpose_Counter_Limit__c,Property_Counter__c,Property_Counter_Limit__c,Counter_Limit__c,	Total_Limit__c
              from Lead_Class_Scoring__c 
              
              limit 1];
        
        Test.StopTest();
        
    } 
    
public testMethod static void LeadTriggerDoowupTest2() {
        Test.StartTest();
        id recTypeId  =Schema.SObjectType.Lead_Class_Scoring__c.getRecordTypeInfosByName().get('Routing HL Leads').getRecordTypeId();
        ld = TestData_Factory.CreateFreshLead(false);
        ld.Budget_Range__c ='Upto 1.5L';
        ld.leadSource ='Website';
        ld.PostalCode ='560103';
        ld.Brand__c ='HomeLane';
        ld.Sub_Status__c='Unverified';
        insert ld;
        //Showroom_User__c sh = [select id,Email__c from Showroom_User__c where Email__c ='doowuptransfer@homelane.com' limit 1];
        list<Territory__c > lst = [Select id,Name,Cluster__C,Assignment__c,Lat_Long__Latitude__s,Lat_Long__Longitude__s,IronMan__c,Is_Active__c,Cluster_Brand__c from Territory__c];
        lcs =[Select id,Budget_Counter__c,Budget_Counter_Limit__c,Purpose_Counter__c,Purpose_Counter_Limit__c,Property_Counter__c,Property_Counter_Limit__c,Counter_Limit__c,	Total_Limit__c
              from Lead_Class_Scoring__c 
              
              limit 1];
        
        Test.StopTest();
        
    } 
    public testMethod static void LeadTriggerDoowupTest3() {
        Test.StartTest();
        id recTypeId  =Schema.SObjectType.Lead_Class_Scoring__c.getRecordTypeInfosByName().get('Routing HL Leads').getRecordTypeId();
        ld = TestData_Factory.CreateFreshLead(false);
        ld.Property_Status__c ='Rent Out';
        ld.leadSource ='Website';
        ld.PostalCode ='560103';
        ld.Brand__c ='HomeLane';
        ld.Sub_Status__c='Unverified';
        insert ld;

        list<Territory__c > lst = [Select id,Name,Cluster__C,Assignment__c,Lat_Long__Latitude__s,Lat_Long__Longitude__s,IronMan__c,Is_Active__c,Cluster_Brand__c from Territory__c];
        lcs =[Select id,Budget_Counter__c,Budget_Counter_Limit__c,Purpose_Counter__c,Purpose_Counter_Limit__c,Property_Counter__c,Property_Counter_Limit__c,Counter_Limit__c,	Total_Limit__c
              from Lead_Class_Scoring__c 
              
              limit 1];
        
        Test.StopTest();
        
    } 
        
}