force-app/main/default/objects/SC_Item__c/SC_Item__c.object-meta.xml
<CustomObject>
    <label>SC Item</label>
    <nameField>
        <displayFormat>SCIN-{00000}</displayFormat>
        <label>SC Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SC Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SC_Item__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SC_Item__c/fields/Response_Type__c.field-meta.xml
<CustomField>
    <fullName>Response_Type__c</fullName>
    <label>Response Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PickList</fullName>
            </value>
            <value>
                <fullName>Multi PickList</fullName>
            </value>
            <value>
                <fullName>Check Box</fullName>
            </value>
            <value>
                <fullName>Open Text</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SC_Response__c/SC_Response__c.object-meta.xml
<CustomObject>
    <label>SC Response</label>
    <nameField>
        <displayFormat>SCRN-{0000}</displayFormat>
        <label>SC Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SC Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SC_Response__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <referenceTo>SC_Item__c</referenceTo>
    <relationshipLabel>SC Responses</relationshipLabel>
    <relationshipName>SC_Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SC_Response__c/fields/Required_for_Next_Stage__c.field-meta.xml
<CustomField>
    <fullName>Required_for_Next_Stage__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Required for Next Stage</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SC_Section__c/SC_Section__c.object-meta.xml
<CustomObject>
    <label>SC Section</label>
    <nameField>
        <displayFormat>SEC-{0000}</displayFormat>
        <label>SC Section Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SC Sections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SC_Section__c/fields/Opportunity_Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Sub_Status__c</fullName>
    <label>Opportunity Sub Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IQ Follow Up - Unable To Contact</fullName>
            </value>
            <value>
                <fullName>IQ Follow Up - Follow Up Later</fullName>
            </value>
            <value>
                <fullName>IQ Follow Up - Property on Hold</fullName>
            </value>
            <value>
                <fullName>Customer Needs More Time</fullName>
            </value>
            <value>
                <fullName>Customer Not Free To Talk</fullName>
            </value>
            <value>
                <fullName>Site Measurement Proposed</fullName>
            </value>
            <value>
                <fullName>Site Measurement Meeting Confirmed</fullName>
            </value>
            <value>
                <fullName>3D Design &amp; Quote Reviewed by Buddy</fullName>
            </value>
            <value>
                <fullName>3D Design &amp; Quote Sent</fullName>
            </value>
            <value>
                <fullName>Design Presentation Proposed</fullName>
            </value>
            <value>
                <fullName>Design Presentation Confirmed</fullName>
            </value>
            <value>
                <fullName>Design Presentation Completed</fullName>
            </value>
            <value>
                <fullName>Production Drawings &amp; Quote Review Complete</fullName>
            </value>
            <value>
                <fullName>Production Drawings Sent</fullName>
            </value>
            <value>
                <fullName>Project Kick-off Proposed</fullName>
            </value>
            <value>
                <fullName>Project Kick-off Meeting Confirmed</fullName>
            </value>
            <value>
                <fullName>Project Kick-off Completed</fullName>
            </value>
            <value>
                <fullName>Drawings &amp; Quote Approved</fullName>
            </value>
            <value>
                <fullName>Production Folder shared with factory for Review</fullName>
            </value>
            <value>
                <fullName>Drawings approved by factory</fullName>
            </value>
            <value>
                <fullName>Final Drawings, Quote &amp; Works Contract Sent</fullName>
            </value>
            <value>
                <fullName>Final Drawings, Quote &amp; Works Contract Approved</fullName>
            </value>
            <value>
                <fullName>40% payment collected</fullName>
            </value>
            <value>
                <fullName>Project sent to production</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SC_Section__c/fields/Parent_Section__c.field-meta.xml
<CustomField>
    <fullName>Parent_Section__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Section</label>
    <referenceTo>SC_Section__c</referenceTo>
    <relationshipLabel>SC Sections</relationshipLabel>
    <relationshipName>SC_Sections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SC_Section__c/fields/Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Record_Type__c</fullName>
    <label>Record Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Printer</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Record Type D1</fullName>
            </value>
            <value>
                <fullName>Record Type D2</fullName>
            </value>
            <value>
                <fullName>Record Type D3</fullName>
            </value>
            <value>
                <fullName>Record Type D4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SC_Section__c/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <label>Section</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SC_Section_Item__c/SC_Section_Item__c.object-meta.xml
<CustomObject>
    <label>SC Section Item</label>
    <nameField>
        <displayFormat>SCSI-{0000}</displayFormat>
        <label>SC Section Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SC Section Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SC_Section_Item__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Item</label>
    <referenceTo>SC_Item__c</referenceTo>
    <relationshipLabel>SC Section Items</relationshipLabel>
    <relationshipName>SC_Section_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SC_Section_Item__c/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Section</label>
    <referenceTo>SC_Section__c</referenceTo>
    <relationshipLabel>SC Section Items</relationshipLabel>
    <relationshipName>SC_Section_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SC_User_Response__c/SC_User_Response__c.object-meta.xml
<CustomObject>
    <label>SC User Response</label>
    <nameField>
        <displayFormat>SCUR-{0000}</displayFormat>
        <label>SC User Response Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SC User Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SC_User_Response__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Item</label>
    <referenceTo>SC_Item__c</referenceTo>
    <relationshipLabel>SC User Responses</relationshipLabel>
    <relationshipName>SC_User_Responses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SC_User_Response__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>SC User Responses</relationshipLabel>
    <relationshipName>SC_User_Responses1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SC_User_Response__c/fields/Response_Score__c.field-meta.xml
<CustomField>
    <fullName>Response_Score__c</fullName>
    <label>Response Score</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SC_User_Response__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial Quote Rejected - Unable To Contact</fullName>
            </value>
            <value>
                <fullName>Initial Quote Rejected - Follow Up Later</fullName>
            </value>
            <value>
                <fullName>Initial Quote Rejected - Property on Hold</fullName>
            </value>
            <value>
                <fullName>IQ Follow Up - Unable To Contact</fullName>
            </value>
            <value>
                <fullName>IQ Follow Up - Follow Up Later</fullName>
            </value>
            <value>
                <fullName>IQ Follow Up - Property on Hold</fullName>
            </value>
            <value>
                <fullName>Customer Needs More Time</fullName>
            </value>
            <value>
                <fullName>Customer Not Free To Talk</fullName>
            </value>
            <value>
                <fullName>Initial Quote Approved</fullName>
            </value>
            <value>
                <fullName>Initial Quote Rejected</fullName>
            </value>
            <value>
                <fullName>Site Measurement Proposed</fullName>
            </value>
            <value>
                <fullName>Site Measurement Meeting Confirmed</fullName>
            </value>
            <value>
                <fullName>Site Measurement Completed</fullName>
            </value>
            <value>
                <fullName>Site Measurements Uploaded</fullName>
            </value>
            <value>
                <fullName>3D Design &amp; Quote Uploaded</fullName>
            </value>
            <value>
                <fullName>3D Design &amp; Quote Reviewed by Buddy</fullName>
            </value>
            <value>
                <fullName>Site Measurement Rescheduled</fullName>
            </value>
            <value>
                <fullName>Site Measurement Cancelled</fullName>
            </value>
            <value>
                <fullName>3D Design &amp; Quote Sent</fullName>
            </value>
            <value>
                <fullName>Design Presentation Proposed</fullName>
            </value>
            <value>
                <fullName>Design Presentation Confirmed</fullName>
            </value>
            <value>
                <fullName>Design Presentation Completed</fullName>
            </value>
            <value>
                <fullName>Final 3D Design &amp; Quote Sent</fullName>
            </value>
            <value>
                <fullName>3D Design &amp; Quote Approved</fullName>
            </value>
            <value>
                <fullName>3D Design &amp; Quote Rejected</fullName>
            </value>
            <value>
                <fullName>Production Drawings Uploaded</fullName>
            </value>
            <value>
                <fullName>Production Drawings &amp; Quote Review Complete</fullName>
            </value>
            <value>
                <fullName>Production Drawings Sent</fullName>
            </value>
            <value>
                <fullName>Project Kick-off Proposed</fullName>
            </value>
            <value>
                <fullName>Project Kick-off Meeting Confirmed</fullName>
            </value>
            <value>
                <fullName>D1 Initiated</fullName>
                <isActive>false</isActive>
                <label>D1 Initiated</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SC_User_Response__c/fields/User_Response__c.field-meta.xml
<CustomField>
    <fullName>User_Response__c</fullName>
    <label>User Response</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/SC_MI_TestHandler.cls
public class SC_MI_TestHandler {
   public static SC_Section__c insertSection(String sectionName,String Stage,Integer Order,Id parentSection){
        return new SC_Section__c(Section__c           = sectionName,
                                 Opportunity_Sub_Status__c = Stage,
                                 Order__c             = Order,
                                  Parent_Section__c    = parentSection);
    }    
    public static SC_Item__c insertItem(String itemName,Boolean isActive,String responseType,String recordType){
        return new SC_Item__c( Item__c           = itemName,
                               Is_Active__c      = isActive,
                               Record_Type__c    = recordType, 
                               Response_Type__c  = responseType);    
    }
    public static SC_Response__c insertResponse(String answer,Id item,Integer score,Boolean isActive,Boolean requiredForNextStage){
        return new SC_Response__c( Answer__c                 = answer,
                                   Item__c                   = item,
                                  Score__c                  = score,
                                   Is_Active__c              = isActive,
                                  Required_for_Next_Stage__c= requiredForNextStage);
    }
    public static SC_User_Response__c insertUsrResponse(Id item,String response,String stage,Id oppId,Integer responseScore){
        return new SC_User_Response__c( Item__c           = item,
                                       User_Response__c  = response,
                                       Stage__c          = stage,
                                       Opportunity__c    = oppId,
                                       Response_Score__c  = responseScore);
    }  
    public static SC_Section_Item__c insertSectionItem(Id Item,Id Section,Integer Order){
        return new SC_Section_Item__c( Item__c      = item,
                                       Section__c  = Section,
                                       Order__c    = Order);
    }
    public static Opportunity insertOpportunity(String Name,Date closedDate,String StageName,Integer Amount,Date ForecastDate){
    

    
        Schema.DescribeSObjectResult cfrSchema = Schema.SObjectType.Opportunity; 
        Map<String,Schema.RecordTypeInfo> OpportunityRecordTypeInfo = cfrSchema.getRecordTypeInfosByName(); 
        Id printerId = OpportunityRecordTypeInfo.get('Record Type D1').getRecordTypeId();
     //   System.debug('opp'+printerId);
      RecordType recType1=[SELECT Id FROM RecordType WHERE Name='Business Account'];
        Account acc = new Account();
        acc.Name = 'Test Account';
        acc.recordTypeId=recType1.Id;
      //  acc.PersonEmail='John@gmail.com';
        insert acc;
        Contact con = new Contact();
        con.LastName = 'Test contact';
        con.AccountId = acc.Id;
        insert con;
        return new Opportunity(Name       = Name,
                               CloseDate  = closedDate,
                               
                               Amount     = Amount,
                               stageName='D1 Initiated',
                               recordTypeId =printerId  ,
                               NextStep = 'test step',
                               AccountId = acc.Id
                              
                              );
    }
    public static void insertIsTriggerExecute(){
        SC_isTriggerExecute__c isTriggerEx = new SC_isTriggerExecute__c();
        isTriggerEx.name = 'Sales Coach Trigger on Opportunity';
        isTriggerEx.isTriggerExecute__c = TRUE;
        insert isTriggerEx;
    }
    public Static void insertCustomDate(){
        SC_OpportunityCustDate__c setting = new SC_OpportunityCustDate__c();
        setting.SC_StartDate__c= System.Today()-1;
        setting.Name = 'StartDate';
        insert setting;
        
        

    }
}