force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <label>Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Showroom_User__c.field-meta.xml
<CustomField>
    <fullName>Showroom_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Showroom User</label>
    <referenceTo>Showroom_User__c</referenceTo>
    <relationshipLabel>Log</relationshipLabel>
    <relationshipName>Log</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master__c/Master__c.object-meta.xml
<CustomObject>
    <description>This is master object.</description>
    <label>Master</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If the Showroom is active the isActive then check it else Uncheck</description>
    <label>IsActive ShowRoom</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/Showroom_User__c.object-meta.xml
<CustomObject>
    <label>Showroom User</label>
    <nameField>
        <label>ShowRoom User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Showroom User</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Showroom_User__c/fields/Daily_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Daily_Assignment__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Daily Assignment</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/IronMan__c.field-meta.xml
<CustomField>
    <fullName>IronMan__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IronMan</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/Weekly_Off_Days__c.field-meta.xml
<CustomField>
    <fullName>Weekly_Off_Days__c</fullName>
    <label>Weekly Off Days</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sunday</fullName>
            </value>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Territory__c/Territory__c.object-meta.xml
<CustomObject>
    <label>Territory</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory__c/fields/Assignment__c.field-meta.xml
<CustomField>
    <fullName>Assignment__c</fullName>
    <formula>IF( ISPICKVAL(City__c, &apos;Outskirts&apos;), Ironman__r.Outskirts_Assignment__c , Ironman__r.Daily_Assignment__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Assignment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territory__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bengaluru</fullName>
            </value>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>Kolkata</fullName>
            </value>
            <value>
                <fullName>Coimbatore</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Noida</fullName>
            </value>
            <value>
                <fullName>Gurgaon</fullName>
            </value>
            <value>
                <fullName>New Delhi</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
            <value>
                <fullName>Thane</fullName>
            </value>
            <value>
                <fullName>Visakhapatnam</fullName>
            </value>
            <value>
                <fullName>Mysore</fullName>
            </value>
            <value>
                <fullName>Lucknow</fullName>
            </value>
            <value>
                <fullName>Indore</fullName>
            </value>
            <value>
                <fullName>Mangalore</fullName>
            </value>
            <value>
                <fullName>Surat</fullName>
            </value>
            <value>
                <fullName>Ghaziabad</fullName>
            </value>
            <value>
                <fullName>Ahmedabad</fullName>
            </value>
            <value>
                <fullName>Ranchi</fullName>
            </value>
            <value>
                <fullName>Faridabad</fullName>
            </value>
            <value>
                <fullName>Kochi</fullName>
            </value>
            <value>
                <fullName>Bhubaneswar</fullName>
            </value>
            <value>
                <fullName>Madurai</fullName>
            </value>
            <value>
                <fullName>Jaipur</fullName>
            </value>
            <value>
                <fullName>Vijayawada</fullName>
            </value>
            <value>
                <fullName>Salem</fullName>
            </value>
            <value>
                <fullName>Nagpur</fullName>
            </value>
            <value>
                <fullName>Trichy</fullName>
            </value>
            <value>
                <fullName>Outskirts</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Territory__c/fields/Cluster__c.field-meta.xml
<CustomField>
    <fullName>Cluster__c</fullName>
    <label>Cluster</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BLR_GOP_1</fullName>
            </value>
            <value>
                <fullName>Test1</fullName>
            </value>
            <value>
                <fullName>Test2</fullName>
            </value>
            <value>
                <fullName>BLR_KAN_6</fullName>
            </value>
            <value>
                <fullName>BLR_HEB_5</fullName>
            </value>
            <value>
                <fullName>BLR_MUS_4</fullName>
            </value>
            <value>
                <fullName>BLR_WHI_3</fullName>
            </value>
            <value>
                <fullName>BLR_HSR_2</fullName>
            </value>
            <value>
                <fullName>CBE_ PLZ_1</fullName>
            </value>
            <value>
                <fullName>HYD_SHG_1</fullName>
            </value>
            <value>
                <fullName>MUM_THN_2</fullName>
            </value>
            <value>
                <fullName>HYD_BAN_2</fullName>
            </value>
            <value>
                <fullName>KOL_MAN_1</fullName>
            </value>
            <value>
                <fullName>CHE_CTY_2</fullName>
            </value>
            <value>
                <fullName>CHE_ OMR_1</fullName>
            </value>
            <value>
                <fullName>NCR_NOI_3</fullName>
            </value>
            <value>
                <fullName>NCR_GUR_1</fullName>
            </value>
            <value>
                <fullName>NCR_KRN_2</fullName>
            </value>
            <value>
                <fullName>PUN_BAN_1</fullName>
            </value>
            <value>
                <fullName>MUM_GOR_1</fullName>
            </value>
            <value>
                <fullName>BLR_BSR_7</fullName>
            </value>
            <value>
                <fullName>VIZ_SQRLT_1</fullName>
            </value>
            <value>
                <fullName>MYS_SQRLT_1</fullName>
            </value>
            <value>
                <fullName>KOL_CHI_2</fullName>
            </value>
            <value>
                <fullName>LKO_SQRLT_1</fullName>
            </value>
            <value>
                <fullName>PUN_VIM_2</fullName>
            </value>
            <value>
                <fullName>BAN_JPN_6</fullName>
            </value>
            <value>
                <fullName>SRT_SQRLT_1</fullName>
            </value>
            <value>
                <fullName>CHE_SQRLT_1</fullName>
            </value>
            <value>
                <fullName>CHE_ GST_3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Territory__c/fields/Cluster_Brand__c.field-meta.xml
<CustomField>
    <fullName>Cluster_Brand__c</fullName>
    <label>Cluster Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Homelane</fullName>
                <default>true</default>
                <label>Homelane</label>
            </value>
            <value>
                <fullName>Doow up</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Territory__c/fields/Inside_Sales_Cluster__c.field-meta.xml
<CustomField>
    <fullName>Inside_Sales_Cluster__c</fullName>
    <label>Inside Sales Cluster</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>INSALES_DOUP_BLR_1</fullName>
            </value>
            <value>
                <fullName>INSALES_BHU_1</fullName>
            </value>
            <value>
                <fullName>INSALES_ROTN_1</fullName>
            </value>
            <value>
                <fullName>INSALES_MYS_1</fullName>
            </value>
            <value>
                <fullName>INSALES_VIJ_VIZ</fullName>
            </value>
            <value>
                <fullName>INSALES_PUN_1</fullName>
            </value>
            <value>
                <fullName>INSALES_AHM_1</fullName>
            </value>
            <value>
                <fullName>INSALES_SUR_1</fullName>
            </value>
            <value>
                <fullName>INSALES_NOI</fullName>
            </value>
            <value>
                <fullName>InSales_Cluster_1_Mum</fullName>
            </value>
            <value>
                <fullName>InSales_Cluster_2_Viz</fullName>
            </value>
            <value>
                <fullName>InSales_Cluster_3_Ben</fullName>
            </value>
            <value>
                <fullName>InSales_Cluster_4_Ben_Che</fullName>
            </value>
            <value>
                <fullName>InSales_Cluster_5_Bhu</fullName>
            </value>
            <value>
                <fullName>InSales_Cluster_5_Mum/Bhu</fullName>
            </value>
            <value>
                <fullName>INSales_Cluster 6_Mum</fullName>
            </value>
            <value>
                <fullName>INSales_Cluster 1_BenMys</fullName>
            </value>
            <value>
                <fullName>INSales_Cluster 3_HydViz</fullName>
            </value>
            <value>
                <fullName>INSales_Cluster 5_KolBhu</fullName>
            </value>
            <value>
                <fullName>INSales_Cluster 10_Nag</fullName>
            </value>
            <value>
                <fullName>INSales_Cluster 7_Pun</fullName>
            </value>
            <value>
                <fullName>INSales_Cluster 8_Ahm</fullName>
            </value>
            <value>
                <fullName>INSales_Cluster 9_Koc</fullName>
            </value>
            <value>
                <fullName>DWP_Insales_Hyd</fullName>
            </value>
            <value>
                <fullName>DWP_Insales_Mys</fullName>
            </value>
            <value>
                <fullName>INSales_Cluster 2_CheRotn</fullName>
            </value>
            <value>
                <fullName>INSales_Cluster 4_NcrJaiLuc</fullName>
            </value>
            <value>
                <fullName>InSales_South</fullName>
            </value>
            <value>
                <fullName>InSales_North</fullName>
            </value>
            <value>
                <fullName>InSales_East</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Territory__c/fields/Ironman__c.field-meta.xml
<CustomField>
    <fullName>Ironman__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Ironman</label>
    <referenceTo>Showroom_User__c</referenceTo>
    <relationshipLabel>Territories</relationshipLabel>
    <relationshipName>Territories</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Territory__c/fields/Pincode__c.field-meta.xml
<CustomField>
    <fullName>Pincode__c</fullName>
    <label>Pincode</label>
    <length>6</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Territory__c/fields/Sales_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Sales_Campaign__c</fullName>
    <label>Sales Campaign</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Green Channel</fullName>
            </value>
            <value>
                <fullName>Inside Sales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LuxeLeadAssignmentHandler.cls
public class LuxeLeadAssignmentHandler {
    Public Static void  getLuxeShowroomUserDetails(List<Lead> lstOfLead,set<String> lstOfPincode){
        try{
             List<Log__c> listOfLogsToInsert = new List<Log__c>();
            if(!lstOfPincode.isEmpty()&& !lstOfLead.isEmpty()){
                String clstrBrand = GenericConstants.CLUSTER_BRAND_DOOWUP;
                Set<String> clusterSet = new Set<String>();
                Map<String,Territory__c> mapClustor_AssociatedTerritory = new Map<String,Territory__c>();
                list<Showroom_User__c> lstShowroomUser = new list<Showroom_User__c> ();
               
                list<Territory__c> lstTerritory= [Select id,Name,Cluster__c,City__c,Ironman__c,Lat_Long__Latitude__s,Lat_Long__Longitude__s,Pincode__c,Assignment__c,Cluster_Brand__c,Sales_Campaign__c,Inside_Sales_cluster__c
                                                  From Territory__c
                                                  Where Pincode__c IN:lstOfPincode and Cluster_Brand__c != :clstrBrand];
                if(!lstTerritory.isEmpty()){
                    for(Territory__c terri: lstTerritory){
                        clusterSet.add(terri.Cluster__c);
                        mapClustor_AssociatedTerritory.put(terri.Pincode__c,terri);
                    }
                    if(!clusterSet.isEmpty()){
                        dateTime todayDate = Date.Today();
                        System.debug('DayOfTheWeek: '+todayDate.format('EEEE'));
                        String showroomUserPCRole = GenericConstants.PRODUCT_CONSULTANT_ROLE;
                        String bronzeIMClass= GenericConstants.IM_Class_Bronze;
                        String todayDayInString = todayDate.format('EEEE');
                        lstShowroomUser = [Select Name,Daily_Assignment__c,Weekly_Off_Days__c,IsActive__c,Outskirts_Assignment__c,Outskirts_Monthly_Assignment__c,IM_Class__c,Role__c,Luxe_service_Showroom__c,
                                           (Select id,Name,Cluster__C,Assignment__c,Lat_Long__Latitude__s,Lat_Long__Longitude__s,IronMan__c,Monthly_Assignment__c
                                            from Territories__r) 
                                           From Showroom_User__c 
                                           where ID IN (Select IronMan__c 
                                                        from Territory__c 
                                                        where Cluster__C IN:clusterSet and Is_Active__c = True) 
                                           and Daily_Assignment__c != NULL and Weekly_Off_Days__c Excludes(:todayDayInString) and Role__c != :showroomUserPCRole and Luxe_service_Showroom__c = True and IM_Class__c !=:bronzeIMClass ];
                        system.debug('lstShowroomUser '+ lstShowroomUser);
                        
                        if(!lstShowroomUser.isEmpty()){
                            IronManLead_Assignment_Handler.getTerritoryChampionMapping(lstOfLead,  lstShowroomUser,   mapClustor_AssociatedTerritory); 
                            
                        }
                        else{
                            Boolean  pushToOzonetel = false;
                            set<String> citySet = new Set<String>();
                            for(lead ld: lstOfLead){
                                citySet.add(ld.city); 
                            }
                            system.debug('citySet' + citySet);
                            List<master__c> showroomListBasedOnCity = new List<master__c>();
                            Map<String,List<Showroom_user__c>> mapOfCityAndShowroomUser = new Map<String,List<Showroom_user__c>>();
                           // List<Showroom_User__c> lstShowroomUser = new List<Showroom_User__c>();
                            showroomListBasedOnCity =[select id,(select id,Role__c  from showroom_user__r where IM_Class__c != :bronzeIMClass and Role__c != :showroomUserPCRole and Weekly_Off_Days__c Excludes(:todayDayInString) 
                                                                 and Reached_Daily_Limit__c = false 
                                                                 and Reached_Monthly_Limit__c = false and IsActive__c = true ),
                                                                  Property_City__c from Master__c where Type__c = :GenericConstants.Showroom_Type and Property_City__c In: citySet and Luxe_service__c=true];
                            system.debug(' showroomListBasedOnCity ' +  showroomListBasedOnCity);
                            if(!showroomListBasedOnCity.isEmpty()){
                                for(master__c showroom : showroomListBasedOnCity){
                                    system.debug('showroom.showroom_user__r'+ showroom.showroom_user__r);
                                    lstShowroomUser.addAll(showroom.showroom_user__r);
                                }
                            }
                           
                            system.debug('lstShowroomUser '+ lstShowroomUser);
                            system.debug('mapClustor_AssociatedTerritory '+ mapClustor_AssociatedTerritory);
                            List<Showroom_user__c>    shTerriList = new List<Showroom_user__c>();
                            if(!lstShowroomUser.isEmpty()){
                                 shTerriList= [Select Name,Daily_Assignment__c,Weekly_Off_Days__c,IsActive__c,Role__c,
                                                                    (Select id,Name,Cluster__C,Assignment__c,Lat_Long__Latitude__s,Lat_Long__Longitude__s,IronMan__c,Monthly_Assignment__c
                                                                     from Territories__r where  Is_Active__c =true) 
                                                                    From Showroom_User__c where id IN:lstShowroomUser];
                            }else{
                                pushToOzoneTel = true;   
                             }
                            system.debug('shTerriList '+ shTerriList);
                            if(!shTerriList.isEmpty()){
                                IronManLead_Assignment_Handler.getTerritoryChampionMapping(lstOfLead,  shTerriList,  mapClustor_AssociatedTerritory);
                            }else{
                                pushToOzoneTel = true;
                            }
                            
                           
                            
                            if(pushToOzonetel){
                                List<Lead> listOfOzonetelpushedLeadsUpdate = new List<Lead>();
                                for(Lead ld : lstOfLead){
                                    Lead leadToUpdate = new Lead();
                                    leadToUpdate.id = ld.Id;
                                    leadToUpdate.Pushed_To_Ozonetel__c = true;
                                    leadToUpdate.Transfer_Status__c = 'IM-Inactive-Cluster';
                                    leadToUpdate.IM_Assignment_Stage__c = 'LC - No Iron Man available';
                                    //Owner and WTA Cloud Agent
                                    leadToUpdate.OwnerId = label.Cloud_Agent_Id;
                                    leadToUpdate.WT_Agent__c = label.Cloud_Agent_Id;
                                    listOfOzonetelpushedLeadsUpdate.add(leadToUpdate);
                                }
                                //Pushing to OzoneTel Queue
                                PushToOzoneTelAdditionalQueue objLPA = new PushToOzoneTelAdditionalQueue(lstOfLead,UserInfo.getSessionId());
                                ID jobID = System.enqueueJob(objLPA);
                                system.debug('-----jobID----'+jobID);
                                
                                if(!listOfOzonetelpushedLeadsUpdate.isEmpty()){
                                    //Update Lead Details
                                    update listOfOzonetelpushedLeadsUpdate;
                                }
                            }
                            if(!listOfLogsToInsert.isEmpty()){
                                //Insert log records.
                                insert listOfLogsToInsert;
                            }
                            
                        }
                    }  
                }
               else{
                        // Territory record is not present in pincode. Log the scenario and email will be sent through workflow on log record.
                        //First element is taken as the leads are getting created from Website and it will be only one at a time and not in bulk.
                        listOfLogsToInsert.add(Logger.returnLog('Lead Assignment Error','IronManLead_Assignment_Handler Class','getIronManDetails method',' A Territory record is not present for this pincode: '+String.valueOf(lstOfPincode),lstOfLead[0].email,String.valueOf(lstOfPincode)));
                        //pushToOzoneTel = true;
                    }
                
            }else{
             
                //cannot handle bulk scenarios
                listOfLogsToInsert.add(Logger.returnLog('Lead Assignment Error','IronManLead_Assignment_Handler Class','getIronManDetails method','Bulk Lead Scenario Cannot be handle as per the new IM assignment logic based on catergory',null,null));
             
            }
        }
        
        catch(exception e){
             system.debug('Exception : '+e.getStackTraceString());
            system.debug('Exception message: '+e.getMessage());
            //Log the exceptions
            Logger.log('Exception','getShowroomUserDetails method','IronManLead_Assignment_Handler Class',e.getMessage(),e.getStackTraceString(),null);
        }
    }
    
}