force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <label>Log</label>
    <nameField>
        <label>Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Lead_Opp_Phone__c.field-meta.xml
<CustomField>
    <fullName>Lead_Opp_Phone__c</fullName>
    <label>Lead/Opp Phone</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <label>RecordId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/StackTrace__c.field-meta.xml
<CustomField>
    <fullName>StackTrace__c</fullName>
    <label>StackTrace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Logger.cls
/**
 * @File Name          : Logger.cls
 * @Description        : 
 * @Author             : Bharatesh Shetty
 * @Group              : 
 * @Last Modified By   : Bharatesh Shetty
 * @Last Modified On   : 9/19/2019, 11:36:07 AM
 * @Modification Log   : 
 *==============================================================================
 * Ver         Date                     Author      		      Modification
 *==============================================================================
 * 1.0    9/19/2019, 11:07:03 AM   Bharatesh Shetty     Initial Version
**/
public class Logger {

  public static void log(String Type, String className,String methodName, String message,String stackTrace,String recordId) { 
    insert (new Log__c(Type__c=Type,
                       class__c=className,
                       Method__c = methodName,
                       message__c=message,
                       RecordId__c = recordId,
                       StackTrace__c = stackTrace,
                       Name = className));
                    //   System.debug('Log--->  '+Log__c);
  }
  
  public static void logWithPhone(String Type, String className,String methodName, String message,String stackTrace,String recordId, String ph) { 
    insert (new Log__c(Type__c=Type,
                       class__c=className,
                       Method__c = methodName,
                       message__c=message,
                       RecordId__c = recordId,
                       StackTrace__c = stackTrace,
                       Lead_Opp_Phone__c = ph,
                       Name = className));
                     //  System.debug('Log--->  '+Log__c);
  }
  public static Log__c returnLog(String Type, String className,String methodName, String message,String stackTrace,String recordId) { 
    return (new Log__c(Type__c=Type,
                       class__c=className,
                       Method__c = methodName,
                       message__c=message,
                       RecordId__c = recordId,
                       StackTrace__c = stackTrace,
                       Name = className));
                    //   System.debug('Log--->  '+Log__c);
  }
 
}