force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List Of Operating Cities</description>
    <label>City</label>
</CustomObject>

force-app/main/default/objects/Lead_Assignment__c/Lead_Assignment__c.object-meta.xml
<CustomObject>
    <label>Lead Assignment</label>
    <nameField>
        <label>Lead Assignment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Assignment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead_Assignment__c/fields/Actual_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Actual_Percentage__c</fullName>
    <formula>IF(Round_Robin__r.Total_Leads__c &gt; 0, Number_of_Leads__c /Round_Robin__r.Total_Leads__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Actual Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Lead_Assignment__c/fields/Assign_Percent__c.field-meta.xml
<CustomField>
    <fullName>Assign_Percent__c</fullName>
    <label>Assign Percent</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Lead_Assignment__c/fields/Number_of_Leads__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Leads__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Leads</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead_Assignment__c/fields/Round_Robin__c.field-meta.xml
<CustomField>
    <fullName>Round_Robin__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Round Robin</label>
    <referenceTo>Round_Robin__c</referenceTo>
    <relationshipLabel>Lead Assignment</relationshipLabel>
    <relationshipName>Lead_Assignment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead_Assignment__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Lead_Assignment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead_Round_Robin_Assignment__c/Lead_Round_Robin_Assignment__c.object-meta.xml
<CustomObject>
    <label>Iron Man Assignment</label>
    <nameField>
        <label>Lead Round Robin Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Iron Man Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead_Round_Robin_Assignment__c/fields/Assignment__c.field-meta.xml
<CustomField>
    <fullName>Assignment__c</fullName>
    <formula>(Daily_Assignment__c/Daily_Limit__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Assignment %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Lead_Round_Robin_Assignment__c/fields/Assignment_Days__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Days__c</fullName>
    <label>Assignment Days</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
            <value>
                <fullName>Sunday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead_Round_Robin_Assignment__c/fields/Daily_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Daily_Assignment__c</fullName>
    <label>Daily Assignment</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead_Round_Robin_Assignment__c/fields/Daily_Limit__c.field-meta.xml
<CustomField>
    <fullName>Daily_Limit__c</fullName>
    <label>Daily Limit</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead_Round_Robin_Assignment__c/fields/Distance_from_ShowRoom__c.field-meta.xml
<CustomField>
    <fullName>Distance_from_ShowRoom__c</fullName>
    <label>Distance from ShowRoom</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead_Round_Robin_Assignment__c/fields/IronMan_Reference__c.field-meta.xml
<CustomField>
    <fullName>IronMan_Reference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>IronMan Reference</label>
    <referenceTo>Showroom_User__c</referenceTo>
    <relationshipLabel>Iron Man Assignments</relationshipLabel>
    <relationshipName>ronMan_LeadAssignment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead_Round_Robin_Assignment__c/fields/Monthly_Assignments__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Assignments__c</fullName>
    <label>Monthly Assignments</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead_Round_Robin_Assignment__c/fields/Monthly_Limit__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Limit__c</fullName>
    <label>Monthly Limit</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead_Round_Robin_Assignment__c/fields/Showroom_Name__c.field-meta.xml
<CustomField>
    <fullName>Showroom_Name__c</fullName>
    <label>Showroom Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Round_Robin_Assignment__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Lead_Round_Robin_Assignment_User</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Round_Robin__c/Round_Robin__c.object-meta.xml
<CustomObject>
    <description>This is created to define user within each Queue for workload and city</description>
    <label>Round Robin</label>
    <nameField>
        <label>Round Robin  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Round Robin</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Round_Robin__c/fields/Queue_Name__c.field-meta.xml
<CustomField>
    <fullName>Queue_Name__c</fullName>
    <label>Queue Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Round_Robin__c/fields/Total_Leads__c.field-meta.xml
<CustomField>
    <fullName>Total_Leads__c</fullName>
    <label>Total Leads</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WTA_Assignment__c/WTA_Assignment__c.object-meta.xml
<CustomObject>
    <label>WTA Assignment</label>
    <nameField>
        <label>WTA Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WTA Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WTA_Assignment__c/fields/Agent_Campaign_Name__c.field-meta.xml
<CustomField>
    <fullName>Agent_Campaign_Name__c</fullName>
    <formula>User__r.Cloud_Agent_Campaign_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Agent Campaign Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WTA_Assignment__c/fields/Agent_Email__c.field-meta.xml
<CustomField>
    <fullName>Agent_Email__c</fullName>
    <formula>User__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Agent Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WTA_Assignment__c/fields/Assignment__c.field-meta.xml
<CustomField>
    <fullName>Assignment__c</fullName>
    <formula>Daily_Assignment__c / Daily_Limit__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Assignment %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/WTA_Assignment__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bengaluru</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>New Delhi</fullName>
            </value>
            <value>
                <fullName>Noida</fullName>
            </value>
            <value>
                <fullName>Gurgaon</fullName>
            </value>
            <value>
                <fullName>Ghaziabad</fullName>
            </value>
            <value>
                <fullName>Thane</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
            <value>
                <fullName>Kolkata</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WTA_Assignment__c/fields/City_Campaign_Name__c.field-meta.xml
<CustomField>
    <fullName>City_Campaign_Name__c</fullName>
    <label>City_Campaign Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BLR_AutoLead</fullName>
            </value>
            <value>
                <fullName>BLR-AutoLead-Pool2</fullName>
            </value>
            <value>
                <fullName>CHN_AutoLead-Pool2</fullName>
            </value>
            <value>
                <fullName>HYD_AutoLead-Pool2</fullName>
            </value>
            <value>
                <fullName>Kolkata_AutoLead-Pool2</fullName>
            </value>
            <value>
                <fullName>MUM_AutoLead-Pool2</fullName>
            </value>
            <value>
                <fullName>Pune_AutoLead-Pool2</fullName>
            </value>
            <value>
                <fullName>NCR_AutoLead-Pool2</fullName>
            </value>
            <value>
                <fullName>HYD_AutoLead</fullName>
            </value>
            <value>
                <fullName>CHN_AutoLead</fullName>
            </value>
            <value>
                <fullName>NCR_AutoLead</fullName>
            </value>
            <value>
                <fullName>MUM_AutoLead</fullName>
            </value>
            <value>
                <fullName>Pune_AutoLead</fullName>
            </value>
            <value>
                <fullName>Kolkata_AutoLead</fullName>
            </value>
            <value>
                <fullName>Others_AutoLead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WTA_Assignment__c/fields/Daily_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Daily_Assignment__c</fullName>
    <label>Daily Assignment</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WTA_Assignment__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Group A</fullName>
            </value>
            <value>
                <fullName>Group B</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WTA_Assignment__c/fields/Monthly_Assignments__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Assignments__c</fullName>
    <label>Monthly Assignments</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WTA_Assignment__c/fields/Monthly_Limit__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Limit__c</fullName>
    <label>Monthly Limit</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WTA_Assignment__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>WTA_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WTA_Assignment__c/fields/Weekly_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Weekly_Assignment__c</fullName>
    <label>Weekly Assignment</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WTA_Assignment__c/fields/Weekly_Limit__c.field-meta.xml
<CustomField>
    <fullName>Weekly_Limit__c</fullName>
    <label>Weekly Limit</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AssignLeadToIronMan.cls
Public class AssignLeadToIronMan implements Queueable,Database.AllowsCallouts{

    Lead ObjLead = new Lead(); 
    boolean bInBusinessHours;

    public AssignLeadToIronMan(Lead leadObj){
        ObjLead = leadObj;

    }
    Public void execute(QueueableContext QC){
        system.debug('lead Owner Name'+ObjLead.Owner.Name);
        system.debug('lead Owner Id'+ObjLead.OwnerId);
        Lead_Round_Robin_Assignment__c assignedUser;
        List<Lead> leadToUpdate = new List<Lead>();
        List<Lead> lstAssignToGroups = new List<Lead>();
        list<Lead_Round_Robin_Assignment__c> lstRleadAssignment = new list<Lead_Round_Robin_Assignment__c>();
        list<Lead_Round_Robin_Assignment__c> lstMatchedAssignment = new list<Lead_Round_Robin_Assignment__c>();
        list<Lead_Round_Robin_Assignment__c> lstAssignmentToUpdate = new list<Lead_Round_Robin_Assignment__c>();
        Map<String,List<Lead_Round_Robin_Assignment__c>> mapShowroomRAssgnments = new Map<String,List<Lead_Round_Robin_Assignment__c>>();

        // Lead id not NULL
        if( ObjLead != NULL ){
            try{
                if(ObjLead.Round_Robin_Lead_Source_Condition__c == true){
                    system.debug('++++ObjLead++++'+ObjLead.id);

                    lstRleadAssignment = [Select Assignment__c,Assignment_Days__c,Daily_Assignment__c,Daily_Limit__c,
                                                Distance_from_ShowRoom__c,Monthly_Assignments__c,Monthly_Limit__c,
                                                Showroom_Name__c,User__c,IronMan_Reference__c
                                                from Lead_Round_Robin_Assignment__c];
                    system.debug('+++++lstRleadAssignment+++'+lstRleadAssignment);
                    // IF records are Present put it in a map
                    if(!lstRleadAssignment.isEmpty() && lstRleadAssignment != NULL){
                        for(Lead_Round_Robin_Assignment__c objLeadRA : lstRleadAssignment){
                            if(mapShowroomRAssgnments.containsKey(objLeadRA.Showroom_Name__c)){
                                mapShowroomRAssgnments.get(objLeadRA.Showroom_Name__c).add(objLeadRA);
                            }
                            else{
                                mapShowroomRAssgnments.put(objLeadRA.Showroom_Name__c,new list<Lead_Round_Robin_Assignment__c>{objLeadRA});
                            }
                        }

                        
                        // If Status = Fresh Lead and Sub Status = New and Not Pushed Ozonetel and Not Assigned to Asm
                        if((objLead.Status =='Fresh Lead' && objLead.sub_status__c == 'New' && objLead.Pushed_To_Ozone_1st_Time__c == false && 
                            objLead.Assigned_to_Resi_ASM__c == false && String.isNotBlank(objLead.Closest_Showroom__c)) || 
                            (objLead.status == 'Appointment Fixed' && objLead.Pushed_To_Ozone_1st_Time__c == false  &&
                            objLead.Assigned_to_Resi_ASM__c == false && objLead.Assigned_to_WTA__c == false)){
                            
                            lstMatchedAssignment = NULL;
                            for(String sShowroom:mapShowroomRAssgnments.keyset()){
                                // If the Match Showroom matches
                                if(objLead.Closest_Showroom__c.containsIgnoreCase(sShowroom)){
                                    lstMatchedAssignment = mapShowroomRAssgnments.get(sShowroom);   
                                    break;  
                                }
                            } 

                            if(lstMatchedAssignment != NULL && !lstMatchedAssignment.isEmpty()){
                                Decimal d =100.0;
                                Datetime dt = DateTime.newInstance(objLead.createdDate.date(), Time.newInstance(0, 0, 0, 0));
                                String dayOfWeek=dt.format('EEEE');
                                for(Lead_Round_Robin_Assignment__c objAssignment:lstMatchedAssignment){
                                    if((objAssignment.Daily_Limit__c>0 && objAssignment.Daily_Assignment__c<objAssignment.Daily_Limit__c) 
                                        && (objAssignment.Monthly_Limit__c>0 && objAssignment.Monthly_Assignments__c<objAssignment.Monthly_Limit__c
                                        && objAssignment.Assignment_Days__c.containsIgnoreCase(dayOfWeek))){
                                        Decimal distance; 
                                        distance = String.isNotBlank(objLead.Closest_Showroom__c.trim().substringAfterLast(' ').removeEndIgnoreCase('km'))?Decimal.ValueOf(objLead.Closest_Showroom__c.trim().substringAfterLast(' ').removeEndIgnoreCase('km')):2000;
                                        System.debug('d--->'+d+'objAssignment.Assignment__c'+objAssignment.Assignment__c+'distance'+distance);
                                        if(distance <= objAssignment.Distance_from_ShowRoom__c)
                                            {
                                            if(objAssignment.Assignment__c<=d){
                                                d = objAssignment.Assignment__c;
                                                assignedUser = objAssignment;
                                            }    
                                        }
                                    }    
                                }

                                if(assignedUser != NULL){
                                    //Since After Trigger Creating the New Instance to Update
                                    system.debug('+++++assignedUser+++'+assignedUser+'+++objLead+++'+objLead);
                                    lead objLeadToUpdate = new lead();
                                    objLeadToUpdate.id = ObjLead.id;
                                    objLeadToUpdate.OwnerId = assignedUser.User__c;
                                    objLeadToUpdate.Wt_Agent__c = assignedUser.User__c;
    
                                    // Update Iron Man As SSA in 
                                    //objLeadToUpdate.Square_Showroom_Agent__c = assignedUser.User__c;
                                    objLeadToUpdate.Sales_Manager__c =  assignedUser.IronMan_Reference__c;
                                    objLeadToUpdate.Assigned_to_Resi_ASM__c = true;
                                    leadToUpdate.add(objLeadToUpdate);

                                    assignedUser.Daily_Assignment__c++;
                                    assignedUser.Monthly_Assignments__c++;
                                    System.debug('Updated sadsa'+assignedUser);
                                    lstAssignmentToUpdate.add(assignedUser); 
                                }else{
                                    // No Iron Man Meets the Critiria
                                    lstAssignToGroups.add(objLead);
                                } 

                            }else{
                                // No Macth Found i.e No IronMan for the showroom then assign it to WTA
                                lstAssignToGroups.add(objLead);
                            }

                        // Fresh Lead - Relanded Condition       
                        }else if(objLead.Status =='Fresh Lead' && objLead.sub_status__c == 'Re-Landed'){
                                lstAssignToGroups.add(objLead);
                        }
                        else{
                                // Do Nothing     
                        }
                        
                    }
                    else{
                        // Group A and Group B
                        // If there is no Iron man Records
                        lstAssignToGroups.add(objLead);
                    }

                    if(lstAssignToGroups != NULL && !lstAssignToGroups.isEmpty()){
                        // If created in business Hours
                        system.debug('lstAssignToGroups'+lstAssignToGroups);
                        if(objLead.Created_during_business_hours__c){ 
                            lead ObjLeadNew = new lead();
                            ObjLeadNew.id = objLead.id;
                            ObjLeadNew.Pushed_To_Ozonetel__c = true;
                            leadToUpdate.add(ObjLeadNew);
                            system.debug('LeadPushToOzonetelQueueable');
                            LeadPushToOzonetelQueueable objLPA = new LeadPushToOzonetelQueueable(lstAssignToGroups,UserInfo.getSessionId());
                            ID jobID = System.enqueueJob(objLPA);
                        }else{
                            AssignOffBusinessHrLead(objLead);
                        }
                    }
                    
                    // Update the Lead   
                    if(leadToUpdate != NULL && !leadToUpdate.isEmpty()){
                        update leadToUpdate;
                    }

                    // Update Assignement List 
                    if(lstAssignmentToUpdate != NULL && !lstAssignmentToUpdate.isEmpty()){
                        update lstAssignmentToUpdate;
                    }
                }
                else{
                    //Round_Robin_Lead_Source_Condition__c false don't change the Owner 
                }
            }
            catch(Exception e){
                system.debug('Exception  --- >'+e.getStackTraceString());
                 Logger.log('Exception','AssignLeadToIronMan','execute',e.getMessage(),e.getStackTraceString(),NULL);
            }    
        }else{
            // IF Lead Object is NULL
        }
    }

    public static void AssignOffBusinessHrLead(Lead ObjectLead){

     /* When Lead is created it's assigned to respective Group and We are comapring the Group Name
     In Round Robin*/
    system.debug('lead Owner Name'+ObjectLead.Owner.Name);
    system.debug('lead Owner Id'+ObjectLead.OwnerId);
    Map < String, Id > rrNameMap = new Map < String, Id > ();
    Lead_Assignment__c curLAss = new Lead_Assignment__c();
    list<lead> lstupdatelead = new list<lead>();
    list<Lead_Assignment__c> lstleadAssignment = new list<Lead_Assignment__c>();
    Map < Id, Round_Robin__c > roundRobinMap = new Map < Id, Round_Robin__c > ([select Queue_Name__c, Total_Leads__c,IsActive__c,
                                                                                (select Name,Number_of_Leads__c, USer__r.name, User__r.LastLoginDate, Assign_Percent__c, Actual_Percentage__c, Round_Robin__c, User__c from Lead_Assignment__r 
                                                                                    where Assign_Percent__c >0)
                                                                                FROM Round_Robin__c
                                                                                WHERE Queue_Name__c =: ObjectLead.Owner.Name
                                                                                ]);
        system.debug('lead Owner Name'+ObjectLead.Owner.Name); 
        system.debug('roundRobinMap'+roundRobinMap);                                                                        
        if(!roundRobinMap.isEmpty()){
            for(Round_Robin__c rr:roundRobinMap.values()){
                rrNameMap.put(rr.Queue_Name__c,rr.id);
            }    

            system.debug('rrNameMap'+rrNameMap); 
            if(!rrNameMap.isEmpty()){
                Round_Robin__c roundRobin = roundRobinMap.get(rrNameMap.get(ObjectLead.Owner.Name));
                if (roundRobin.Lead_Assignment__r != NULL) {
                    decimal i = 0;
                    for(Lead_Assignment__c leadAssign:roundRobin.Lead_Assignment__r){
                        system.debug('i-->'+(leadAssign.Assign_Percent__c - leadAssign.Actual_Percentage__c)+'leadAssign.User__c'+leadAssign.Name );
                        if( i < leadAssign.Assign_Percent__c - leadAssign.Actual_Percentage__c ){
                            
                            i = leadAssign.Assign_Percent__c - leadAssign.Actual_Percentage__c;
                            curLAss = leadAssign;
                        }
                    }
                }
                if(curLAss != NULL){
                    lead ObjLeadNew = new lead();
                    ObjLeadNew.id = ObjectLead.id;
                    ObjLeadNew.Ownerid = curLAss.User__c;
                    ObjLeadNew.WT_Agent__c = curLAss.User__c;
                    ObjLeadNew.Assigned_to_WTA__c = true;
                    lstupdatelead.add(ObjLeadNew);
                    curLAss.Number_of_Leads__c += 1;
                    lstleadAssignment.add(curLAss);
                }
                else{
                    // No lead Assignment record for lead
                }
            }    
        }
        else{
            // Round Robin record doesn't exists
        }

        system.debug('lstupdatelead--->'+lstupdatelead);
        system.debug('lstleadAssignment--->'+lstleadAssignment);


        if(!lstupdatelead.isEmpty()){
            update lstupdatelead;
        }
        if(!lstleadAssignment.isEmpty()){
            update lstleadAssignment;
        }

    }



    

    public void  AssignToWTA(Lead ObjectLead){

        lead objlead;
        list<Lead> lstLeadUpdate = new list<Lead>();
        list<WTA_Assignment__c> lstWTAssignment = new list<WTA_Assignment__c>();
        list<WTA_Assignment__c> lstGroupA_Assignment = new list<WTA_Assignment__c>();
        list<WTA_Assignment__c> lstGroupB_Assignment = new list<WTA_Assignment__c>();

        if(String.isNotBlank(ObjectLead.city)){
            objLead = ObjectLead;
            try{
                lstGroupA_Assignment = [Select id,Name,Assignment__c,City__c,Daily_Assignment__c,Daily_Limit__c,Group__c,
                                            IsActive__c,Monthly_Assignments__c,Monthly_Limit__c,User__c,Weekly_Assignment__c,Weekly_Limit__c,
                                            Agent_Campaign_Name__c,City_Campaign_Name__c,Agent_Email__c 
                                            from WTA_Assignment__c 
                                            where City__c includes (:objLead.city) and Group__c = 'Group A' and 
                                            Assignment__c <100 and IsActive__c = true
                                            Order by Assignment__c desc];

                                            
                
                if(lstGroupA_Assignment != NULL && !lstGroupA_Assignment.isEmpty()){
                    system.debug('Sample Assignment Group A OutOfWorking Hr'+lstGroupA_Assignment);
                    lead ObjLeadNew = new lead();
                    ObjLeadNew.id = objLead.id;
                    ObjLeadNew.OwnerID = lstGroupA_Assignment[0].User__c;
                    ObjLeadNew.WT_Agent__c = lstGroupA_Assignment[0].User__c;
                    ObjLeadNew.Assigned_to_WTA__c = true;
                    lstLeadUpdate.add(ObjLeadNew);

                    lstGroupA_Assignment[0].Daily_Assignment__c = lstGroupA_Assignment[0].Daily_Assignment__c +1;
                    lstGroupA_Assignment[0].Monthly_Assignments__c = lstGroupA_Assignment[0].Monthly_Assignments__c +1;
                    lstGroupA_Assignment[0].Weekly_Assignment__c = lstGroupA_Assignment[0].Weekly_Assignment__c +1;
                    lstWTAssignment.add(lstGroupA_Assignment[0]); 
                }
                else{

                    lstGroupB_Assignment = [Select id,Name,Assignment__c,City__c,Daily_Assignment__c,Daily_Limit__c,Group__c,
                                IsActive__c,Monthly_Assignments__c,Monthly_Limit__c,User__c,Weekly_Assignment__c,Weekly_Limit__c,
                                Agent_Campaign_Name__c,City_Campaign_Name__c,Agent_Email__c
                                from WTA_Assignment__c 
                                where City__c includes (:objLead.city) and Group__c = 'Group B'  
                                and IsActive__c = true
                                Order by Assignment__c desc];

                    if(lstGroupB_Assignment != NULL && !lstGroupB_Assignment.isEmpty()){
                        system.debug('Sample Assignment Group B OutOfWorking Hr'+lstGroupB_Assignment);
                        lead ObjLeadNew = new lead();
                        ObjLeadNew.id = objLead.id;
                        ObjLeadNew.OwnerID = lstGroupB_Assignment[0].User__c;
                        ObjLeadNew.WT_Agent__c = lstGroupB_Assignment[0].User__c;
                        ObjLeadNew.Assigned_to_WTA__c = true;
                        lstLeadUpdate.add(ObjLeadNew);

                        lstGroupB_Assignment[0].Daily_Assignment__c = lstGroupB_Assignment[0].Daily_Assignment__c +1;
                        lstGroupB_Assignment[0].Monthly_Assignments__c = lstGroupB_Assignment[0].Monthly_Assignments__c +1;
                        lstGroupB_Assignment[0].Weekly_Assignment__c = lstGroupB_Assignment[0].Weekly_Assignment__c +1;
                        lstWTAssignment.add(lstGroupB_Assignment[0]); 
                    }            
                }
                
                if(lstLeadUpdate != NULL && !lstLeadUpdate.isEmpty()){
                    System.debug('lstLeadUpdate'+lstLeadUpdate);
                    update lstLeadUpdate;
                }

                if(lstWTAssignment != NULL && !lstWTAssignment.isEmpty()){
                    update lstWTAssignment;
                }
            }
            catch(Exception e){
                 Logger.log('Exception','AssignLeadToIronMan','AssignToWTA',e.getMessage(),e.getStackTraceString(),NULL);
            }
        }
        
        else{
            // If city is not null 
        }

    }
}