force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List Of Operating Cities</description>
    <label>City</label>
</CustomObject>

force-app/main/default/objects/Showroom_User__c/Showroom_User__c.object-meta.xml
<CustomObject>
    <label>Showroom User</label>
    <nameField>
        <label>ShowRoom User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Showroom User</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Showroom_User__c/fields/Monthly_Exception_Leads_Assigned__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Exception_Leads_Assigned__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Monthly Exception Leads Assigned</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territory__c/Territory__c.object-meta.xml
<CustomObject>
    <label>Territory</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bengaluru</fullName>
            </value>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>Kolkata</fullName>
            </value>
            <value>
                <fullName>Coimbatore</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Noida</fullName>
            </value>
            <value>
                <fullName>Gurgaon</fullName>
            </value>
            <value>
                <fullName>New Delhi</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
            <value>
                <fullName>Thane</fullName>
            </value>
            <value>
                <fullName>Visakhapatnam</fullName>
            </value>
            <value>
                <fullName>Mysore</fullName>
            </value>
            <value>
                <fullName>Lucknow</fullName>
            </value>
            <value>
                <fullName>Indore</fullName>
            </value>
            <value>
                <fullName>Mangalore</fullName>
            </value>
            <value>
                <fullName>Surat</fullName>
            </value>
            <value>
                <fullName>Ghaziabad</fullName>
            </value>
            <value>
                <fullName>Ahmedabad</fullName>
            </value>
            <value>
                <fullName>Ranchi</fullName>
            </value>
            <value>
                <fullName>Faridabad</fullName>
            </value>
            <value>
                <fullName>Kochi</fullName>
            </value>
            <value>
                <fullName>Bhubaneswar</fullName>
            </value>
            <value>
                <fullName>Madurai</fullName>
            </value>
            <value>
                <fullName>Jaipur</fullName>
            </value>
            <value>
                <fullName>Vijayawada</fullName>
            </value>
            <value>
                <fullName>Salem</fullName>
            </value>
            <value>
                <fullName>Nagpur</fullName>
            </value>
            <value>
                <fullName>Trichy</fullName>
            </value>
            <value>
                <fullName>Outskirts</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ExceptionLeadsIMShareBatch_Test.cls
@isTest
public class ExceptionLeadsIMShareBatch_Test {    
    @TestSetup static void data(){
        //Create Showroom Users records
        List<Showroom_User__c> listOfShowroomUsers = new List<Showroom_User__c>();
        Showroom_User__c objShowroom1= TestData_Factory.createShowroomUser(false);
        objShowroom1.City__c = 'Bengaluru';
        objShowroom1.IsActive__c = true;
        objShowroom1.Monthly_Exception_Leads_Assigned__c = 10;
        listOfShowroomUsers.add(ObjShowroom1);
        
        Showroom_User__c objShowroom2= TestData_Factory.createShowroomUser(false);
        objShowroom2.City__c = 'Bengaluru';
        objShowroom2.IsActive__c = true;
        objShowroom2.Monthly_Exception_Leads_Assigned__c = 9;
        listOfShowroomUsers.add(ObjShowroom2);
        
        Showroom_User__c objShowroom3= TestData_Factory.createShowroomUser(false);
        objShowroom3.City__c = 'Kolkata';
        objShowroom3.IsActive__c = true;
        objShowroom3.Monthly_Exception_Leads_Assigned__c = Null;
        listOfShowroomUsers.add(ObjShowroom3);
        
        insert listOfShowroomUsers;
        
        List<Territory__c> listOfTerritories = new List<Territory__c>();
        Territory__c objTerr = TestData_Factory.createTerritory('Area a',ObjShowroom1.id,'Bengaluru','Cluster A','123456',False);
        objTerr.Lat_Long__Latitude__s = 20.0936477440000;
        objTerr.Lat_Long__Longitude__s =  89.7849897840000;
        listOfTerritories.add(objTerr);
        
        Territory__c objTerr1 = TestData_Factory.createTerritory('Area b',ObjShowroom2.id,'Bengaluru','Cluster A','123457',False);
        objTerr1.Lat_Long__Latitude__s = 25.0936477440000;
        objTerr1.Lat_Long__Longitude__s =  88.7849897840000;
        listOfTerritories.add(objTerr1);           
        
        Territory__c objTerr2 = TestData_Factory.createTerritory('Area b',ObjShowroom3.id,'Kolkata','Cluster A','123458',False);
        objTerr2.Lat_Long__Latitude__s = 26.0936477440000;
        objTerr2.Lat_Long__Longitude__s =  87.7849897840000;
        listOfTerritories.add(objTerr2); 
        
        insert listOfTerritories;
        Account acc= new account();
        acc.name='test acc';
        insert acc;
        List<Lead> listOfLeads = new List<Lead>();
        lead objLead = new Lead();
        objlead = TestData_Factory.CreateFreshLead(false);
        objlead.Postalcode = '123400';
        objlead.City = 'Bengaluru';
        objLead.Account__c =acc.id;
        listOfLeads.add(objlead);
        
        lead objLead1 = new Lead();
        objlead1 = TestData_Factory.CreateFreshLead(false);
        objlead1.Postalcode = '123401';
        objlead1.City = 'Kolkata';
        objLead1.Account__c =acc.id;
        listOfLeads.add(objlead1); 
        
        insert listOfLeads;
    }
    public testMethod static void ExceptionLeadsIMShareBatchTest1(){
        Test.startTest();
        Database.executeBatch(new ExceptionLeadsIMShareBatch());
        test.stopTest();
    }
    public testMethod static void ExceptionLeadsIMShareBatchTest2(){
        Map<Id,Lead> mapOfLeads = new Map<Id,Lead>([Select id from lead]); 
        Test.startTest();
        Database.executeBatch(new ExceptionLeadsIMShareBatch(mapOfLeads.keySet()));
        test.stopTest();
    }
}