force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List Of Operating Cities</description>
    <label>City</label>
</CustomObject>

force-app/main/default/objects/Custom_Campaign__c/Custom_Campaign__c.object-meta.xml
<CustomObject>
    <label>Custom Campaign</label>
    <nameField>
        <label>Custom Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Campaign__c/fields/Batch_Process_Description__c.field-meta.xml
<CustomField>
    <fullName>Batch_Process_Description__c</fullName>
    <label>Batch Process Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Custom_Campaign__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Ahmedabad</fullName>
            </value>
            <value>
                <fullName>Bengaluru</fullName>
            </value>
            <value>
                <fullName>Bhubaneswar</fullName>
            </value>
            <value>
                <fullName>Calicut</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Coimbatore</fullName>
            </value>
            <value>
                <fullName>Faridabad</fullName>
            </value>
            <value>
                <fullName>Ghaziabad</fullName>
            </value>
            <value>
                <fullName>Gurgaon</fullName>
            </value>
            <value>
                <fullName>Guwahati</fullName>
            </value>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>Indore</fullName>
            </value>
            <value>
                <fullName>Jaipur</fullName>
            </value>
            <value>
                <fullName>Jamshedpur</fullName>
            </value>
            <value>
                <fullName>Kochi</fullName>
            </value>
            <value>
                <fullName>Kolkata</fullName>
            </value>
            <value>
                <fullName>Lucknow</fullName>
            </value>
            <value>
                <fullName>Madurai</fullName>
            </value>
            <value>
                <fullName>Mangalore</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
            <value>
                <fullName>Mysore</fullName>
            </value>
            <value>
                <fullName>Nagpur</fullName>
            </value>
            <value>
                <fullName>New Delhi</fullName>
            </value>
            <value>
                <fullName>Noida</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Outskirts</fullName>
            </value>
            <value>
                <fullName>Patna</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
            <value>
                <fullName>Ranchi</fullName>
            </value>
            <value>
                <fullName>Salem</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Campaign__c/fields/Offline_Priority_Values__c.field-meta.xml
<CustomField>
    <fullName>Offline_Priority_Values__c</fullName>
    <label>Offline Priority Values</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>P0</fullName>
            </value>
            <value>
                <fullName>P1</fullName>
            </value>
            <value>
                <fullName>P2</fullName>
            </value>
            <value>
                <fullName>P3</fullName>
            </value>
            <value>
                <fullName>B0</fullName>
            </value>
            <value>
                <fullName>B1</fullName>
            </value>
            <value>
                <fullName>B2</fullName>
            </value>
            <value>
                <fullName>L0</fullName>
            </value>
            <value>
                <fullName>L1</fullName>
            </value>
            <value>
                <fullName>L2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Custom_Campaign__c/fields/Total_Leads_Processed__c.field-meta.xml
<CustomField>
    <fullName>Total_Leads_Processed__c</fullName>
    <label>Total Leads Processed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CampaignTransferBatch_test.cls
@isTest
public class CampaignTransferBatch_test 
{
 	Public static Lead ld;
    Public static Custom_Campaign__c ccRecord;
    Public static String CampaignName;
    Public static Id CampaignId;
    Public static Decimal totalLeads;
    Public static String Description;
    Public static List<String> cityList = new List<String>();
    Public static List<String> priorityValues = new List<String>();
       
    @TestSetup static void data() 
    { 
        ccRecord =new Custom_Campaign__c();
        ccRecord.Name = 'Nimbus Telugu Transfer';
        ccRecord.City__c = 'Bengaluru;Coimbatore';
        ccRecord.Offline_Priority_Values__c = 'L0;L1;L2';
        ccRecord.Batch_Process_Description__c = 'Test';
        ccRecord.Total_Leads_Processed__c = 0;
        insert ccRecord;
        
        Account acc = new account();
        acc.Name='acctest';
        insert acc;

        ld = TestData_Factory.CreateFreshLead(false);
        ld.Status = 'Fresh Lead';
        ld.Sub_Status__c = 'Unverified';
        ld.Account__c =acc.id;
        ld.city='Bengaluru';
        ld.Offline_Priority_Lead__c = 'L0';
        insert ld;
        
    }
    
    public testMethod static void CampaignTransferBatch_test1()
    {
        Test.startTest();
        Database.executeBatch(new CampaignTransferBatch());
        test.stopTest();
    }
    
    public testMethod static void CampaignTransferBatch_test2()
    {
        Test.startTest();        
        
        List<Custom_Campaign__c> ccList = new  List<Custom_Campaign__c>();     
        ccList = [SELECT id,City__c, Offline_Priority_Values__c,Name,Batch_Process_Description__c,Total_Leads_Processed__c 
                  from Custom_Campaign__c LIMIT 1];
        
        System.debug('ccList :'+ccList);
        
         CampaignId = ccList[0].Id ;
         CampaignName = ccList[0].Name ;
    //     cityList =  ccList[0].City__c.split(';'); 
    //     priorityValues = ccList[0].Offline_Priority_Values__c.split(';'); 
         totalLeads = ccList[0].Total_Leads_Processed__c;
         Description = ccList[0].Batch_Process_Description__c;
        
         ld = [Select id from Lead limit 1];
         Set<Id> setOfIds = new Set<Id>();
         setOfIds.add(ld.id);
        
        Database.executeBatch(new CampaignTransferBatch(setOfIds,CampaignName,CampaignId,TotalLeads,Description,ccRecord));
        test.stopTest();
    }
    
    public testMethod static void CampaignTransferBatch_test3()
    {
        Test.startTest();
        String sch = '0 0 23 * * ?';
        test.stopTest();
    }
}