force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List Of Operating Cities</description>
    <label>City</label>
</CustomObject>

force-app/main/default/objects/Showroom_User__c/Showroom_User__c.object-meta.xml
<CustomObject>
    <label>Showroom User</label>
    <nameField>
        <label>ShowRoom User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Showroom User</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Showroom_User__c/fields/Monthly_Exception_Leads_Assigned__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Exception_Leads_Assigned__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Monthly Exception Leads Assigned</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ExceptionLeadsCountResetBatch_Test.cls
@isTest
public class ExceptionLeadsCountResetBatch_Test {    
    @TestSetup static void data(){
        //Create Showroom Users records
        List<Showroom_User__c> listOfShowroomUsers = new List<Showroom_User__c>();
        Showroom_User__c objShowroom1= TestData_Factory.createShowroomUser(false);
        objShowroom1.City__c = 'Bengaluru';
        objShowroom1.IsActive__c = true;
        objShowroom1.Monthly_Exception_Leads_Assigned__c = 10;
        listOfShowroomUsers.add(ObjShowroom1);
        
        insert listOfShowroomUsers;
        System.debug('listOfShowroomUsers: '+listOfShowroomUsers);
    }
    public testMethod static void ExceptionLeadsCountResetBatchTest1(){
        Test.startTest();
        Database.executeBatch(new ExceptionLeadsCountResetBatch());
        test.stopTest();
    }
    public testMethod static void ExceptionLeadsCountResetBatchTest2(){
        Map<Id,Showroom_User__c> mapOfShowroomUsers = new Map<Id,Showroom_User__c>([Select id from Showroom_User__c]); 
        Test.startTest();
        Database.executeBatch(new ExceptionLeadsCountResetBatch(mapOfShowroomUsers.keySet()));
        test.stopTest();
    }
}