force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List Of Operating Cities</description>
    <label>City</label>
</CustomObject>

force-app/main/default/objects/Lead_Class_Scoring__c/Lead_Class_Scoring__c.object-meta.xml
<CustomObject>
    <label>Lead and IM Class mapping</label>
    <nameField>
        <displayFormat>LM - {0000000}</displayFormat>
        <label>Lead  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead and IM Class mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead_Class_Scoring__c/fields/Offline_Ads_Included_Cities__c.field-meta.xml
<CustomField>
    <fullName>Offline_Ads_Included_Cities__c</fullName>
    <label>Offline Ads Included Cities</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Coimbatore</fullName>
            </value>
            <value>
                <fullName>Madurai</fullName>
            </value>
            <value>
                <fullName>Kochi</fullName>
            </value>
            <value>
                <fullName>Salem</fullName>
            </value>
            <value>
                <fullName>Trichy</fullName>
            </value>
            <value>
                <fullName>Mysore</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead_Class_Scoring__c/fields/Offline_Assignment_Enable__c.field-meta.xml
<CustomField>
    <fullName>Offline_Assignment_Enable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Offline Assignment Enable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/Showroom_User__c.object-meta.xml
<CustomObject>
    <label>Showroom User</label>
    <nameField>
        <label>ShowRoom User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Showroom User</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Showroom_User__c/fields/Backlogs__c.field-meta.xml
<CustomField>
    <fullName>Backlogs__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Backlogs</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/Daily_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Daily_Assignment__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Daily Assignment</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/Daily_Assignment_Limit__c.field-meta.xml
<CustomField>
    <fullName>Daily_Assignment_Limit__c</fullName>
    <defaultValue>7</defaultValue>
    <label>Daily Assignment Limit</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/IronMan__c.field-meta.xml
<CustomField>
    <fullName>IronMan__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IronMan</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/Monthly_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Assignment__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Monthly Assignment</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/Monthly_Assignment_Limit__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Assignment_Limit__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Monthly Assignment Limit</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Showroom_User__c/fields/Threashold__c.field-meta.xml
<CustomField>
    <fullName>Threashold__c</fullName>
    <defaultValue>18</defaultValue>
    <label>Threashold</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Territory__c/Territory__c.object-meta.xml
<CustomObject>
    <label>Territory</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Territory__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bengaluru</fullName>
            </value>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>Kolkata</fullName>
            </value>
            <value>
                <fullName>Coimbatore</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Noida</fullName>
            </value>
            <value>
                <fullName>Gurgaon</fullName>
            </value>
            <value>
                <fullName>New Delhi</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
            <value>
                <fullName>Thane</fullName>
            </value>
            <value>
                <fullName>Visakhapatnam</fullName>
            </value>
            <value>
                <fullName>Mysore</fullName>
            </value>
            <value>
                <fullName>Lucknow</fullName>
            </value>
            <value>
                <fullName>Indore</fullName>
            </value>
            <value>
                <fullName>Mangalore</fullName>
            </value>
            <value>
                <fullName>Surat</fullName>
            </value>
            <value>
                <fullName>Ghaziabad</fullName>
            </value>
            <value>
                <fullName>Ahmedabad</fullName>
            </value>
            <value>
                <fullName>Ranchi</fullName>
            </value>
            <value>
                <fullName>Faridabad</fullName>
            </value>
            <value>
                <fullName>Kochi</fullName>
            </value>
            <value>
                <fullName>Bhubaneswar</fullName>
            </value>
            <value>
                <fullName>Madurai</fullName>
            </value>
            <value>
                <fullName>Jaipur</fullName>
            </value>
            <value>
                <fullName>Vijayawada</fullName>
            </value>
            <value>
                <fullName>Salem</fullName>
            </value>
            <value>
                <fullName>Nagpur</fullName>
            </value>
            <value>
                <fullName>Trichy</fullName>
            </value>
            <value>
                <fullName>Outskirts</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Territory__c/fields/Cluster_Brand__c.field-meta.xml
<CustomField>
    <fullName>Cluster_Brand__c</fullName>
    <label>Cluster Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Homelane</fullName>
                <default>true</default>
                <label>Homelane</label>
            </value>
            <value>
                <fullName>Doow up</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Territory__c/fields/Ironman__c.field-meta.xml
<CustomField>
    <fullName>Ironman__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Ironman</label>
    <referenceTo>Showroom_User__c</referenceTo>
    <relationshipLabel>Territories</relationshipLabel>
    <relationshipName>Territories</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Territory__c/fields/Monthly_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Assignment__c</fullName>
    <formula>If( ISPICKVAL( City__c , &apos;Outskirts&apos;), Ironman__r.Outskirts_Monthly_Assignment__c , Ironman__r.Monthly_Assignment__c  )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Monthly Assignment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/OfflineAdsLeadImShareBatch_Test.cls
@IsTest
public class OfflineAdsLeadImShareBatch_Test {
    Public static Lead ld;
    public static Lead_Class_Scoring__c  lcs;
    
    @TestSetup static void data() { 
    
      lcs = new Lead_Class_Scoring__c();
        lcs.Offline_Ads_Included_Cities__c ='Coimbatore';
        lcs.Offline_Assignment_Enable__c=true;
        RecordType recType1= [SELECT Id FROM RecordType WHERE Name='Offline Ads' limit 1];
        lcs.RecordTypeId =recType1.id;
        insert lcs;    
    
    
    Showroom_User__c objShowroom1= TestData_Factory.createShowroomUser(false);
        objShowroom1.Email__c = 'TestSHowRoomasdUSer@test.com';
        objShowroom1.Threashold__c = 10;
        objShowroom1.Backlogs__c = 2;
        objShowroom1.Daily_Assignment__c = 4;
        objShowroom1.Daily_Assignment_Limit__c = 10;
        objShowroom1.IsActive__c = true;
        objShowroom1.Monthly_Assignment__c = 0;
        objShowroom1.Monthly_Assignment_Limit__c = 100;
        objShowroom1.City__c='Coimbatore';
        insert objShowroom1;
    Showroom_User__c objShowroom2= TestData_Factory.createShowroomUser(false);
        objShowroom2.Email__c = 'TestSHowRoomasdU2Ser@test.com';
        objShowroom2.Threashold__c = 10;
        objShowroom2.Backlogs__c = 2;
        objShowroom2.Daily_Assignment__c = 4;
        objShowroom2.Daily_Assignment_Limit__c = 10;
        objShowroom2.IsActive__c = true;
        objShowroom2.Monthly_Assignment__c = 0;
        objShowroom2.Monthly_Assignment_Limit__c = 100;
        objShowroom2.City__c='Coimbatore';
        insert objShowroom2;
        
        Territory__c objTerr1 = TestData_Factory.createTerritory('Area b',ObjShowroom1.id,'Coimbatore','Cluster A','560103',False);
        objTerr1.Lat_Long__Latitude__s = 25.0936477440000;
        objTerr1.Lat_Long__Longitude__s =  88.7849897840000;
        objTerr1.Cluster_Brand__c ='Homelane';
        //objTerr1.Ironman__c
        Insert objTerr1; 
        
        Territory__c objTerr2 = TestData_Factory.createTerritory('Area b',ObjShowroom2.id,'Coimbatore','Cluster A','560104',False);
        objTerr2.Lat_Long__Latitude__s = 25.0936477440000;
        objTerr2.Lat_Long__Longitude__s =  88.7849897840000;
        objTerr2.Cluster_Brand__c ='Homelane';
        //objTerr1.Ironman__c
        Insert objTerr2; 
        
        
        ld = TestData_Factory.CreateFreshLead(false);
        ld.LeadSource ='Offline Ads';
        ld.Brand__c='HomeLane';
        ld.City='Coimbatore';
        insert ld;
    }
    
    public testMethod static void LeadTriggerDoowupTest1() {
        Test.startTest();
        ld=[select id,City from Lead limit 1];
        OfflineAdsLeadIMShareBatch  batchable = new OfflineAdsLeadIMShareBatch ();
        database.executeBatch(batchable);
        Test.stopTest();
    }
    
    public testMethod static void UnverifiedLeadsAssignmentInitiateBatch(){
        Test.startTest();
        String sch = '0 0 23 * * ?';
       System.schedule('OfflineAdsLeadIMShareBatch',sch, new OfflineAdsLeadIMShareBatch());
        test.stopTest();
    }
}