force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List Of Operating Cities</description>
    <label>City</label>
</CustomObject>

force-app/main/default/objects/Interior_Designer__c/Interior_Designer__c.object-meta.xml
<CustomObject>
    <label>Interior Designer</label>
    <nameField>
        <label>Design Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interior Designers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Interior_Designer__c/fields/Available_at_Showroom__c.field-meta.xml
<CustomField>
    <fullName>Available_at_Showroom__c</fullName>
    <label>Available at Showroom</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Kanakapura Showroom</fullName>
            </value>
            <value>
                <fullName>Gopalan Showroom</fullName>
            </value>
            <value>
                <fullName>Pushparang Showroom</fullName>
            </value>
            <value>
                <fullName>Durga Petals Showroom</fullName>
            </value>
            <value>
                <fullName>Test Showroom 2</fullName>
            </value>
            <value>
                <fullName>Sanghvi Valley</fullName>
            </value>
            <value>
                <fullName>Noida Showroom</fullName>
            </value>
            <value>
                <fullName>Gurgaon Showroom</fullName>
            </value>
            <value>
                <fullName>Kodambakkam Showroom</fullName>
            </value>
            <value>
                <fullName>Gachibowli Showroom</fullName>
            </value>
            <value>
                <fullName>Kandivali Showroom</fullName>
            </value>
            <value>
                <fullName>Yelahanka Showroom</fullName>
            </value>
            <value>
                <fullName>HSR Showroom</fullName>
            </value>
            <value>
                <fullName>Thane Showroom</fullName>
            </value>
            <value>
                <fullName>Test Showroom</fullName>
            </value>
            <value>
                <fullName>Gulbarga</fullName>
            </value>
            <value>
                <fullName>Hebbal Showroom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interior_Designer__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NCR</fullName>
            </value>
            <value>
                <fullName>Bengaluru</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
            <value>
                <fullName>Kolkata</fullName>
            </value>
            <value>
                <fullName>Gurgaon</fullName>
            </value>
            <value>
                <fullName>Coimbatore</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interior_Designer__c/fields/Languages_Known__c.field-meta.xml
<CustomField>
    <fullName>Languages_Known__c</fullName>
    <label>Languages Known</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>Hindi</fullName>
            </value>
            <value>
                <fullName>Kannada</fullName>
            </value>
            <value>
                <fullName>Tamil</fullName>
            </value>
            <value>
                <fullName>Telugu</fullName>
            </value>
            <value>
                <fullName>Malayalam</fullName>
            </value>
            <value>
                <fullName>Marathi</fullName>
            </value>
            <value>
                <fullName>Gujarati</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interior_Designer__c/fields/Property_Exp_Data__c.field-meta.xml
<CustomField>
    <fullName>Property_Exp_Data__c</fullName>
    <label>Property Exp Data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Interior_Designer__c/fields/Total_Wins__c.field-meta.xml
<CustomField>
    <fullName>Total_Wins__c</fullName>
    <label>Total Wins</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Interior_Designer__c/fields/X0_4_Won_Opportunities__c.field-meta.xml
<CustomField>
    <fullName>X0_4_Won_Opportunities__c</fullName>
    <label>0 - 4 Won Opportunities</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Interior_Designer__c/fields/X4_8_Won_Opportunities__c.field-meta.xml
<CustomField>
    <fullName>X4_8_Won_Opportunities__c</fullName>
    <label>4 - 8 Won Opportunities</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Interior_Designer__c/fields/X8_Won_Opportunities__c.field-meta.xml
<CustomField>
    <fullName>X8_Won_Opportunities__c</fullName>
    <label>8+ Won Opportunities</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Master__c/Master__c.object-meta.xml
<CustomObject>
    <description>This is master object.</description>
    <label>Master</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Master__c/fields/Total_Opportunities__c.field-meta.xml
<CustomField>
    <fullName>Total_Opportunities__c</fullName>
    <label>Total Opportunities</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Master__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Property</fullName>
                <default>true</default>
                <label>Property</label>
            </value>
            <value>
                <fullName>Showroom</fullName>
            </value>
            <value>
                <fullName>Builder</fullName>
            </value>
            <value>
                <fullName>Walk-in Source</fullName>
            </value>
            <value>
                <fullName>Dealer Showroom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master__c/recordTypes/Property.recordType-meta.xml
<RecordType>
    <fullName>Property</fullName>
    <active>true</active>
    <label>Property</label>
</RecordType>

force-app/main/default/objects/Stack_DP_Rank__c/Stack_DP_Rank__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Stack DP Rank</label>
</CustomObject>

force-app/main/default/objects/Stack_DP_Rank__c/fields/Language_Score__c.field-meta.xml
<CustomField>
    <fullName>Language_Score__c</fullName>
    <label>Language Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stack_DP_Rank__c/fields/New_Active_0_4__c.field-meta.xml
<CustomField>
    <fullName>New_Active_0_4__c</fullName>
    <label>New Active 0 - 4</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stack_DP_Rank__c/fields/New_Active_4_8__c.field-meta.xml
<CustomField>
    <fullName>New_Active_4_8__c</fullName>
    <label>New Active 4 - 8</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stack_DP_Rank__c/fields/New_Active_8__c.field-meta.xml
<CustomField>
    <fullName>New_Active_8__c</fullName>
    <label>New Active 8+</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stack_DP_Rank__c/fields/New_Active_Master__c.field-meta.xml
<CustomField>
    <fullName>New_Active_Master__c</fullName>
    <label>New Active Master</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stack_DP_Rank__c/fields/Project_Score__c.field-meta.xml
<CustomField>
    <fullName>Project_Score__c</fullName>
    <label>Project Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stack_DP_Rank__c/fields/Rank_for_Conversion_Percent__c.field-meta.xml
<CustomField>
    <fullName>Rank_for_Conversion_Percent__c</fullName>
    <label>Rank for Conversion Percent</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stack_DP_Rank__c/fields/Rank_for_Won_Opp__c.field-meta.xml
<CustomField>
    <fullName>Rank_for_Won_Opp__c</fullName>
    <label>Rank for Won Opp</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Stack_DP_Rank__c/fields/X10_40_score__c.field-meta.xml
<CustomField>
    <fullName>X10_40_score__c</fullName>
    <label>10 40 score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CalculateRankDP_test.cls
@isTest
public class CalculateRankDP_test{ 
    public static testMethod void calculateRank(){
        Stack_DP_Rank__c stack = new Stack_DP_Rank__c();
        stack.Name = 'Stack DP';
        stack.Project_Score__c = 40;
        stack.Language_Score__c = 20;
        stack.New_Active_0_4__c = 10;
        stack.New_Active_4_8__c = 10;
        stack.New_Active_8__c = 10;
        stack.New_Active_Master__c = 10;
        stack.X10_40_score__c = 20;
        stack.Rank_for_Conversion_Percent__c = 10;
        stack.Rank_for_Won_Opp__c = 30;
        insert stack;
        
        List<Interior_Designer__c> intDesigner = new List<Interior_Designer__c>();
        Interior_Designer__c inte = new Interior_Designer__c();
        inte.Name = 'Test Int';
        inte.Email__c = 'test@google.com';
        inte.X0_4_Won_Opportunities__c = 1;
        inte.X4_8_Won_Opportunities__c = 2;
        inte.X8_Won_Opportunities__c = 3;
        inte.Total_Wins__c = 10;
        inte.Total_Opportunities__c = 50;
        inte.Available_at_Showroom__c = 'Test Showroom 2';
        inte.Property_Exp_Data__c = 'Kanakapura Showroom';
        inte.City__c = 'Bengaluru';
       // inte.Languages_Known__c = 'Hindi';
        intDesigner.add(inte);
        
        Interior_Designer__c inte2 = new Interior_Designer__c();
        inte2.Name = 'Test Int2';
        inte2.Email__c = 'test2@google.com';
        inte2.X0_4_Won_Opportunities__c = 4;
        inte2.X4_8_Won_Opportunities__c = 5;
        inte2.X8_Won_Opportunities__c = 6;
        inte2.Total_Wins__c = 9;
        inte2.Total_Opportunities__c = 50;
        inte2.Available_at_Showroom__c = 'Test Showroom 2';
        inte2.Property_Exp_Data__c = 'Kanakapura Showroom';
        inte2.City__c = 'Bengaluru';
      //  inte2.Languages_Known__c = 'Hindi';
        intDesigner.add(inte2);
        
        Interior_Designer__c inte3 = new Interior_Designer__c();
        inte3.Name = 'Test Int3';
        inte3.Email__c = 'test3@google.com';
        inte3.X0_4_Won_Opportunities__c = 7;
        inte3.X4_8_Won_Opportunities__c = 8;
        inte3.X8_Won_Opportunities__c = 9;
        inte3.Total_Wins__c = 8;
        inte3.Total_Opportunities__c = 50;
        inte3.Available_at_Showroom__c = 'Test Showroom 2';
        inte3.Property_Exp_Data__c = 'Kanakapura Showroom';
        inte3.City__c = 'Bengaluru';
      //  inte3.Languages_Known__c = 'Hindi';
        intDesigner.add(inte3);
        
        insert intDesigner;  
        System.debug('@@@@@@@  '+intDesigner);
        
        
        List<Master__c> master = new List<Master__c>();
        Master__c m = new Master__c();
        m.Name = 'Test Showroom';
        m.Type__c = 'Property';
        master.add(m);
        insert master;
        
        Master__c m1 = new Master__c();
        m1.Name = 'Test Showroom 2';
        m1.Type__c = 'Showroom';
        insert m1;
        
        
        List<Lead> leadList = new List<Lead>();
        lead newLead = new Lead();
        newLead.Email = 'test@test.com';
        newLead.lastName = 'Test';
        newLead.Phone = '1234567890';
        newLead.LeadSource = 'Google Ad';
        newLead.Status = 'Fresh Lead';
        newLead.Property__c = m.Id;
        newLead.Budget_Range__c = '1.5L - 4L';
        newLead.City = 'Bengaluru';
        newLead.Regional_Language_Preference__c = 'Hindi';
        newLead.Appointment_Venue_Square__c = m1.Id;
      //  newLead.Property__c = 'Test Showroom';
        leadList.add(newLead);
        
        lead newLead1 = new Lead();
        newLead1.Email = 'tes3t@test.com';
        newLead1.lastName = 'Test1';
        newLead1.Phone = '1234567800';
        newLead1.LeadSource = 'Google Ad';
        newLead1.Status = 'Fresh Lead';
        newLead1.Regional_Language_Preference__c = 'Hindi';
        newLead1.Property__c = m.Id;
        newLead1.Budget_Range__c = '4L - 6L';
        newLead1.City = 'Bengaluru'; 
        newLead1.Appointment_Venue_Square__c = m1.Id;    
       // newLead1.Property__c = 'Test Showroom';  
        leadList.add(newLead1);
        
        lead newLead2 = new Lead();
        newLead2.Email = 'te89t@test.com';
        newLead2.lastName = 'Test2';
        newLead2.Phone = '1234500000';
        newLead2.LeadSource = 'Google Ad';
        newLead2.Status = 'Fresh Lead';
        newLead2.Regional_Language_Preference__c = 'Hindi';
        newLead2.Property__c = m.Id;
        newLead2.Budget_Range__c = '8L - 10L';
        newLead2.City = 'Bengaluru';  
        newLead2.Appointment_Venue_Square__c = m1.Id;    
       // newLead2.Property__c = 'Test Showroom'; 
        leadList.add(newLead2);
        
        lead newLead3 = new Lead();
        newLead3.Email = 'te89245t@test.com';
        newLead3.lastName = 'Test3';
        newLead3.Phone = '1234567000';
        newLead3.LeadSource = 'Google Ad';
        newLead3.Status = 'Fresh Lead';
        newLead3.Regional_Language_Preference__c = 'Hindi';
        newLead3.Property__c = m.Id;
        newLead3.Budget_Range__c = 'Cx didn\'t disclose';
        newLead3.City = 'Bengaluru'; 
        newLead3.Appointment_Venue_Square__c = m1.Id;  
      //  newLead3.Property__c = 'Test Showroom';    
        leadList.add(newLead3);  
        
        insert leadList; 
        
        CalculateRankDPWrapper cal = new CalculateRankDPWrapper ();
        cal.recordId = inte.Id;
        cal.email = 'test@google.com';
        cal.project = 'Test Master';
        cal.language = 'English';
        cal.languageScore = 20;
        cal.projectScore = 40;
        cal.wonOpp = 1;
        cal.conversionScore = 10;
        cal.rankForConversion = 1;
        cal.conversionPercent = 30;
        cal.wonOppScore = 20;
        cal.rankForWonOpp = 1;
        cal.finalScore = 90;
        cal.finalRank = 1;  
       
       CalculateRankDPWrapper cal2 = new CalculateRankDPWrapper ();
        cal2.recordId = inte2.Id;
        cal2.email = 'test1@google.com';
        cal2.project = 'Test Master';
        cal2.language = 'English';
        cal2.languageScore = 20;
        cal2.projectScore = 40;
        cal2.wonOpp = 1;
        cal2.conversionScore = 10;
        cal2.rankForConversion = 1;
        cal2.conversionPercent = 30;
        cal2.wonOppScore = 10;
        cal2.rankForWonOpp = 1;
        cal2.finalScore = 80;
        cal2.finalRank = 2;        
        
        System.assertEquals(1, cal.finalRank);
        System.assertEquals(2, cal2.finalRank);     
       
       Test.startTest();
       PageReference pageRef = Page.DPButton;       
       Test.setCurrentPage(pageRef);
       pageRef.getParameters().put('id',newLead.id);
       ApexPages.StandardController sc = new ApexPages.standardController(newLead);
       CalculateRankDP  controller = new CalculateRankDP(sc);
       controller.CalculateRank(); 
        
       PageReference pageRef1 = Page.DPButton;       
       Test.setCurrentPage(pageRef1);
       pageRef1.getParameters().put('id',newLead1.id);
       ApexPages.StandardController sc1 = new ApexPages.standardController(newLead1);
       CalculateRankDP  controller1 = new CalculateRankDP(sc1);
       controller1.CalculateRank();
       
       PageReference pageRef2 = Page.DPButton;       
       Test.setCurrentPage(pageRef2);
       pageRef2.getParameters().put('id',newLead2.id);
       ApexPages.StandardController sc2 = new ApexPages.standardController(newLead2);
       CalculateRankDP  controller2 = new CalculateRankDP(sc2);
       controller2.CalculateRank();
       
       PageReference pageRef3 = Page.DPButton;       
       Test.setCurrentPage(pageRef3);
       pageRef3.getParameters().put('id',newLead3.id);
       ApexPages.StandardController sc3 = new ApexPages.standardController(newLead3);
       CalculateRankDP  controller3 = new CalculateRankDP(sc3);
       controller3.CalculateRank(); 
       Test.stopTest();

    }
       
}