force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List Of Operating Cities</description>
    <label>City</label>
</CustomObject>

force-app/main/default/objects/Referrer__c/Referrer__c.object-meta.xml
<CustomObject>
    <label>Referrer</label>
    <nameField>
        <label>Referrer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referrers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referrer__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bengaluru</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>New Delhi</fullName>
            </value>
            <value>
                <fullName>Noida</fullName>
            </value>
            <value>
                <fullName>Gurgaon</fullName>
            </value>
            <value>
                <fullName>Ghaziabad</fullName>
            </value>
            <value>
                <fullName>Thane</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
            <value>
                <fullName>Kolkata</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Referrer__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <label>Phone</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Referrer__c/fields/Referral_Program__c.field-meta.xml
<CustomField>
    <fullName>Referral_Program__c</fullName>
    <label>Referral Program</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ambassador</fullName>
            </value>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Field agent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ReferralProgramToLead_Test.cls
@isTest 
public class ReferralProgramToLead_Test {
    public static testMethod void referral() {
        List<Referrer__c> ref = new List<Referrer__c>();
        Referrer__c r = new Referrer__c();
        r.Name = 'Test';
        r.Email__c = 'test@test.com';
        r.Phone__c = '0000000000';
        r.Referral_Program__c = 'Ambassador';
        r.City__c = 'Pune';
        ref.add(r);
        
        Referrer__c r1 = new Referrer__c();
        r1.Name = 'Test1';
        r1.Email__c = 'test1@test.com';
        r1.Phone__c = '0000000001';
        r1.City__c = 'Pune';
        r1.Referral_Program__c = 'Ambassador';
        
        ref.add(r1);
        insert ref;
        
        lead newLead = new Lead();
        newLead.Email = 'test@test.com';
        newLead.lastName = 'Test';
        newLead.Phone = '1234567890';
        newLead.LeadSource = 'Google Ad';
        newLead.Status = 'Fresh Lead';
        newLead.Budget_Range__c = '1.5L - 4L';
        newLead.City = 'Bengaluru';
        newLead.Regional_Language_Preference__c = 'Hindi';  
        newLead.HL_Referrer_Phone__c = '0000000000';      
        insert newLead;    
        newLead.HL_Referrer_Phone__c = '0000000001';     
        update newLead;
      
    }
}