force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List Of Operating Cities</description>
    <label>City</label>
</CustomObject>

force-app/main/default/objects/WTA_Assignment__c/WTA_Assignment__c.object-meta.xml
<CustomObject>
    <label>WTA Assignment</label>
    <nameField>
        <label>WTA Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WTA Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WTA_Assignment__c/fields/Agent_Campaign_Name__c.field-meta.xml
<CustomField>
    <fullName>Agent_Campaign_Name__c</fullName>
    <formula>User__r.Cloud_Agent_Campaign_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Agent Campaign Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WTA_Assignment__c/fields/Agent_Email__c.field-meta.xml
<CustomField>
    <fullName>Agent_Email__c</fullName>
    <formula>User__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Agent Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WTA_Assignment__c/fields/Assignment__c.field-meta.xml
<CustomField>
    <fullName>Assignment__c</fullName>
    <formula>Daily_Assignment__c / Daily_Limit__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Assignment %</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/WTA_Assignment__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bengaluru</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>New Delhi</fullName>
            </value>
            <value>
                <fullName>Noida</fullName>
            </value>
            <value>
                <fullName>Gurgaon</fullName>
            </value>
            <value>
                <fullName>Ghaziabad</fullName>
            </value>
            <value>
                <fullName>Thane</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
            <value>
                <fullName>Kolkata</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WTA_Assignment__c/fields/City_Campaign_Name__c.field-meta.xml
<CustomField>
    <fullName>City_Campaign_Name__c</fullName>
    <label>City_Campaign Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BLR_AutoLead</fullName>
            </value>
            <value>
                <fullName>BLR-AutoLead-Pool2</fullName>
            </value>
            <value>
                <fullName>CHN_AutoLead-Pool2</fullName>
            </value>
            <value>
                <fullName>HYD_AutoLead-Pool2</fullName>
            </value>
            <value>
                <fullName>Kolkata_AutoLead-Pool2</fullName>
            </value>
            <value>
                <fullName>MUM_AutoLead-Pool2</fullName>
            </value>
            <value>
                <fullName>Pune_AutoLead-Pool2</fullName>
            </value>
            <value>
                <fullName>NCR_AutoLead-Pool2</fullName>
            </value>
            <value>
                <fullName>HYD_AutoLead</fullName>
            </value>
            <value>
                <fullName>CHN_AutoLead</fullName>
            </value>
            <value>
                <fullName>NCR_AutoLead</fullName>
            </value>
            <value>
                <fullName>MUM_AutoLead</fullName>
            </value>
            <value>
                <fullName>Pune_AutoLead</fullName>
            </value>
            <value>
                <fullName>Kolkata_AutoLead</fullName>
            </value>
            <value>
                <fullName>Others_AutoLead</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WTA_Assignment__c/fields/Daily_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Daily_Assignment__c</fullName>
    <label>Daily Assignment</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WTA_Assignment__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Group A</fullName>
            </value>
            <value>
                <fullName>Group B</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WTA_Assignment__c/fields/Monthly_Assignments__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Assignments__c</fullName>
    <label>Monthly Assignments</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WTA_Assignment__c/fields/Monthly_Limit__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Limit__c</fullName>
    <label>Monthly Limit</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WTA_Assignment__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>WTA_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WTA_Assignment__c/fields/Weekly_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Weekly_Assignment__c</fullName>
    <label>Weekly Assignment</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WTA_Assignment__c/fields/Weekly_Limit__c.field-meta.xml
<CustomField>
    <fullName>Weekly_Limit__c</fullName>
    <label>Weekly Limit</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AssignLeadToWTAGroup.cls
Public class AssignLeadToWTAGroup{ 
    
    Public static void  AssignLeadToWTAGroupA_GroupB(lead objectLead){  
        
        Lead ObjLead = new Lead();
        list<WTA_Assignment__c> lstAssignmentGroupA = new list<WTA_Assignment__c>();
        
        if(objectLead != NULL){  
            system.debug('++++objectLead++++'+objectLead.id);
            ObjLead = objectLead;
            if((objLead.Status =='Fresh Lead' && objLead.sub_status__c == 'New' &&
               objLead.Pushed_To_Ozone_1st_Time__c == false && objLead.Assigned_to_Resi_ASM__c == false && 
               objLead.Assigned_to_WTA__c == false) ||(objLead.Status =='Fresh Lead' && objLead.sub_status__c == 'Re-Landed')||
               (objLead.Status =='Appointment Fixed'  && objLead.Pushed_To_Ozone_1st_Time__c == false && 
               objLead.Assigned_to_Resi_ASM__c == false )){
            
                // Group A Details 
                lstAssignmentGroupA = getGroupADetails(ObjLead);

                if(lstAssignmentGroupA != NULL && !lstAssignmentGroupA.isEmpty()){
                    system.debug('List Of Group A Records'+lstAssignmentGroupA);
                    Map<String,WTA_Assignment__c> MapGroupA_Assignmnet  = new Map<String,WTA_Assignment__c>();
                    for(WTA_Assignment__c obj:lstAssignmentGroupA){
                        MapGroupA_Assignmnet.put(obj.Agent_Email__c,obj);
                    }
                    Lead_Assignment_Helper.checkWTAStatus(objLead,MapGroupA_Assignmnet,lstAssignmentGroupA[0].City_Campaign_Name__c);
                }
                //
                else{
                    list<WTA_Assignment__c> lstGroupB_Assignment = getGroupBDetails(objLead);
                    if(lstGroupB_Assignment != NULL && !lstGroupB_Assignment.isEmpty()){
                        system.debug('List Of Group B Records'+lstGroupB_Assignment);
                        Map<String,WTA_Assignment__c> MapGroupB_Assignmnet  = new Map<String,WTA_Assignment__c>();
                        for(WTA_Assignment__c obj:lstGroupB_Assignment){
                            MapGroupB_Assignmnet.put(obj.Agent_Email__c,obj);
                        }
                       Lead_Assignment_Helper.checkWTAStatus(objLead,MapGroupB_Assignmnet,lstGroupB_Assignment[0].City_Campaign_Name__c);
                    }   
                }
            }    
            else{
                    // If Status is not Matching 
            }     
            
           
        }
        else{
            // If lead is  null 
        }

    }

        /*
    Used to Query the lead Assignment of Group A
    */

    Public static List<WTA_Assignment__c> getGroupADetails(lead objlead){
        list<WTA_Assignment__c> lstAssignment = [Select id,Name,Assignment__c,City__c,Daily_Assignment__c,Daily_Limit__c,Group__c,
                                        IsActive__c,Monthly_Assignments__c,Monthly_Limit__c,User__c,Weekly_Assignment__c,Weekly_Limit__c,
                                        Agent_Campaign_Name__c,City_Campaign_Name__c,Agent_Email__c
                                        from WTA_Assignment__c 
                                        where City__c =: objLead.city and Group__c = 'Group A' and 
                                        Assignment__c <100 and IsActive__c = true
                                        Order by Assignment__c desc];
        system.debug('------Group A Assignment lstAssignment-------'+lstAssignment);                                
        return lstAssignment;
        
    }

    /*
    Used to Query the lead Assignment of Group B
    */
    Public static List<WTA_Assignment__c> getGroupBDetails(lead objlead){
       list<WTA_Assignment__c> lstAssignment = [Select id,Name,Assignment__c,City__c,Daily_Assignment__c,Daily_Limit__c,Group__c,
                                                        IsActive__c,Monthly_Assignments__c,Monthly_Limit__c,User__c,Weekly_Assignment__c,Weekly_Limit__c,
                                                        Agent_Campaign_Name__c,City_Campaign_Name__c,Agent_Email__c
                                                        from WTA_Assignment__c 
                                                        where City__c includes (:objLead.city)  and Group__c = 'Group B' and 
                                                        IsActive__c = true
                                                        Order by Assignment__c desc]; 
        system.debug('------Group B Assignment lstAssignment-------'+lstAssignment);   
        return lstAssignment;
        
    }

    Public static void asssigntoGroupB(lead objlead){
        map<String,WTA_Assignment__c> mapAssignment = new map<String,WTA_Assignment__c>();
        list<WTA_Assignment__c> lstAssignment = [Select id,Name,Assignment__c,City__c,Daily_Assignment__c,Daily_Limit__c,Group__c,
                                                        IsActive__c,Monthly_Assignments__c,Monthly_Limit__c,User__c,Weekly_Assignment__c,Weekly_Limit__c,
                                                        Agent_Campaign_Name__c,City_Campaign_Name__c,Agent_Email__c
                                                        from WTA_Assignment__c 
                                                        where City__c includes (:objLead.city)  and Group__c = 'Group B' and 
                                                        IsActive__c = true
                                                        Order by Assignment__c desc]; 
        system.debug('------Group B Assignment lstAssignment-------'+lstAssignment);   
        if(!lstAssignment.isEmpty()){
            for(WTA_Assignment__c objassign:lstAssignment){
                mapAssignment.put(objassign.Agent_Email__c,objassign);
            }
            Lead_Assignment_Helper.checkWTAStatus(objLead,mapAssignment,lstAssignment[0].City_Campaign_Name__c);
        }
    }
}