force-app/main/default/objects/Lead_Assignment__c/Lead_Assignment__c.object-meta.xml
<CustomObject>
    <label>Lead Assignment</label>
    <nameField>
        <label>Lead Assignment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Assignment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead_Assignment__c/fields/Assign_Percent__c.field-meta.xml
<CustomField>
    <fullName>Assign_Percent__c</fullName>
    <label>Assign Percent</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Lead_Assignment__c/fields/Number_of_Leads__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Leads__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Leads</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead_Assignment__c/fields/Round_Robin__c.field-meta.xml
<CustomField>
    <fullName>Round_Robin__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Round Robin</label>
    <referenceTo>Round_Robin__c</referenceTo>
    <relationshipLabel>Lead Assignment</relationshipLabel>
    <relationshipName>Lead_Assignment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead_Assignment__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Lead_Assignment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Queue_Custom_Setting__c/Queue_Custom_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Queue Custom Setting</label>
</CustomObject>

force-app/main/default/objects/Queue_Custom_Setting__c/fields/Queue_Count__c.field-meta.xml
<CustomField>
    <fullName>Queue_Count__c</fullName>
    <label>Queue Count</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Queue_Custom_Setting__c/fields/Queue_Setting__c.field-meta.xml
<CustomField>
    <fullName>Queue_Setting__c</fullName>
    <label>Queue Setting</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Round_Robin__c/Round_Robin__c.object-meta.xml
<CustomObject>
    <description>This is created to define user within each Queue for workload and city</description>
    <label>Round Robin</label>
    <nameField>
        <label>Round Robin  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Round Robin</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Round_Robin__c/fields/Queue_Name__c.field-meta.xml
<CustomField>
    <fullName>Queue_Name__c</fullName>
    <label>Queue Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Round_Robin__c/fields/Total_Leads__c.field-meta.xml
<CustomField>
    <fullName>Total_Leads__c</fullName>
    <label>Total Leads</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RR_Deactivate_Time__c/RR_Deactivate_Time__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This setting is use to capture the date and time of round robin deactivation.</description>
    <label>RR Deactivate Time</label>
</CustomObject>

force-app/main/default/objects/RR_Deactivate_Time__c/fields/Deactivation_Time__c.field-meta.xml
<CustomField>
    <fullName>Deactivation_Time__c</fullName>
    <label>Deactivation Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/RR_Deactivate_Time__c/fields/Error_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Error_Email_Address__c</fullName>
    <label>Error Email Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/RR_Deactivate_Time__c/fields/Pattern__c.field-meta.xml
<CustomField>
    <fullName>Pattern__c</fullName>
    <label>Pattern</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RR_Deactivate_Time__c/fields/Reporting_Time__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Time__c</fullName>
    <label>Reporting Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LeadAssignmentRemovalBatch_Test.cls
@isTest
public class LeadAssignmentRemovalBatch_Test {
    Public static testMethod void testLeadAssignmentRemovalBatch1(){ 
        Map<String,Id> profileData = new Map<String,Id>();
        RR_Deactivate_Time__c objRR = new RR_Deactivate_Time__c();
        objRR.Name = 'Daily Time';
        objRR.Reporting_Time__c = 9.0;
        objRR.Pattern__c = '9,10,11';
        objRR.Deactivation_Time__c = Date.today().addDays(-1);
        objRR.Error_Email_Address__c = 'Test@gmail.com,test2@gmail.com';
        insert objRR;
        Queue_Custom_Setting__c objQueue = new Queue_Custom_Setting__c();
        objQueue.Queue_Setting__c = 'BLR:BangaloreTeam,CHN:ChennaiTeam,HYD:HyderabadTeam,MUM:MumbaiTeam,NCR:GurgaonTeam,NCR:NewDelhiTeam';
        objQueue.Queue_Count__c = '';
        objQueue.Name= 'Lead Queue';
        
        Insert objQueue;
        for(Profile obj : [SELECT Name,Id FROM Profile WHERE Name IN ('WTA Profile','Square Sales Profile','Square Profile','Design Partner Profile')]){
            profileData.put(obj.Name,obj.Id);
        }
        Account ac = new Account(name ='Grazitti') ;
        insert ac; 
        
        User wta_user=leadUtil_Test.inserUser('tetta1@gmail.com','TesWT1','',profileData.get('WTA Profile')); 
        insert wta_user;
        User wta_user1=leadUtil_Test.inserUser('tetta2@gmail.com','TesWT2','',profileData.get('WTA Profile')); 
        insert wta_user1;
        User wta_user2=leadUtil_Test.inserUser('tetta3@gmail.com','TesWT2','',profileData.get('WTA Profile')); 
        insert wta_user2;
       
       //assign users in round robin manner to leads
        Group grp=new group();
        grp.Name='BangaloreTeam';
        grp.Type='Queue';
        insert grp;
        
        System.runAs(new User(Id = UserInfo.getUserId())) {   
            QueueSobject testQueue = new QueueSObject(QueueId = grp.Id, SobjectType = 'Lead');
            insert testQueue;
        }
      
            
        Round_Robin__c roundRobin=new Round_Robin__c(Name='BangaloreTeam',Queue_Name__c='BangaloreTeam',Total_Leads__c=45);
        insert roundRobin;
        
           
        Lead_Assignment__c leadAssign=new Lead_Assignment__c(Name='tetWta1@gmail.com',Round_Robin__c=roundRobin.id,User__c=wta_user.Id,Assign_Percent__c=0,Number_of_Leads__c=0);
        insert leadAssign;
        
        Lead_Assignment__c leadAssign1=new Lead_Assignment__c(Name='tetWta2@gmail.com',Round_Robin__c=roundRobin.id,User__c=wta_user1.Id,Assign_Percent__c=0,Number_of_Leads__c=0);
        insert leadAssign1;
        
        Lead_Assignment__c leadAssign2=new Lead_Assignment__c(Name='tetWta3@gmail.com',Round_Robin__c=roundRobin.id,User__c=wta_user2.Id,Assign_Percent__c=0,Number_of_Leads__c=0);
        insert leadAssign2;
        
                 
         Test.StartTest();
           Database.executeBatch(new LeadAssignmentRemovalBatch ());
         
         Test.StopTest();
    }
}