force-app/main/default/objects/Lead_Assignment__c/Lead_Assignment__c.object-meta.xml
<CustomObject>
    <label>Lead Assignment</label>
    <nameField>
        <label>Lead Assignment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Assignment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead_Assignment__c/fields/Assign_Percent__c.field-meta.xml
<CustomField>
    <fullName>Assign_Percent__c</fullName>
    <label>Assign Percent</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Lead_Assignment__c/fields/Number_of_Leads__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Leads__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Leads</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead_Assignment__c/fields/Round_Robin__c.field-meta.xml
<CustomField>
    <fullName>Round_Robin__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Round Robin</label>
    <referenceTo>Round_Robin__c</referenceTo>
    <relationshipLabel>Lead Assignment</relationshipLabel>
    <relationshipName>Lead_Assignment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead_Assignment__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Lead_Assignment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Queue_Custom_Setting__c/Queue_Custom_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Queue Custom Setting</label>
</CustomObject>

force-app/main/default/objects/Queue_Custom_Setting__c/fields/Queue_Count__c.field-meta.xml
<CustomField>
    <fullName>Queue_Count__c</fullName>
    <label>Queue Count</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Round_Robin__c/Round_Robin__c.object-meta.xml
<CustomObject>
    <description>This is created to define user within each Queue for workload and city</description>
    <label>Round Robin</label>
    <nameField>
        <label>Round Robin  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Round Robin</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RR_Deactivate_Time__c/RR_Deactivate_Time__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This setting is use to capture the date and time of round robin deactivation.</description>
    <label>RR Deactivate Time</label>
</CustomObject>

force-app/main/default/objects/RR_Deactivate_Time__c/fields/Deactivation_Time__c.field-meta.xml
<CustomField>
    <fullName>Deactivation_Time__c</fullName>
    <label>Deactivation Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/LeadAssignmentRemovalBatch.cls
global class LeadAssignmentRemovalBatch implements Database.Batchable<sObject>, Database.Stateful{
    global string query;
    global RR_Deactivate_Time__c RRDT{get;set;}
    List<Lead_Assignment__c> lstUpdatedLeadAssignment = new List<Lead_Assignment__c>();
    global LeadAssignmentRemovalBatch(){
        query = 'Select Id,User__c,Number_of_Leads__c,Assign_Percent__c,Round_Robin__c From Lead_Assignment__c';
        
    }
    
     global Database.QueryLocator start(Database.BatchableContext BC){
        
        return Database.getQueryLocator(query);
    }
    
      global void execute(Database.BatchableContext BC, List<Lead_Assignment__c> lstLeadAssignment){
          RRDT = RR_Deactivate_Time__c.getvalues('Daily Time');
          for(Lead_Assignment__c objLA : lstLeadAssignment){
             objLA.Assign_Percent__c = 0;
             objLA.Number_of_Leads__c = 0; 
             lstUpdatedLeadAssignment.add(objLA);
          }
          try{ 
         if(!lstUpdatedLeadAssignment.isEmpty()){
             update lstUpdatedLeadAssignment;
             }system.debug('-------lstUpdatedLeadAssignment-----------'+lstUpdatedLeadAssignment);
        }catch(exception exp){
            system.debug('-------exp start-----------'+exp.getmessage());
        } 
           
      }
    
     global void finish(Database.BatchableContext BC){
        try{
            Queue_Custom_Setting__c queueSetting = Queue_Custom_Setting__c.getvalues('Lead Queue');
            queueSetting.Queue_Count__c = '';
            RRDT.Deactivation_Time__c = System.Now();
            update RRDT;
            update queueSetting;
        }catch(Exception exp){
            system.debug('-------exp finish-----------'+exp.getmessage());
            
        }
    }
    

    
    
    
    
    
    
}