force-app/main/default/objects/Referrer__c/Referrer__c.object-meta.xml
<CustomObject>
    <label>Referrer</label>
    <nameField>
        <label>Referrer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referrers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referrer__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <label>Phone</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Referrer__c/fields/Property_Name__c.field-meta.xml
<CustomField>
    <fullName>Property_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Property Name</label>
    <referenceTo>Master__c</referenceTo>
    <relationshipLabel>Referrers</relationshipLabel>
    <relationshipName>Referrers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referrer__c/fields/Referral_Program__c.field-meta.xml
<CustomField>
    <fullName>Referral_Program__c</fullName>
    <label>Referral Program</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ambassador</fullName>
            </value>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Field agent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ReferralProgramToLead.cls
public class ReferralProgramToLead {
    public static void referralUpdate(Map<Id,Lead> newMap, Map<Id,Lead> oldMap) {
        Set<String> phoneSet = new Set<String>();
        Map<String, Referrer__c> referrerMap = new Map<String, Referrer__c>();
        
        for(Lead l : newMap.values()) {
            if(l.HL_Referrer_Phone__c != null) {
                phoneSet.add(l.HL_Referrer_Phone__c);
            }
        }
        
        List<Referrer__c> referrerList = [select id, name, Email__c, Phone__c, Property_Name__c, Referral_Program__c from Referrer__c where Phone__c =: phoneSet];
        if(referrerList.size() > 0) {            
            for(Referrer__c ref : referrerList) {
                referrerMap.put(ref.Phone__c, ref);
            }
        } 
        
        if(!referrerMap.isEmpty()){
            for(Lead l : newMap.values()) {               
                if(l.HL_Referrer_Phone__c != null && oldMap.get(l.id).HL_Referrer_Phone__c  != l.HL_Referrer_Phone__c) {               
                    Referrer__c ref = referrerMap.get(l.HL_Referrer_Phone__c);
                    l.Referral_Program__c = ref.Referral_Program__c;
                }                                       
            }
        }   
        else {
            for(Lead l : newMap.values()) {
                l.Referral_Program__c = null;
            }
        }           
    }
    
    public static void referralInsert(List<Lead> newMap) {
        Set<String> phoneSet = new Set<String>();
        Map<String, Referrer__c> referrerMap = new Map<String, Referrer__c>();
        
        for(Lead l : newMap) {
            if(l.HL_Referrer_Phone__c != null) {
                phoneSet.add(l.HL_Referrer_Phone__c);
            }
        }
        
        List<Referrer__c> referrerList = [select id, name, Email__c, Phone__c, Property_Name__c, Referral_Program__c from Referrer__c where Phone__c =: phoneSet];
        if(referrerList.size() > 0) {
            
            for(Referrer__c ref : referrerList) {
                referrerMap.put(ref.Phone__c, ref);
            }
        } 
        
        if(!referrerMap.isEmpty()){
            for(Lead l : newMap) {
                if(l.HL_Referrer_Phone__c != null) {
                    Referrer__c ref = referrerMap.get(l.HL_Referrer_Phone__c);
                    l.Referral_Program__c = ref.Referral_Program__c;
                }
            }
        }
       
    }
}