force-app/main/default/objects/Recommended_Meeting_Type__c/Recommended_Meeting_Type__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Updates Recommended meeting Type on Lead</description>
    <label>Recommended Meeting Type</label>
</CustomObject>

force-app/main/default/objects/Recommended_Meeting_Type__c/fields/Max_Distance__c.field-meta.xml
<CustomField>
    <fullName>Max_Distance__c</fullName>
    <label>Max Distance ( =&lt; )</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Recommended_Meeting_Type__c/fields/Meeting_Type__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Type__c</fullName>
    <label>Meeting Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recommended_Meeting_Type__c/fields/Min_Distance__c.field-meta.xml
<CustomField>
    <fullName>Min_Distance__c</fullName>
    <label>Min Distance ( &gt; )</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Recommended_Meeting_Type__c/fields/ShowRoom_Name__c.field-meta.xml
<CustomField>
    <fullName>ShowRoom_Name__c</fullName>
    <label>ShowRoom Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Recommended_Meeting_Type_Test.cls
@isTest
public class Recommended_Meeting_Type_Test{
    public static testMethod void Success() {
    
        Recommended_Meeting_Type__c hsrShowroom = new Recommended_Meeting_Type__c();
        hsrShowroom.Max_Distance__c = 10;
        hsrShowroom.Meeting_Type__c = 'RV';
        hsrShowroom.Min_Distance__c =  0;
        hsrShowroom.ShowRoom_Name__c = 'HSR Showroom';
        hsrShowroom.Name = 'HSR Showroom 0 - 10';
        insert hsrShowroom;
        
    
        Lead l = TestData_Factory.CreateFreshLead(False);
        insert l;
        
        map<id,Lead> newMap = new map<id,Lead>();
        map<id,Lead> OldMap= new map<id,Lead>();
        OldMap.put(l.id,l);
        
        
        lead l2 = new Lead();
        l2.id = l.id;
        l2.Closest_Showroom__c = 'HSR Showroom 8.8km';
        newMap.put(l2.id,l2);
        
        
        
        test.starttest();
        Recommended_Meeting_Type.updateMeetingType(newMap,OldMap);
            //l.Closest_Showroom__c = 'HSR Showroom 8.8km';
            //update l;
           //lead la = [select id,Name,Recommended_Meeting_Type__c from lead where id =:l.id];
           //system.assertequals('RV',la.Recommended_Meeting_Type__c);
        test.stoptest();
    }
 }