force-app/main/default/objects/Customer_Bill__c/Customer_Bill__c.object-meta.xml
<CustomObject>
    <label>Bill</label>
    <nameField>
        <displayFormat>Bill-{00000}</displayFormat>
        <label>Bill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Bill__c/fields/Amount_to_be_paid__c.field-meta.xml
<CustomField>
    <fullName>Amount_to_be_paid__c</fullName>
    <description>amount to be paid value is calculated from Opportunity amount based on 10%, 40%, 50%</description>
    <label>Amount to be paid</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Customer_Bill__c/fields/Bill_Status__c.field-meta.xml
<CustomField>
    <fullName>Bill_Status__c</fullName>
    <label>Bill Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>10% Payment Received</fullName>
            </value>
            <value>
                <fullName>10% Payment Approved</fullName>
            </value>
            <value>
                <fullName>10% Payment Rejected</fullName>
            </value>
            <value>
                <fullName>40% Payment Received</fullName>
            </value>
            <value>
                <fullName>40% Payment Approved</fullName>
            </value>
            <value>
                <fullName>40% Payment Rejected</fullName>
            </value>
            <value>
                <fullName>50% Payment Received</fullName>
            </value>
            <value>
                <fullName>50% Payment Approved</fullName>
            </value>
            <value>
                <fullName>50% Payment Rejected</fullName>
            </value>
            <value>
                <fullName>Full and Final Settlement Received</fullName>
            </value>
            <value>
                <fullName>Full and Final Settlement Approved</fullName>
            </value>
            <value>
                <fullName>Full and Final Settlement Rejected</fullName>
            </value>
            <value>
                <fullName>10% Intermediate</fullName>
            </value>
            <value>
                <fullName>10% Approved</fullName>
            </value>
            <value>
                <fullName>40% Intermediate</fullName>
            </value>
            <value>
                <fullName>40% Approved</fullName>
            </value>
            <value>
                <fullName>50% Intermediate</fullName>
            </value>
            <value>
                <fullName>50% Approved</fullName>
            </value>
            <value>
                <fullName>100% Intermediate</fullName>
            </value>
            <value>
                <fullName>100% Approved</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Customer_Bill__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Bills</relationshipLabel>
    <relationshipName>Bills</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>URLString For the Opportunity Record</description>
    <label>URLString</label>
</CustomObject>

force-app/main/default/objects/Payment_Milestone__c/Payment_Milestone__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Payment Milestone Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Milestone__c/fields/Bill__c.field-meta.xml
<CustomField>
    <fullName>Bill__c</fullName>
    <label>Bill</label>
    <referenceTo>Customer_Bill__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Milestone__c/fields/Payment_Mode__c.field-meta.xml
<CustomField>
    <fullName>Payment_Mode__c</fullName>
    <label>Payment Mode</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>DD</fullName>
            </value>
            <value>
                <fullName>Wire Transfer</fullName>
            </value>
            <value>
                <fullName>NEFT/RTGS</fullName>
            </value>
            <value>
                <fullName>CC Avenue</fullName>
            </value>
            <value>
                <fullName>Paytm</fullName>
            </value>
            <value>
                <fullName>Kissht</fullName>
            </value>
            <value>
                <fullName>Card Swipe</fullName>
            </value>
            <value>
                <fullName>HDFC</fullName>
            </value>
            <value>
                <fullName>PayU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Milestone__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Installment 1</fullName>
            </value>
            <value>
                <fullName>Installment 2</fullName>
            </value>
            <value>
                <fullName>Installment 3</fullName>
            </value>
            <value>
                <fullName>Installment 4</fullName>
            </value>
            <value>
                <fullName>Final Installment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/paymentTrigger_test.cls
@isTest
public class paymentTrigger_test{
    static testMethod void testPaymentMilesone(){
    
        SC_MI_TestHandler.insertIsTriggerExecute();
        SC_MI_TestHandler.insertCustomDate();
        
      /* Profile pm_profile = [SELECT Id FROM Profile WHERE Name = 'Project Manager Profile' LIMIT 1];
        list<User> pm_user = [SELECT id,Name, Email,Internal_buddy__c FROM User WHERE ProfileId = :pm_profile.Id and isActive = True];
        system.debug('pm_user='+pm_user);
        
        Profile smm_profile = [SELECT Id FROM Profile WHERE Name = 'SMM Profile' LIMIT 1];
        list<User> smm_user = [SELECT id,Name, Email,Internal_buddy__c FROM User WHERE ProfileId = :smm_profile.Id and isActive = True];
        system.debug('smm_user='+smm_user);*/
        
        Profile agent_profile = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        list<User> agent_user = [SELECT id,Name, Email,Internal_buddy__c FROM User WHERE ProfileId = :agent_profile.Id and isActive = True];
        system.debug('agent_user='+agent_user);
        
        Profile fac_profile = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        list<User> fac_coordinator = [SELECT id,Name, Email,Internal_buddy__c FROM User WHERE ProfileId = :fac_profile.Id and isActive = True];
        system.debug('fac_coordinator ='+fac_coordinator );
        
        Profile dp_profile = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        list<User> dp_prof = [SELECT id,Name, Email,Internal_buddy__c FROM User WHERE ProfileId = :dp_profile.Id and isActive = True];
        system.debug('dp_prof ='+dp_prof );
        
      /*  UserRole squareMagUser=[SELECT Id,Name FROM UserRole WHERE Name='Square Showroom Manager Partner User' limit 1];
        User managerUser=[SELECT id,Name, Email,Internal_Buddy__c FROM User WHERE UserRoleId=:squareMagUser.id];*/
        
        Profile finance_profile = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
        List<User> finance_user = [SELECT id, Email FROM User WHERE ProfileId = : finance_profile.Id ];
 
        Profile squareMag_profile = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        list<User> managerUser=[SELECT id,Name, Email,Internal_buddy__c FROM User WHERE ProfileId =:squareMag_profile.id and isActive = True];
        system.debug('*****square manager*****'+managerUser[0]);
 
       // RecordType recType=[SELECT Id FROM RecordType WHERE Name='Person Account'];
        Account personAcc=new Account(LastName='Anand',PersonEmail='Anand@gmail.com',phone='0801231541');
        insert personAcc;
       
        Opportunity opp=new Opportunity(Name='Vijay',AccountId=personAcc.Id,stageName='Initial Quote Sent',
                                        closeDate=system.today());
       // insert opp;
        
        opp.StageName='Initial Quote Approved';
        opp.Amount=100;
       // opp.SMM__c=smm_user[0].id;
       // opp.PM__c=pm_user[0].id;
        opp.Square_Showroom_Agent__c=agent_user[0].Id;
        opp.Square_Showroom_Manager__c=managerUser[0].Id;
        opp.customer_email__c='John@gmail.com';
        insert opp;
        
      //  opportunity opptnity=[SELECT id, name, stageName,sub_status__c,customer_email__c FROM Opportunity WHERE Id=:opp.id];
      //  system.assert(opptnity.customer_email__c =='Anand@gmail.com');
        
        Customer_Bill__c custBill=new Customer_Bill__c(Opportunity__c=opp.id, Amount_to_be_paid__c=10);
        insert custBill;
        
        
        Payment_Milestone__c payMile;
       // system.runAs(finance_user[0]){
            payMile=new Payment_Milestone__c(Bill__c=custBill.id,Payment_Mode__c='Wire Transfer',Payment_Type__c='Final Installment');
            insert payMile;
     //   }
         opp.stageName='D4 initiated';
       // update opp;
        
        opp.stageName='Full and Final Settlement Received';
        update opp;
        
        Customer_Bill__c custBill4=new Customer_Bill__c(Opportunity__c=opp.id, Amount_to_be_paid__c=10);
        insert custBill4;
        
        custBill4.bill_status__c='Full and Final Settlement Received';
        custBill4.customer_email__c=opp.customer_email__c;
        update custBill4;
         
       /* Customer_Bill__c custBill5=[SELECT id, name,customer_email__c,Amount_to_be_paid__c,Opportunity__c FROM Customer_Bill__c WHERE Id=:custBill4.id];
        system.debug('custBill5.customer_email__c='+custBill5.customer_email__c);*/
        
        Payment_Milestone__c payMile1;
      //  system.runAs(finance_user[0]){
            payMile1=new Payment_Milestone__c(Bill__c=custBill4.id,Payment_Mode__c='Wire Transfer',Payment_Type__c='Final Installment');
            insert payMile1;
       //  }
        
        payMile1.Payment_Type__c='Installment 1';
        update payMile1;
        
        Payment_Milestone__c payMileStone=[SELECT id,customer_email__c FROM Payment_Milestone__c WHERE id=:payMile1.id];
        system.debug(payMileStone.customer_email__c);
        
        try{
            Payment_Milestone__c payMile2=new Payment_Milestone__c(Bill__c=custBill4.id,Payment_Mode__c='Wire Transfer',Payment_Type__c='Final Installment');
            insert payMile2;
       }catch(DMLexception e){
         //  system.assertEquals('Record with Payment Type Final Installment already exists. Please, change the type and Save again.','Record with Payment Type Final Installment already exists. Please, change the type and Save again.');
         System.assert(e.getMessage().contains('Record with Payment Type Final Installment already exists. Please, change the type and Save again.'),e.getMessage());
             
       }
    }
    static testMethod void testPaymentMilesone1(){
    
        SC_MI_TestHandler.insertIsTriggerExecute();
        SC_MI_TestHandler.insertCustomDate();
        Profile agent_profile = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        list<User> agent_user = [SELECT id,Name, Email,Internal_buddy__c FROM User WHERE ProfileId = :agent_profile.Id and isActive = True];
        system.debug('agent_user='+agent_user);
        
        Profile fac_profile = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        list<User> fac_coordinator = [SELECT id,Name, Email,Internal_buddy__c FROM User WHERE ProfileId = :fac_profile.Id and isActive = True];
        system.debug('fac_coordinator ='+fac_coordinator );
        
        Profile dp_profile = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        list<User> dp_prof = [SELECT id,Name, Email,Internal_buddy__c FROM User WHERE ProfileId = :dp_profile.Id and isActive = True];
        system.debug('dp_prof ='+dp_prof );
        
        Profile finance_profile = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
        List<User> finance_user = [SELECT id, Email FROM User WHERE ProfileId = : finance_profile.Id ];
 
        Profile squareMag_profile = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        list<User> managerUser=[SELECT id,Name, Email,Internal_buddy__c FROM User WHERE ProfileId =:squareMag_profile.id and isActive = True];
        system.debug('*****square manager*****'+managerUser[0]);
 
        Account personAcc=new Account(LastName='Anand',PersonEmail='Anand@gmail.com',phone='0801231541');
        insert personAcc;
       
        Opportunity opp=new Opportunity(Name='Vijay',AccountId=personAcc.Id,stageName='Initial Quote Sent',
                                        closeDate=system.today());
        
        
        opp.StageName='Initial Quote Approved';
        opp.Amount=100;
        //opp.SMM__c=smm_user[0].id;
        //opp.PM__c=pm_user[0].id;
        opp.Square_Showroom_Agent__c=agent_user[0].Id;
        opp.Square_Showroom_Manager__c=managerUser[0].Id;
        opp.customer_email__c='John@gmail.com';
       insert opp;
        
      //  opportunity opptnity=[SELECT id, name, stageName,sub_status__c,customer_email__c FROM Opportunity WHERE Id=:opp.id];
      //  system.assert(opptnity.customer_email__c =='Anand@gmail.com');
        
        Customer_Bill__c custBill=new Customer_Bill__c(Opportunity__c=opp.id, Amount_to_be_paid__c=10);
        insert custBill;
        
        Payment_Milestone__c payMile;
        system.runAs(finance_user[0]){
            payMile=new Payment_Milestone__c(Bill__c=custBill.id,Payment_Mode__c='Wire Transfer',Payment_Type__c='Final Installment');
            insert payMile;
        }
        
        payMile.Payment_Type__c='Final Installment';
        update payMile;
        
        try{
         Payment_Milestone__c  payMileDup=new Payment_Milestone__c(Bill__c=custBill.id,Payment_Mode__c='Wire Transfer',Payment_Type__c='Final Installment');
            insert payMileDup;
         }catch(DMLException e){
         }  
        opp.stageName='D4 initiated';
       // update opp;
        
        opp.stageName='Full and Final Settlement Received';
        update opp;
        
        Customer_Bill__c custBill4=new Customer_Bill__c(Opportunity__c=opp.id, Amount_to_be_paid__c=10);
        insert custBill4;
        
        custBill4.bill_status__c='Full and Final Settlement Received';
        custBill4.customer_email__c=opp.customer_email__c;
        update custBill4;
         
       /* Customer_Bill__c custBill5=[SELECT id, name,customer_email__c,Amount_to_be_paid__c,Opportunity__c FROM Customer_Bill__c WHERE Id=:custBill4.id];
        system.debug('custBill5.customer_email__c='+custBill5.customer_email__c);*/
        
        Payment_Milestone__c payMile1;
        system.runAs(finance_user[1]){
            payMile1=new Payment_Milestone__c(Bill__c=custBill4.id,Payment_Mode__c='Wire Transfer',Payment_Type__c='Final Installment');
            insert payMile1;
        }
        payMile1.Payment_Type__c='Final Installment';
        try{
            update payMile1;
            Payment_Milestone__c payMileDup1=new Payment_Milestone__c(Bill__c=custBill4.id,Payment_Mode__c='Wire Transfer',Payment_Type__c='Final Installment');
            insert payMileDup1;
        }
        catch(DMLException e){
        }
        Payment_Milestone__c payMileStone=[SELECT id,customer_email__c FROM Payment_Milestone__c WHERE id=:payMile1.id];
        system.debug(payMileStone.customer_email__c);
        
    }
}