force-app/main/default/objects/Setup_Configuration__c/Setup_Configuration__c.object-meta.xml
<CustomObject>
    <label>Setup Configuration</label>
    <nameField>
        <displayFormat>SC -{0000000000}</displayFormat>
        <label>Setup Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setup Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Setup_Configuration__c/fields/Operation_Status__c.field-meta.xml
<CustomField>
    <fullName>Operation_Status__c</fullName>
    <label>Operation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Setup_Configuration__c/fields/Type_Of_Transfer__c.field-meta.xml
<CustomField>
    <fullName>Type_Of_Transfer__c</fullName>
    <label>Type Of Transfer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IM Transfer</fullName>
            </value>
            <value>
                <fullName>Freelancer Transfer</fullName>
            </value>
            <value>
                <fullName>Telecaller Transfer</fullName>
            </value>
            <value>
                <fullName>Nimbus Transfer</fullName>
            </value>
            <value>
                <fullName>Doowup Transfer</fullName>
            </value>
            <value>
                <fullName>Doowup Presales Transfer</fullName>
            </value>
            <value>
                <fullName>Nimbus DL Offline Transfer</fullName>
            </value>
            <value>
                <fullName>Nimbus DL Digital Transfer</fullName>
            </value>
            <value>
                <fullName>Offline Relanded Transfer</fullName>
            </value>
            <value>
                <fullName>IM Classification</fullName>
            </value>
            <value>
                <fullName>Inside Sales Transfer</fullName>
            </value>
            <value>
                <fullName>Nimbus Relanded Transfer</fullName>
            </value>
            <value>
                <fullName>Nimbus Hindi Transfer</fullName>
            </value>
            <value>
                <fullName>Nimbus Telugu Transfer</fullName>
            </value>
            <value>
                <fullName>Cubico Transfer</fullName>
            </value>
            <value>
                <fullName>Nimbus Doowup Offline Transfer</fullName>
            </value>
            <value>
                <fullName>Nimbus HL Missed Call Transfer</fullName>
            </value>
            <value>
                <fullName>Nimbus Doowup Opp Transfer</fullName>
            </value>
            <value>
                <fullName>Globiva Offline RL Transfer</fullName>
            </value>
            <value>
                <fullName>Globiva Offline PB Transfer</fullName>
            </value>
            <value>
                <fullName>Globiva Relanded Transfer</fullName>
            </value>
            <value>
                <fullName>Globiva Feedback Digital Transfer</fullName>
            </value>
            <value>
                <fullName>Globiva Digital North Transfer</fullName>
            </value>
            <value>
                <fullName>Globiva Digital South Transfer</fullName>
            </value>
            <value>
                <fullName>Globiva Digital East Transfer</fullName>
            </value>
            <value>
                <fullName>Globiva Digital West Transfer</fullName>
            </value>
            <value>
                <fullName>Globiva Digital Centre Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SetUpConfigDeleteBatch.cls
global class SetUpConfigDeleteBatch implements Database.Batchable<sObject>,Schedulable { 
    
    Set<String> TypeOfTransfer = new Set<String>{'IM Transfer','Freelancer Transfer'};
   
    global Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'Select Id,Operation_Status__c from Setup_Configuration__c where Operation_Status__c=\'Closed\' AND Type_Of_Transfer__c IN:TypeOfTransfer';
        return Database.getQueryLocator(query);
    }
 
    
    global void execute( Database.BatchableContext bc , List<Setup_Configuration__c> setUpConfigList) {
         try{
            delete  setUpConfigList;
        }catch(Exception e){
            system.debug('-------exp finish-----------'+e.getmessage());
        }
    }
    
    
    global void finish(Database.BatchableContext bc) {
        
    }
    global void execute(SchedulableContext sc) {
        Database.executeBatch(new SetUpConfigDeleteBatch());
    }
}