force-app/main/default/objects/Agent_Roster__c/Agent_Roster__c.object-meta.xml
<CustomObject>
    <label>Agent Roaster</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Roster Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agent Roasters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Agent_Roster__c/fields/Login_Active_Status__c.field-meta.xml
<CustomField>
    <fullName>Login_Active_Status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Login Active Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Agent_Roster__c/fields/Reporting_Time__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Time__c</fullName>
    <label>Reporting Time</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Agent_Roster__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Employee</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RR_Deactivate_Time__c/RR_Deactivate_Time__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This setting is use to capture the date and time of round robin deactivation.</description>
    <label>RR Deactivate Time</label>
</CustomObject>

force-app/main/default/objects/RR_Deactivate_Time__c/fields/Reporting_Time__c.field-meta.xml
<CustomField>
    <fullName>Reporting_Time__c</fullName>
    <label>Reporting Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AgentSignInController.cls
public Class AgentSignInController{

public string strPageMessage{get;set;}
public boolean isLoggedIn{get;set;}
public AgentSignInController(){
    
    
}

    public void UpdateUserRoster(){
        try{
            RR_Deactivate_Time__c RRDT = RR_Deactivate_Time__c.getvalues('Daily Time');
        Agent_Roster__c objLeave = [Select Id,User__c,Reporting_Time__c,Login_Active_Status__c From Agent_Roster__c Where Apply_Date__c =: System.Today() AND User__c =: Userinfo.getuserid() Limit 1];
        if(objLeave.Login_Active_Status__c == true){
            strPageMessage = 'You are already logged In.';
        }else{
            Integer ReportTime = Integer.valueof(RRDT.Reporting_Time__c);
            if(objLeave.Reporting_Time__c =='OFF' || objLeave.Reporting_Time__c =='Leave')
                objLeave.Reporting_Time__c = ReportTime+':00 AM';
            objLeave.Login_Active_Status__c = true;
            update objLeave; 
            strPageMessage = 'You have Sucessfully logged In.';         
        }
        isLoggedIn = true;
        }catch(Exception exp){
            strPageMessage ='Your Roster is not updated. Please coordinate with your reporting manager.';
        }
    }
    public void LogOutUser(){
        try{
            RR_Deactivate_Time__c RRDT = RR_Deactivate_Time__c.getvalues('Daily Time');
        Agent_Roster__c objLeave = [Select Id,User__c,Reporting_Time__c,Login_Active_Status__c From Agent_Roster__c Where Apply_Date__c =: System.Today() AND User__c =: Userinfo.getuserid() Limit 1];
        if(objLeave.Login_Active_Status__c == true){
            objLeave.Login_Active_Status__c = false;
            update objLeave; 
            strPageMessage = 'You have Sucessfully logged Out.';         
        }
        isLoggedIn = false;
        }catch(Exception exp){
            strPageMessage ='Your Roster is not updated. Please coordinate with your reporting manager.';
        }
    }

}