force-app/main/default/objects/WebEngage_Task__c/WebEngage_Task__c.object-meta.xml
<CustomObject>
    <label>WebEngage Task</label>
    <nameField>
        <label>WebEngage Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WebEngage Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WebEngage_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Open&apos;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/WebEngageTaskDelete_Batch.cls
global class WebEngageTaskDelete_Batch  implements Database.Batchable<sObject>,Schedulable {
  global Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'SELECT Id, Name FROM WebEngage_Task__c where Status__c=\'Closed\'';
        return Database.getQueryLocator(query);
    }
     global void execute( Database.BatchableContext bc , List<WebEngage_Task__c> webengageList) {
         try{
             if(!webengageList.isEmpty()){
                 delete webengageList ;
             }
            
        }catch(Exception e){
            system.debug('-------exp finish-----------'+e.getmessage());
            Logger.log('Exception','WebEngageTaskDelete_Batch Class','Execute Method',e.getMessage(),e.getStackTraceString(),null);
        }
    }
    
    global void finish(Database.BatchableContext bc) {
        
    }
    global void execute(SchedulableContext sc) {
        Database.executeBatch(new WebEngageTaskDelete_Batch ());
    }
 
}