force-app/main/default/objects/WebEngage_Task__c/WebEngage_Task__c.object-meta.xml
<CustomObject>
    <label>WebEngage Task</label>
    <nameField>
        <label>WebEngage Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WebEngage Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WebEngage_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Open&apos;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/WebEngageTaskDelete_Test.cls
@isTest
public class WebEngageTaskDelete_Test {
    
    Public static WebEngage_Task__c webEngageTask;
    Public static Lead ld;
    @TestSetup static void data() {
        ld = TestData_Factory.CreateFreshLead(false);
        insert ld;
        webEngageTask = TestData_Factory.createWebEngageEventTask(ld.id,null,'Appointment Details Updated','Change Event',true);
    }
    
    public testMethod static void WebEngageTest1(){
        
        Test.startTest();
        WebEngage_Task__c webTaskList =[select id from WebEngage_Task__c limit 1];
        webTasklist.Status__c='Closed';
        update webTaskList;
        
        WebEngageTaskDelete_Batch webTask = new WebEngageTaskDelete_Batch();
        database.executeBatch(webTask);
        Test.stopTest();
    }
    public testMethod static void WebEngageTest2(){
        Test.startTest();
        WebEngageTaskDelete_Batch   sh1 = new WebEngageTaskDelete_Batch();
        
        String sch = '0 0 23 * * ?'; 
        system.schedule('Test Check', sch, sh1); 
        
        Database.executeBatch(new WebEngageTaskDelete_Batch());
        test.stopTest();
    }
    
}